class PBFieldNote
  attr_accessor :fieldeffect
  attr_accessor :text
  attr_accessor :elaboration
  attr_accessor :cogwheeltext

  def initialize(fieldeffect, text, elaboration = "", cogwheeltext = "")
    @fieldeffect = fieldeffect
    @text = text
    @elaboration = elaboration
    @cogwheeltext = cogwheeltext
  end
end

def feToStringName(fieldeffect,dig1,dig2=nil)
  return PBMoves.getName(FIELDEFFECTS.dig(fieldeffect, dig1)) if dig1 == :NATUREMOVES
  if dig2.nil?
    return FIELDEFFECTS.dig(fieldeffect, dig1).map {|id| PBMoves.getName(id) }.sort.uniq.join(", ")
  else
    return FIELDEFFECTS.dig(fieldeffect, dig1, dig2).map {|id| PBMoves.getName(id)}.sort.uniq.join(", ")
  end
end

### General syntax ########################################################################
#up by x1.5                <icon=fieldUp> <c=green>x1.5</c>
#down by 0.5               <icon=fieldDown> <c=red>x0.5</c>
#green                     <c=green></c>
#red                       <c=red></c>         (actually crimson bc funny) (hi ily)
#orange                    <c=orange></c>
#field general             <icon=field>
#field change              <icon=fieldChange>
#field up                  <icon=fieldUp>
#field down                <icon=fieldDown>
#field plus                <icon=fieldPlus>
#type boosted              PBFieldNote.new(1,"Attaques <icon=FieldElectric> attacks <icon=fieldUp> <c=green>x1.5</c> si . . .","...si l'attaquant est au sol."),
#attacks boosted           PBFieldNote.new(1,"Certaines attaques <icon=fieldUp> <c=green>x1.5</c> . . . ",FIELDEFFECTS.dig(PBFields::ELECTRICT, :MOVEDAMAGEBOOST, 1.5)),
#attacks weakened          PBFieldNote.new(1,"Certaines attaques <icon=fieldDown> <c=red>x0.5</c> . . . ",FIELDEFFECTS.dig(PBFields::ELECTRICT, :MOVEDAMAGEBOOST, 0.5)),


# arguments for PBFieldNote are as followed:
# 1: which field the field note belongs to
# 2: The text that's on screen explaining a field phenomenon
# 3: Elaboration on the field phenomenon if no space was left on screen (optional)
# 4: text that appears to the right which shows what stage of field it happens (optional)

def pbCompileFieldNotes
  all_field_notes = [
  #Electric Field
    PBFieldNote.new(1,"<c=orange>\"#{FIELDEFFECTS.dig(PBFields::ELECTRICT, :INTROMESSAGE)}\"</c> "),
    PBFieldNote.new(1,"Pokémon au sol <icon=fieldChange> <icon=fieldNoSleep#{getSuffixFile()}> "),
    PBFieldNote.new(1,"<c=green>Créé</c> par . . .","Créa-Élec, Champ Électrifié (5 tours), Électro-Surf Survolté, Déluge Plasmique (3 tours), Plasma Punch (3 tours), si l'attaquant ne tient pas de Pierre Stase."),
    PBFieldNote.new(1,"Attaques <icon=field#{pbGetTypeNameFile(PBTypes::ELECTRIC)}> <icon=fieldUp> <c=green>x1.5</c> si . . .","...si l'attaquant est au sol."),
    PBFieldNote.new(1,"Certaines attaques <icon=fieldPlus> <icon=field#{pbGetTypeNameFile(PBTypes::ELECTRIC)}> . . . ",feToStringName(PBFields::ELECTRICT,:MOVETYPEMOD,PBTypes::ELECTRIC)),
    PBFieldNote.new(1,"Mitra-Poing <c=red>échoue</c> toujours"),
    PBFieldNote.new(1,"Effet de certaines capacités <icon=fieldUp> . . . ","Chargeur, Ondes Étranges"),
    PBFieldNote.new(1,"Vol Magnétik dure <c=green>8</c> tours"),
    PBFieldNote.new(1,"Certaines attaques <icon=fieldUp> <c=green>x1.5</c> . . . ",feToStringName(PBFields::ELECTRICT,:MOVEDAMAGEBOOST, 1.5)),
    PBFieldNote.new(1,"Puissance de Bombe Aimant <icon=fieldUp> <c=green>x2</c>"),
    PBFieldNote.new(1,"<c=green>Active</c> Surf Caudal"),
    PBFieldNote.new(1,"<c=green>Active</c> Motorisé chaque tour"),
    PBFieldNote.new(1,"<c=red>Désactive</c> Hypersommeil"),
    PBFieldNote.new(1,"Compte à rebours de Début Lent <icon=fieldChange> <c=green>÷2</c>"),
    PBFieldNote.new(1,"Éclair Fou n'a <c=green>pas de recul</c> "),
    PBFieldNote.new(1,"<c=red>Détruit</c> par ces attaques . . .", feToStringName(PBFields::ELECTRICT, :FIELDCHANGE, 0)),
    PBFieldNote.new(1,"Force-Nature <icon=fieldChange> #{feToStringName(PBFields::ELECTRICT, :NATUREMOVES)}"),
    PBFieldNote.new(1,"Camouflage <icon=fieldChange> <icon=field#{pbGetTypeNameFile(PBTypes::ELECTRIC)}> "),
    PBFieldNote.new(1,"Force Cachée <icon=fieldChange> <icon=fieldParalyze> "),
    PBFieldNote.new(1,"Active <c=orange>Graine Élémentaire</c>. . .","Augmente la Vitesse et applique Chargeur."),
  #Grassy Terrain
    PBFieldNote.new(2,"<c=orange>\"#{FIELDEFFECTS.dig(PBFields::GRASSYT, :INTROMESSAGE)}\"</c> "),
    PBFieldNote.new(2,"Pokémon <icon=fieldPlus> <c=green>1/16 PV</c> si . . .", "...si au sol."),
    PBFieldNote.new(2,"<c=green>Créé</c> par . . .","Créa-Herbe, Champ Herbu (5 tours), Pétalexplosion Éblouissante si le Terrain n'est pas Forêt ou Jardin Fleuri (3 tours)."),
    PBFieldNote.new(2,"Attaques <icon=Field#{pbGetTypeNameFile(PBTypes::GRASS)}> <icon=fieldUp> <c=green>x1.5</c> si . . .","...si l'attaquant est au sol."),
    PBFieldNote.new(2,"Attaques <icon=Field#{pbGetTypeNameFile(PBTypes::FIRE)}> <icon=fieldUp> <c=green>x1.5</c> si . . .","...si la cible est au sol."),
    PBFieldNote.new(2,"<c=green>Active</c> Toison Herbue"),
    PBFieldNote.new(2,"Certaines attaques <icon=fieldUp> <c=green>x1.5</c> . . . ",feToStringName(PBFields::GRASSYT, :MOVEDAMAGEBOOST, 1.5)),
    PBFieldNote.new(2,"Certaines attaques <icon=fieldDown> <c=red>x0.5</c> . . . ",feToStringName(PBFields::GRASSYT, :MOVEDAMAGEBOOST, 0.5)),
    PBFieldNote.new(2,"Précision de Siffl'Herbe <icon=fieldChange> <c=green>80</c> "),
    PBFieldNote.new(2,"Effet de certaines capacités <icon=fieldUp> . . .","Croissance, Enroulement"),
    PBFieldNote.new(2,"Dégâts d'Ire de la Nature <icon=fieldChange> <c=green>75 % PV</c> "),
    PBFieldNote.new(2,"Soin Floral rend <c=green>100 %</c> des PV Max"),
    PBFieldNote.new(2,"Devient <c=orange>Terrain Enflammé</c> si . . .", "...si #{feToStringName(PBFields::GRASSYT, :FIELDCHANGE, PBFields::BURNINGF)} est utilisé en l'absence de pluie ou de Tourniquet."),
    PBFieldNote.new(2,"Devient <c=orange>Terrain Corrosif</c> si . . .", "...si #{feToStringName(PBFields::GRASSYT, :FIELDCHANGE, PBFields::CORROSIVEF)} est utilisé."),
    PBFieldNote.new(2,"Force-Nature <icon=fieldChange> Eco-Sphère"),
    PBFieldNote.new(2,"Camouflage <icon=fieldChange> <icon=field#{pbGetTypeNameFile(PBTypes::GRASS)}> "),
    PBFieldNote.new(2,"Force Cachée <icon=fieldChange> <icon=fieldSleep#{getSuffixFile()}> "),
    PBFieldNote.new(2,"Active <c=orange>Graine Élémentaire</c>. . .","Augmente la Défense et applique Racines."),
  #Misty Terrain
    PBFieldNote.new(3,"<c=orange>\"#{FIELDEFFECTS.dig(PBFields::MISTYT, :INTROMESSAGE)}\"</c> "),
    PBFieldNote.new(3,"Pokémon au sol <c=red>immunisés</c> au statut"),
    PBFieldNote.new(3,"<c=green>Créé</c> par . . .","Créa-Brume, Champ Brumeux (5 tours), Brume (3 tours), si l'attaquant ne tient pas de Pierre Stase."),
    PBFieldNote.new(3,"Attaques <icon=FieldDragon> <icon=fieldDown> <c=red>x0.5</c> "),
    PBFieldNote.new(3,"Attaques <icon=Field#{pbGetTypeNameFile(PBTypes::FAIRY)}> <icon=fieldUp> <c=green>x1.5</c> Déf.Spé. "),
    PBFieldNote.new(3,"<c=green>Active</c> Écaille Spéciale"),
    PBFieldNote.new(3,"Peau Sèche <c=green>rend des PV</c> chaque tour"),
    PBFieldNote.new(3,"Boost de Peau Féérique <icon=fieldChange> <c=green>x1.5</c> "),
    PBFieldNote.new(3,"Certaines attaques <icon=fieldUp> <c=green>x1.5</c> . . . ",feToStringName(PBFields::MISTYT, :MOVEDAMAGEBOOST, 1.5)),
    PBFieldNote.new(3,"Certaines attaques <icon=fieldDown> <c=red>x0.5</c> . . . ",feToStringName(PBFields::MISTYT, :MOVEDAMAGEBOOST, 0.5)),
    PBFieldNote.new(3,"AnimaCœur <c=green>augmente</c> aussi Déf.Spé."),
    PBFieldNote.new(3,"Effet de certaines capacités <icon=fieldUp> . . . ","Brume Capiteuse, Force Cosmik"),
    PBFieldNote.new(3,"Doux Parfum <c=red>réduit</c> Déf & Déf.Spé."),
    PBFieldNote.new(3,"Soin de Vœu <icon=fieldChange> <c=green>75 % PV</c> "),
    PBFieldNote.new(3,"Soin d'Anneau Hydro <icon=fieldChange> <c=green>1/8 PV</c> "),
    PBFieldNote.new(3,"<c=red>Détruit</c> par ces attaques . . .", feToStringName(PBFields::MISTYT, :FIELDCHANGE, 0)),
    PBFieldNote.new(3,"Devient <c=orange>Brume Corrosive</c> si . . .", "...si Déluge Causti-Toxique est utilisé, ou si l'une de ces capacités est utilisée deux fois: Bain de Smog, Gaz Toxk, Purédpois."),
    PBFieldNote.new(3,"<c=red>Empêche</c> ces attaques. . .","Caboche-Kaboum, Destruction, Explosion"),
    PBFieldNote.new(3,"<c=green>Active</c> Sable Humide lorsque . . .","...lorsque le Pokémon est envoyé."),
    PBFieldNote.new(3,"Force-Nature <icon=fieldChange> #{feToStringName(PBFields::MISTYT, :NATUREMOVES)}"),
    PBFieldNote.new(3,"Camouflage <icon=fieldChange> <icon=Field#{pbGetTypeNameFile(PBTypes::FAIRY)}> "),
    PBFieldNote.new(3,"Force Cachée <icon=fieldChange> <c=red>réduit</c> Att.Spé."),
    PBFieldNote.new(3,"Active <c=orange>Graine Élémentaire</c>. . .","Augmente la Déf.Spé. et applique Vœu."),
  #Dark Crystal Cavern
    PBFieldNote.new(4,"<c=orange>\"#{FIELDEFFECTS.dig(PBFields::DARKCRYSTALC, :INTROMESSAGE)}\"</c> "),
    #PBFieldNote.new(4,"Attaques <icon=Field#{pbGetTypeNameFile(PBTypes::DARK)}> <icon=fieldUp> <c=green>x1.5</c> "),
    PBFieldNote.new(4,"Certaines attaques <icon=fieldUp> <c=green>x2</c> . . . ",feToStringName(PBFields::DARKCRYSTALC, :MOVEDAMAGEBOOST, 2.0)),
    PBFieldNote.new(4,"Certaines attaques <icon=fieldUp> <c=green>x1.5</c> . . . ",feToStringName(PBFields::DARKCRYSTALC, :MOVEDAMAGEBOOST, 1.5)),
    PBFieldNote.new(4,"Certaines attaques <icon=fieldDown> <c=red>x0.5</c> . . . ",feToStringName(PBFields::DARKCRYSTALC, :MOVEDAMAGEBOOST, 0.5)),
    PBFieldNote.new(4,"Défenses des Pokémon <icon=Field#{pbGetTypeNameFile(PBTypes::DARK)}> <icon=fieldUp> <c=green>x1.5</c>"),
    PBFieldNote.new(4,"Défenses des Pokémon <icon=Field#{pbGetTypeNameFile(PBTypes::GHOST)}> <icon=fieldUp> <c=green>x1.5</c>  "),
    PBFieldNote.new(4,"Effet de certaines capacités <icon=fieldUp> . . . ","Flash"),
    PBFieldNote.new(4,"Précision de Trou Noir <icon=fieldChange> <c=green>100</c> "),
    PBFieldNote.new(4,"Soin de Rayon Lune <icon=fieldChange> <c=green>75 % PV</c> "),
    PBFieldNote.new(4,"Soin de Synthèse/Aurore <icon=fieldChange> <c=red>25 % PV</c> "),
    PBFieldNote.new(4,"<c=red>Empêche</c> ces attaques . . .","Lance-Soleil, Lame Solaire"),
    PBFieldNote.new(4,"Devient <c=orange>Caverne de Cristaux</c> si . . .","...s'il y a du soleil, aussi longtemps que le soleil dure."),
    PBFieldNote.new(4,"Devient une <c=orange>Caverne</c> si . . .", "...si #{feToStringName(PBFields::DARKCRYSTALC, :FIELDCHANGE, PBFields::CAVE)} est utilisé."),
    PBFieldNote.new(4,"<c=green>Autorise</c> Voile Aurore"),
    PBFieldNote.new(4,"Prisme-Armure <c=green>réduit les dégâts</c> x0.75"),
    PBFieldNote.new(4,"Spectro-Bouclier <c=green>réduit</c> les dégâts","Réduit les dégâts des attaques super efficaces x0.75."),
    PBFieldNote.new(4,"Force-Nature <icon=fieldChange> #{feToStringName(PBFields::DARKCRYSTALC, :NATUREMOVES)}"),
    PBFieldNote.new(4,"Camouflage <icon=fieldChange> <icon=field#{pbGetTypeNameFile(FIELDEFFECTS.dig(PBFields::DARKCRYSTALC, :MIMICRY))}> "),
    PBFieldNote.new(4,"Force Cachée <icon=fieldChange> <c=red>réduit</c> Précision"),
    PBFieldNote.new(4,"Active <c=orange>Graine Magique</c>. . .","Augmente la Déf.Spé. et applique Reflet Magik."),
  #Chess Field
    PBFieldNote.new(5,"<c=orange>\"#{FIELDEFFECTS.dig(PBFields::CHESSB, :INTROMESSAGE)}\"</c> "),
    PBFieldNote.new(5,"Les Pokémon deviennent des <c=orange>Pièces</c> . . .","...basées sur des critères spécifiques. Un Pokémon ne peut être qu'une seule Pièce."),
    PBFieldNote.new(5,"<c=orange>Pion</c> : Premier envoyé au combat","Prend le dessus sur tous les rôles sauf la Dame."),
    PBFieldNote.new(5,"<c=orange>Tour</c> : Plus haute stat <icon=fieldChange> Déf/Déf.Spé. "),
    PBFieldNote.new(5,"<c=orange>Fou</c> : Plus haute stat <icon=fieldChange> Att/Att.Spé."),
    PBFieldNote.new(5,"<c=orange>Cavalier</c> : Plus haute stat <icon=fieldChange> Vitesse "),
    PBFieldNote.new(5,"<c=orange>Dame</c> : Dernier membre de l'équipe","Prend le dessus sur tous les autres rôles. Une par équipe."),
    PBFieldNote.new(5,"<c=orange>Roi</c> : Plus bas PV/Roche Royale tenue","Prend le dessus sur Cavalier, Fou et Tour. Un par équipe."),
    PBFieldNote.new(5,"<c=orange>Pièces</c> gagnent les effets suivants:"),
    PBFieldNote.new(5,"<c=orange>Pion</c> : <icon=fieldPlus> effet de la Ceinture Force"),
    PBFieldNote.new(5,"<c=orange>Tour</c> : Def et Déf.Spé. <icon=fieldUp> "),
    PBFieldNote.new(5,"<c=orange>Fou</c> : Att. et Att.Spé. <icon=fieldUp> "),
    PBFieldNote.new(5,"<c=orange>Cavalier</c> : Dégâts sur <c=orange>Dame</c> <c=green>x3</c>...", "...et inflige x1.25 dégâts en combat double lorsqu'il utilise une capacité ciblant les deux adversaires."),
    PBFieldNote.new(5,"<c=orange>Dame</c> : Déf, Déf.Spé. et dégâts <icon=fieldUp> "),
    PBFieldNote.new(5,"<c=orange>Roi</c> : Attaques <icon=fieldPlus> 1 Priorité"),
    PBFieldNote.new(5,"Certaines attaques <icon=fieldChange> <c=orange>Coups d'échecs</c> ","#{PBFields::CHESSMOVES.map {|id| PBMoves.getName(id)}.sort.join(", ")}"),
    PBFieldNote.new(5,"<c=orange>Coups d'échecs</c> <icon=fieldUp> <c=green>x1.5</c> "),
    PBFieldNote.new(5,"<c=orange>Coups d'échecs</c> <icon=fieldPlus> <icon=Field#{pbGetTypeNameFile(PBTypes::ROCK)}> "),
    PBFieldNote.new(5,"<c=orange>Coups d'échecs</c> <icon=fieldUp> <c=green>x2</c> si . . .", "...si la cible a Benêt, Simple, Inconscient, Maladresse, ou est confuse."),
    PBFieldNote.new(5,"<c=orange>Coups d'échecs</c> <icon=fieldDown> <c=red>x0.5</c> si . . .", "...si la cible a Adaptabilité, Synchro, Anticipation ou Télépathe."),
    PBFieldNote.new(5,"Distorsion dure <c=green>8</c> tours"),
    PBFieldNote.new(5,"Dégâts de Prestance Royale <icon=fieldUp> <c=green>x1.5</c> "),
    PBFieldNote.new(5,"Certaines attaques <icon=fieldUp> <c=green>x1.5</c> . . .", feToStringName(PBFields::CHESSB, :MOVEDAMAGEBOOST, 1.5)),
    PBFieldNote.new(5,"Effet de certaines capacités <icon=fieldUp> . . . ","Plénitude, Machination"),
    PBFieldNote.new(5,"Certaines attaques <icon=fieldPlus> <c=green>protection</c> . . .","Bouclier Royal protège de toutes les attaques."),
    PBFieldNote.new(5,"Bouclier Royal <icon=fieldPlus> <c=green>baisse</c> l'Att.Spé."),
    PBFieldNote.new(5,"<c=red>Détruit</c> par ces attaques . . .",feToStringName(PBFields::CHESSB, :FIELDCHANGE, 0)),
    PBFieldNote.new(5,"Force-Nature <icon=fieldChange> #{feToStringName(PBFields::CHESSB, :NATUREMOVES)}"),
    PBFieldNote.new(5,"Camouflage <icon=fieldChange> <icon=field#{pbGetTypeNameFile(PBTypes::PSYCHIC)}> "),
    PBFieldNote.new(5,"Force Cachée <icon=fieldChange> <c=red>réduit</c> Défense"),
    PBFieldNote.new(5,"Active <c=orange>Graine Synthétique</c>. . .","Booste l'Att.Spé. et applique Reflet Magik."),
  #Big Top Arena
    PBFieldNote.new(6,"<c=orange>\"#{FIELDEFFECTS.dig(PBFields::BIGTOPA, :INTROMESSAGE)}\"</c> "),
    PBFieldNote.new(6,"Certaines attaques <icon=fieldChange> <c=orange>Frappes</c> ","Toutes les attaques Combat physiques, #{PBFields::STRIKERMOVES.map {|id| PBMoves.getName(id)}.sort.join(", ")}"),
    PBFieldNote.new(6,"<c=orange>Frappes</c> <icon=fieldChange> dégâts aléatoires","Jets de dégâts entre x0.5 et x3."),
    PBFieldNote.new(6,"<c=orange>Frappes</c> <icon=fieldChange> <c=green>hauts jets</c> si . . .", "...si l'attaquant possède un de ces talents: Sans Limite, Cran, Coloforce, Force Pure."),
    PBFieldNote.new(6,"Jets de dégâts basés sur l'Attaque","Une Attaque boostée augmente les chances de faire des jets hauts. Une Attaque réduite les baisse, peu importe le talent."),
    PBFieldNote.new(6,"Acrobatie <icon=fieldChange> toujours <c=green>boosté</c>"),
    PBFieldNote.new(6,"Attaques sonores <icon=fieldUp> <c=green>x1.5</c> "),
    PBFieldNote.new(6,"Effet et Puissance de Jackpot <icon=fieldUp> "),
    PBFieldNote.new(6,"Certaines attaques <icon=fieldUp> <c=green>x1.5</c> . . .", feToStringName(PBFields::BIGTOPA, :MOVEDAMAGEBOOST, 1.5)),
    PBFieldNote.new(6,"Encore dure <c=green>6</c> tours"),
    PBFieldNote.new(6,"Effet de certaines capacités <icon=fieldUp> . . . ","Danse Draco, Papillodanse, Danse-Lames, Danse-Plume."),
    PBFieldNote.new(6,"Précision de Berceuse <icon=fieldChange> <c=green>100</c> "),
    PBFieldNote.new(6,"Danse Pluie dure <c=green>8</c> tours"),
    PBFieldNote.new(6,"Cognobidon <c=green>augmente</c> Def/Déf.Spé."),
    PBFieldNote.new(6,"Projecteur <c=green>augmente</c> Atk/Att.Spé. . . .", "...de la cible et du lanceur."),
    PBFieldNote.new(6,"Danseur <c=green>augmente</c> Vit/Att.Spé. . . .","...quand une capacité de Danse est utilisée lors de son tour."),
    PBFieldNote.new(6,"Force-Nature <icon=fieldChange> #{feToStringName(PBFields::BIGTOPA, :NATUREMOVES)}"),
    PBFieldNote.new(6,"Camouflage <icon=fieldChange> <icon=field#{pbGetTypeNameFile(PBTypes::NORMAL)}> "),
    PBFieldNote.new(6,"Force Cachée <icon=fieldChange> <c=red>réduit</c> Déf.Spé."),
    PBFieldNote.new(6,"Active <c=orange>Graine Synthétique</c>. . .","Augmente l'Attaque et applique Coup d'Main."),
  #Burning Field
    PBFieldNote.new(7,"<c=orange>\"#{FIELDEFFECTS.dig(PBFields::BURNINGF, :INTROMESSAGE)}\"</c> "),
    PBFieldNote.new(7,"<c=orange>Dégâts</c> <icon=field#{pbGetTypeNameFile(PBTypes::FIRE)}> en fin de tour   si . . .","...si au sol et pas de type Feu."),
    PBFieldNote.new(7,"<c=green>Immunité</c> aux <c=orange>dégâts de terrain</c> si . . .", "...si l'un de ces talents est actif: Corps Ardent, Rage Brûlure, Torche, Ignifugé, Armumagma, Aquabulle, Ignifu-voile."),
    PBFieldNote.new(7,"<c=orange>Dégâts de terrain</c> <icon=fieldUp> si . . .","...si l'un de ces talents est actif: Boule de Poils, Toison Herbue, Corps Gel, Feuille Garde"),
    PBFieldNote.new(7,"<c=green>Créé</c> par Aire d'Herbe <icon=fieldPlus> Aire de Feu"),
    PBFieldNote.new(7,"Attaques <icon=Field#{pbGetTypeNameFile(PBTypes::FIRE)}> <icon=fieldUp> <c=green>x1.5</c> si . . .","...si l'attaquant est au sol."),
    PBFieldNote.new(7,"Attaques <icon=Field#{pbGetTypeNameFile(PBTypes::GRASS)}> <icon=fieldDown> <c=red>x0.5</c> si . . .","...si la cible est au sol."),
    PBFieldNote.new(7,"Attaques <icon=Field#{pbGetTypeNameFile(PBTypes::ICE)}> <icon=fieldDown> <c=red>x0.5</c> "),
    PBFieldNote.new(7,"<c=red>Détruit</c> par ces attaques . . .",feToStringName(PBFields::BURNINGF, :FIELDCHANGE, 0)),
    PBFieldNote.new(7,"<c=red>Détruit</c> par le Sable et la Pluie"),
    PBFieldNote.new(7,"<c=green>Active</c> certains talents . . .","Brasier, Rage Brûlure, Torche"),
    PBFieldNote.new(7,"Précision de Feu Follet<icon=fieldChange> <c=green>100</c> "),
    PBFieldNote.new(7,"Les Pokémon ne peuvent pas être <icon=fieldFreeze#{getSuffixFile()}> "),
    PBFieldNote.new(7,"Effet de Brouillard <icon=fieldUp> "),
    PBFieldNote.new(7,"Dégâts de Danse Flamme <icon=fieldChange> <c=green>1/6 PV</c> "),
    PBFieldNote.new(7,"Certaines attaques <icon=fieldPlus> <icon=field#{pbGetTypeNameFile(PBTypes::FIRE)}> . . . ",feToStringName(PBFields::BURNINGF, :MOVETYPEMOD, PBTypes::FIRE)),
    PBFieldNote.new(7,"Certaines attaques <icon=fieldUp> <c=green>x1.5</c> . . . ",feToStringName(PBFields::BURNINGF, :MOVEDAMAGEBOOST, 1.5)),
    PBFieldNote.new(7,"Certaines attaques <icon=fieldUp> <c=green>x2</c> . . . ",feToStringName(PBFields::BURNINGF, :MOVEDAMAGEBOOST, 2.0)),
    PBFieldNote.new(7,"<c=green>Restaure</c> <icon=field#{pbGetTypeNameFile(PBTypes::FIRE)}> après Flamme Ultime"),
    PBFieldNote.new(7,"Force-Nature <icon=fieldChange> #{feToStringName(PBFields::BURNINGF, :NATUREMOVES)}"),
    PBFieldNote.new(7,"Camouflage <icon=fieldChange> <icon=field#{pbGetTypeNameFile(PBTypes::FIRE)}> "),
    PBFieldNote.new(7,"Force Cachée <icon=fieldChange> <icon=fieldBurn#{getSuffixFile()}> "),
    PBFieldNote.new(7,"Active <c=orange>Graine Élémentaire</c>. . .","Augmente l'Attaque, l'Att.Spé. et la Vitesse, mais applique Danse Flamme."),
  #Swamp Field
    PBFieldNote.new(8,"<c=orange>\"#{FIELDEFFECTS.dig(PBFields::SWAMPF, :INTROMESSAGE)}\"</c> "),
    PBFieldNote.new(8,"Vitesse des Pokémon <icon=fieldDown> chaque tour."),
    PBFieldNote.new(8,"Pokémon en l'air <c=green>immunisés</c> . . .","au ralentissement."),
    PBFieldNote.new(8,"<c=green>Créé</c> par Aire d'Eau <icon=fieldPlus> Aire d'Herbe"),
    PBFieldNote.new(8,"Racines <c=red>blesse</c> le lanceur sauf . . .", "...sauf si le lanceur est de type Poison ou Acier."),
    PBFieldNote.new(8,"Peau Sèche <c=green>rend des PV</c> "),
    PBFieldNote.new(8,"Soin d'Anneau Hydro <icon=fieldChange> <c=green>1/8 PV</c> "),
    PBFieldNote.new(8,"Attaques <icon=Field#{pbGetTypeNameFile(PBTypes::POISON)}> <icon=fieldUp> <c=green>x1.5</c> si . . .","...si la cible est au sol."),
    PBFieldNote.new(8,"Certaines attaques <icon=fieldUp> <c=green>x1.5</c> . . . ",feToStringName(PBFields::SWAMPF, :MOVEDAMAGEBOOST, 1.5)),
    PBFieldNote.new(8,"Certaines attaques <icon=fieldDown> <c=red>x0.25</c> . . . ",feToStringName(PBFields::SWAMPF, :MOVEDAMAGEBOOST, 0.25)),
    PBFieldNote.new(8,"Certaines attaques <icon=fieldPlus> <icon=field#{pbGetTypeNameFile(PBTypes::WATER)}> . . . ",feToStringName(PBFields::SWAMPF, :MOVETYPEMOD, PBTypes::WATER)),
    PBFieldNote.new(8,"<c=red>Empêche</c> ces attaques . . .","Explosion, Caboche-Kaboum, Destruction"),
    PBFieldNote.new(8,"Précision de Poudre Dodo <icon=fieldChange> <c=green>100</c> "),
    PBFieldNote.new(8,"Pokémon <icon=FieldSleep#{getSuffixFile()}> <c=red>blessés</c> chaque tour"),
    PBFieldNote.new(8,"Effet de Poisseux <icon=fieldUp> <c=green>x2</c> "),
    PBFieldNote.new(8,"<c=green>Active</c> Sable Humide <c=green>chaque tour</c>."),
    PBFieldNote.new(8,"Soin de Vol-Force <icon=fieldUp> <c=green>x1.3</c> "),
    PBFieldNote.new(8,"Force-Nature <icon=fieldChange> #{feToStringName(PBFields::SWAMPF, :NATUREMOVES)}"),
    PBFieldNote.new(8,"Camouflage <icon=fieldChange> <icon=Field#{pbGetTypeNameFile(PBTypes::WATER)}> "),
    PBFieldNote.new(8,"Force Cachée <icon=fieldChange> <c=red>réduit</c> la Vitesse"),
    PBFieldNote.new(8,"Active <c=orange>Graine Tellurique</c>. . .","Augmente la Défense, la Déf.Spé. et applique Racines."),
  #Rainbow Field
    PBFieldNote.new(9,"<c=orange>\"#{FIELDEFFECTS.dig(PBFields::RAINBOWF, :INTROMESSAGE)}\"</c> "),
    PBFieldNote.new(9,"Chances d'effets secondaires <icon=fieldUp> <c=green>x2</c> "),
    PBFieldNote.new(9,"<c=green>Créé</c> par Aire de Feu <icon=fieldPlus> Aire d'Eau"),
    PBFieldNote.new(9,"<c=green>Créé</c> par Soleil <icon=fieldPlus> Pluie"),
    PBFieldNote.new(9,"Ciel Gris <icon=fieldUp> . . . ","...augmente une statistique au hasard à la fin de chaque tour."),
    PBFieldNote.new(9,"<c=green>Active</c> Écaille Spéciale"),
    PBFieldNote.new(9,"Peau Miracle <c=green>s'active</c> toujours "),
    PBFieldNote.new(9,"Attaques <icon=Field#{pbGetTypeNameFile(PBTypes::NORMAL)}> spéciales <icon=fieldUp> <c=green>x1.5</c> "),
    PBFieldNote.new(9,"Attaques <icon=Field#{pbGetTypeNameFile(PBTypes::NORMAL)}> spéciales <icon=fieldPlus> <icon=Field#{pbGetTypeNameFile(PBTypes::QMARKS)}> ","Les attaques Normal spéciales gagnent un type aléatoire."),
    PBFieldNote.new(9,"Certaines attaques <icon=fieldUp> <c=green>x1.5</c> . . . ",feToStringName(PBFields::RAINBOWF, :MOVEDAMAGEBOOST, 1.5)),
    PBFieldNote.new(9,"Certaines attaques <icon=fieldDown> <c=red>x0.5</c> . . . ",feToStringName(PBFields::RAINBOWF, :MOVEDAMAGEBOOST, 0.5)),
    PBFieldNote.new(9,"Effet de certaines capacités <icon=fieldUp> . . . ","Force Cosmik, Yoga"),
    PBFieldNote.new(9,"Certaines attaques <icon=fieldChange> <c=green>pas de charge</c> ","Lance-Soleil, Lame Solaire"), 
    PBFieldNote.new(9,"Soin de Vœu <icon=fieldChange> <c=green>75 % PV</c> "),
    PBFieldNote.new(9,"Cauchemar et Mauvais Rêve <c=red>échouent</c> "),
    PBFieldNote.new(9,"Pokémon <icon=FieldSleep#{getSuffixFile()}> sont <c=green>soignés</c> chaque tour"),
    PBFieldNote.new(9,"Dégâts de Sonic Boom <icon=fieldChange> <c=green>140</c> "),
    PBFieldNote.new(9,"<c=red>Détruit</c> si . . .","...si le Sable ou la Grêle sont actifs, ou si Apocalypsis Luminis est utilisé."),
    PBFieldNote.new(9,"<c=green>Autorise</c> Voile Aurore"),
    PBFieldNote.new(9, "Animacœur <c=green>augmente</c> aussi la Déf.Spé."),
    PBFieldNote.new(9,"Prisme-Armure <c=green>réduit les dégâts</c> x0.75"),
    PBFieldNote.new(9,"Force-Nature <icon=fieldChange> #{feToStringName(PBFields::RAINBOWF, :NATUREMOVES)}"),
    PBFieldNote.new(9,"Camouflage <icon=fieldChange> <icon=fieldDragon> "),
    PBFieldNote.new(9,"Force Cachée <icon=fieldChange> statut aléatoire"),
    PBFieldNote.new(9,"Active <c=orange>Graine Magique</c>. . .","Augmente l'Att.Spé. et applique Vœu."),
  #Corrosive Field
    PBFieldNote.new(10,"<c=orange>\"#{FIELDEFFECTS.dig(PBFields::CORROSIVEF, :INTROMESSAGE)}\"</c> "),
    PBFieldNote.new(10,"Inflige <c=orange>dégâts de piège</c> <icon=Field#{pbGetTypeNameFile(PBTypes::POISON)}> si . . .","...si au sol."),
    PBFieldNote.new(10,"Pas de <c=orange>dégâts de piège</c> si . . .", "...si le Pokémon est de type Poison ou Acier, ou si l'un de ces talents est actif: Vaccin, Soin Poison, Rage Poison, Garde Mystik" ),
    PBFieldNote.new(10,"Racines <c=red>blesse</c> le lanceur sauf si . . .","...sauf si le Pokémon est de type Poison ou Acier."),
    PBFieldNote.new(10,"Toison Herbue <c=red>blesse</c> sauf si...","...sauf si le Pokémon est de type Poison ou Acier."),
    PBFieldNote.new(10,"<c=green>Active</c> certains talents si . . .","...si le Pokémon est au sol, active Soin Poison et Rage Poison."),
    PBFieldNote.new(10,"Attaques <icon=Field#{pbGetTypeNameFile(PBTypes::GRASS)}> <icon=fieldPlus> <icon=Field#{pbGetTypeNameFile(PBTypes::POISON)}> "),
    PBFieldNote.new(10,"Certaines attaques <icon=fieldPlus> <icon=Field#{pbGetTypeNameFile(PBTypes::POISON)}> . . . ",feToStringName(PBFields::CORROSIVEF, :MOVETYPEMOD, PBTypes::POISON)),
    PBFieldNote.new(10,"Certaines attaques <icon=fieldUp> <c=green>x1.5</c> . . . ",feToStringName(PBFields::CORROSIVEF, :MOVEDAMAGEBOOST, 1.5)),
    PBFieldNote.new(10,"Certaines attaques <icon=fieldUp> <c=green>x2</c> . . . ",feToStringName(PBFields::CORROSIVEF, :MOVEDAMAGEBOOST, 2.0)),
    PBFieldNote.new(10,"Effet d'Acidarmure <icon=fieldUp> "),
    PBFieldNote.new(10,"<c=green>Active</c> Piège de Venin"),
    PBFieldNote.new(10,"<c=green>Active</c> Choc Venin"),
    PBFieldNote.new(10,"Précision de ces capacités <icon=fieldChange> <c=green>100</c> ","Para-Spore, Poudre Toxik, Poudre Dodo, Toxik"),
    PBFieldNote.new(10,"Pokémon <icon=FieldSleep#{getSuffixFile()}> <c=red>blessés</c> sauf . . .", "...sauf s'ils sont de type Poison ou Acier, ou possèdent Garde Mystik."),
    PBFieldNote.new(10,"Pics Toxik <c=red>ne peuvent</c> être absorbés"),
    PBFieldNote.new(10,"Devient <c=orange>Champ Herbu</c> si . . .","...si Fulmigraine est utilisé."),
    PBFieldNote.new(10,"<c=green>Active</c> Cruauté"),
    PBFieldNote.new(10,"Dégâts de Corrosion <icon=fieldUp> <c=green>x1.5</c> "),
    PBFieldNote.new(10,"Soin Floral <icon=fieldPlus> <icon=FieldPoisonStatus#{getSuffixFile()}> "),
    PBFieldNote.new(10,"Force-Nature <icon=fieldChange> #{feToStringName(PBFields::CORROSIVEF, :NATUREMOVES)}"),
    PBFieldNote.new(10,"Camouflage <icon=fieldChange> <icon=Field#{pbGetTypeNameFile(PBTypes::POISON)}> "),
    PBFieldNote.new(10,"Force Cachée <icon=fieldChange> <icon=FieldPoisonStatus#{getSuffixFile()}> "),
    PBFieldNote.new(10,"Active <c=orange>Graine Tellurique</c> . . .","Applique Blockhaus."),
  # Corrosive Mist Field
    PBFieldNote.new(11,"<c=orange>\"#{FIELDEFFECTS.dig(PBFields::CORROSIVEMISTF, :INTROMESSAGE)}\"</c> "),
    PBFieldNote.new(11,"Pokémon <icon=fieldChange> <icon=FieldPoisonStatus#{getSuffixFile()}> chaque tour"),
    PBFieldNote.new(11,"Anneau Hydro <c=red>blesse</c> sauf . . .", "...sauf si le Pokémon est de type Poison ou Acier."),
    PBFieldNote.new(11,"Peau Sèche <c=red>blesse</c> sauf . . .", "...sauf si le Pokémon est de type Poison ou Acier."),
    PBFieldNote.new(11,"Certaines attaques <icon=fieldPlus> <icon=Field#{pbGetTypeNameFile(PBTypes::POISON)}> . . . ","Toutes les attaques Vol spéciales, " + feToStringName(PBFields::CORROSIVEMISTF, :MOVETYPEMOD, PBTypes::POISON)),
    PBFieldNote.new(11,"Certaines attaques <icon=fieldUp> <c=green>x1.5</c> . . . ",feToStringName(PBFields::CORROSIVEMISTF, :MOVEDAMAGEBOOST, 1.5)),
    PBFieldNote.new(11,"Effet d'Acidarmure <icon=fieldUp> "),
    PBFieldNote.new(11,"<c=green>Active</c> Piège de Venin"),
    PBFieldNote.new(11,"<c=green>Active</c> Choc Venin"),
    PBFieldNote.new(11,"Précision de Toxik <icon=fieldChange> <c=green>100</c> "),
    PBFieldNote.new(11,"Dégâts de Boom Final <icon=fieldChange> <c=green>50 % PV</c> "),
    PBFieldNote.new(11,"Attaques <icon=Field#{pbGetTypeNameFile(PBTypes::FIRE)}> <icon=fieldUp> <c=green>x1.5</c> "),
    PBFieldNote.new(11,"<c=green>Active</c> Cruauté"),
    PBFieldNote.new(11,"Dégâts de Corrosion <icon=fieldUp> <c=green>x1.5</c> "),
    PBFieldNote.new(11,"Soin Floral <icon=fieldPlus> <icon=FieldPoisonStatus#{getSuffixFile()}> "),
    PBFieldNote.new(11,"<c=green>Active</c> Sable Humide . . .","...chaque tour."),
    PBFieldNote.new(11,"<c=red>Détruit</c> par ces attaques . . .",feToStringName(PBFields::CORROSIVEMISTF, :FIELDCHANGE, 0)),
    PBFieldNote.new(11,"Tous les Pokémon <icon=fieldFaint#{getSuffixFile()}> si . . .", "...si l'une de ces attaques est utilisée en l'absence de Moiteur, sauf s'ils ont Torche: " + (PBFields::IGNITEMOVES + [PBMoves::SELFDESTRUCT, PBMoves::EXPLOSION]).map {|id| PBMoves.getName(id)}.sort.join(", ")),
    PBFieldNote.new(11,"Devient <c=orange>Terrain Corrosif</c> si . . .","...si Gravité est utilisé."),
    PBFieldNote.new(11,"Devient <c=orange>Champ Brumeux</c> si . . .","...si Fulmigraine est utilisé."),
    PBFieldNote.new(11,"Force-Nature <icon=fieldChange> #{feToStringName(PBFields::CORROSIVEMISTF, :NATUREMOVES)}"),
    PBFieldNote.new(11,"Camouflage <icon=fieldChange> <icon=Field#{pbGetTypeNameFile(PBTypes::POISON)}> "),
    PBFieldNote.new(11,"Force Cachée <icon=fieldChange> <icon=FieldPoisonStatus#{getSuffixFile()}> "),
    PBFieldNote.new(11,"Active <c=orange>Graine Élémentaire</c> . . .","Augmente l'Attaque et l'Att.Spé. et empoisonne gravement."),
  #Desert Field
    PBFieldNote.new(12,"<c=orange>\"#{FIELDEFFECTS.dig(PBFields::DESERTF, :INTROMESSAGE)}\"</c> "),
    PBFieldNote.new(12,"Attaques <icon=Field#{pbGetTypeNameFile(PBTypes::GROUND)}> <icon=fieldUp> <c=green>x1.5</c> Déf.Spé."),
    PBFieldNote.new(12,"<c=green>Active </c> certains talents . . .","Force Sable, Baigne Sable, Voile Sable."),
    PBFieldNote.new(12,"Le Soleil et le Sable durent <c=green>8</c> tours"),
    PBFieldNote.new(12,"Certaines attaques <icon=fieldUp> <c=green>x1.5</c> . . . ",feToStringName(PBFields::DESERTF, :MOVEDAMAGEBOOST, 1.5)),
    PBFieldNote.new(12,"Effet de Jet de Sable <icon=fieldUp> "),
    PBFieldNote.new(12,"Peau Sèche <c=red>blesse</c> l'utilisateur"),
    PBFieldNote.new(12,"Dégâts de Tourbi-Sable <icon=fieldChange> <c=green>1/6 PV</c> "),
    PBFieldNote.new(12,"Attaques <icon=Field#{pbGetTypeNameFile(PBTypes::WATER)}> <icon=fieldDown> <c=red>x0.5</c> si . . .","...si l'attaquant est au sol."),
    PBFieldNote.new(12,"Attaques <icon=Field#{pbGetTypeNameFile(PBTypes::ELECTRIC)}> <icon=fieldDown> <c=red>x0.5</c> si . . .","...si la cible est au sol."),
    PBFieldNote.new(12,"Amass'Sable <icon=fieldChange> <c=green>100 %</c> PV Max"),
    PBFieldNote.new(12,"Force-Nature <icon=fieldChange> #{feToStringName(PBFields::DESERTF, :NATUREMOVES)}"),
    PBFieldNote.new(12,"Camouflage <icon=fieldChange> <icon=Field#{pbGetTypeNameFile(PBTypes::GROUND)}> "),
    PBFieldNote.new(12,"Force Cachée <icon=fieldChange> <c=red>réduit</c> Précision"),
    PBFieldNote.new(12,"Active <c=orange>Graine Tellurique</c> . . .","Augmente la Défense, la Déf.Spé. et la Vitesse mais applique Tourbi-Sable."),
  #Icy Field
    PBFieldNote.new(13,"<c=orange>\"#{FIELDEFFECTS.dig(PBFields::ICYF, :INTROMESSAGE)}\"</c> "),
    PBFieldNote.new(13,"Certaines attaques <icon=fieldUp> Vitesse si . . .","...si l'attaquant est au sol, ces capacités: Toutes les attaques physiques de contact prioritaires, Boul'Armure, Ruse, Furie-Bond, Roulade, Bulldoboule"),
    PBFieldNote.new(13,"Attaques <icon=Field#{pbGetTypeNameFile(PBTypes::ICE)}> <icon=fieldUp> <c=green>x1.5</c> "),
    PBFieldNote.new(13,"Attaques <icon=Field#{pbGetTypeNameFile(PBTypes::FIRE)}> <icon=fieldDown> <c=red>x0.5</c> "),
    PBFieldNote.new(13,"Certaines attaques <icon=fieldDown> <c=red>x0.5</c> . . . ",feToStringName(PBFields::ICYF, :MOVEDAMAGEBOOST, 0.5)),
    PBFieldNote.new(13,"Attaques <icon=Field#{pbGetTypeNameFile(PBTypes::ROCK)}> <icon=fieldPlus> <icon=Field#{pbGetTypeNameFile(PBTypes::ICE)}> "),
    PBFieldNote.new(13,"Pokémon <icon=Field#{pbGetTypeNameFile(PBTypes::ICE)}> <icon=fieldUp> <c=green>x1.5</c> Défense  si . . .", "...s'il grêle"),
    PBFieldNote.new(13,"Dégâts de <icon=FieldBurn#{getSuffixFile()}> <icon=fieldDown> <c=red>x0.5</c> "),
    PBFieldNote.new(13,"Devient <c=orange>Surface de l'Eau</c> si . . .", "...si #{feToStringName(PBFields::ICYF, :FIELDCHANGE, PBFields::WATERS)} est utilisé, ou si Surface de l'Eau est déjà sous la glace et que #{PBFields::QUAKEMOVES.map {|id| PBMoves.getName(id)}.sort.join(", ")} est utilisé. Devient aussi Surface de l'Eau si Ebullition ou Jet de Vapeur est utilisé deux fois."),
    PBFieldNote.new(13,"<c=green>Crée</c> une rangée de picots si . . .", "...si l'une de ces attaques est utilisée et que Surface de l'Eau n'est pas sous la glace: #{PBFields::QUAKEMOVES.map {|id| PBMoves.getName(id)}.sort.join(", ")}."),
    PBFieldNote.new(13,"Grêle dure <c=green>8</c> tours"),
    PBFieldNote.new(13,"<c=green>Active</c> certains talents . . .","Corps Gel, Rideau Neige, Chasse-Neige"),
    PBFieldNote.new(13,"Boost de Peau Gelée <icon=fieldChange> <c=green>x1.5</c> "),
    PBFieldNote.new(13,"<c=green>Autorise</c> Voile Aurore"),
    PBFieldNote.new(13,"Hydrata-Son <icon=fieldChange> <icon=Field#{pbGetTypeNameFile(PBTypes::ICE)}> "),
    PBFieldNote.new(13,"Force-Nature <icon=fieldChange> #{feToStringName(PBFields::ICYF, :NATUREMOVES)}"),
    PBFieldNote.new(13,"Camouflage <icon=fieldChange> <icon=Field#{pbGetTypeNameFile(PBTypes::ICE)}> "),
    PBFieldNote.new(13,"Force Cachée <icon=fieldChange> <icon=fieldFreeze#{getSuffixFile()}> "),
    PBFieldNote.new(13,"Active <c=orange>Graine Élémentaire</c> . . .","Augmente la Vitesse de deux crans, mais blesse avec des Picots."),
  #Rocky Field
    PBFieldNote.new(14,"<c=orange>\"#{FIELDEFFECTS.dig(PBFields::ROCKYF, :INTROMESSAGE)}\"</c> "),
    PBFieldNote.new(14,"Les Pokémon peuvent <c=orange>esquiver</c> si . . .", "...si la Défense est augmentée ou qu'un clone est actif, les attaques pouvant être bloquées par Pare-Balles peuvent être esquivées derrière un rocher."),
    PBFieldNote.new(14,"Attaques de contact ratées <icon=fieldChange> <c=orange>recul</c> . . .","...sauf si le lanceur a Tête de Roc."),
    PBFieldNote.new(14,"Dégâts de Piège de Roc <icon=fieldUp> <c=green>x2</c> "),
    PBFieldNote.new(14,"Pokémon apeurés <icon=fieldChange> <c=orange>recul</c> . . .", "...sauf s'ils ont Impassible ou Fermeté."),
    PBFieldNote.new(14,"<c=green>Empêche</c> la peur si . . .", "...si la Défense est augmentée."),
    PBFieldNote.new(14,"Certaines attaques <icon=fieldPlus> <icon=Field#{pbGetTypeNameFile(PBTypes::ROCK)}> . . .",feToStringName(PBFields::ROCKYF, :MOVETYPEMOD, PBTypes::ROCK)),
    PBFieldNote.new(14,"Certaines attaques <icon=fieldUp> <c=green>x1.5</c> . . . ",feToStringName(PBFields::ROCKYF, :MOVEDAMAGEBOOST, 1.5)),
    PBFieldNote.new(14,"Attaques <icon=Field#{pbGetTypeNameFile(PBTypes::ROCK)}> <icon=fieldUp> <c=green>x1.5</c> "),
    PBFieldNote.new(14,"Éclate-Roc <icon=fieldUp> <c=green>x2</c> "),
    PBFieldNote.new(14,"Effet de Poliroche <icon=fieldUp> "),
    PBFieldNote.new(14,"Précision de Longue Portée <icon=fieldDown> <c=red>x0.9</c> "),
    PBFieldNote.new(14,"Force-Nature <icon=fieldChange> #{feToStringName(PBFields::ROCKYF, :NATUREMOVES)}"),
    PBFieldNote.new(14,"Camouflage <icon=fieldChange> <icon=Field#{pbGetTypeNameFile(PBTypes::ROCK)}> "),
    PBFieldNote.new(14,"Force Cachée <icon=fieldChange> Apeure"),
    PBFieldNote.new(14,"Active <c=orange>Graine Tellurique</c> . . .","Augmente la Défense, mais applique les dégâts de Piège de Roc."),
  #Forest Field
    PBFieldNote.new(15,"<c=orange>\"#{FIELDEFFECTS.dig(PBFields::FORESTF, :INTROMESSAGE)}\"</c> "),
    PBFieldNote.new(15,"Chances de Pose Spore <icon=fieldUp> <c=green>x2</c> "),
    PBFieldNote.new(15,"<c=green>Active</c> certains talents . . .", "Toison Herbue, Feuil. Garde, Engrais, Essaim"),
    PBFieldNote.new(15,"Attaques <icon=Field#{pbGetTypeNameFile(PBTypes::GRASS)}> <icon=fieldUp> <c=green>x1.5</c> "),
    PBFieldNote.new(15,"Attaques <icon=Field#{pbGetTypeNameFile(PBTypes::BUG)}> spéciales <icon=fieldUp> <c=green>x1.5</c> "),
    PBFieldNote.new(15,"Certaines attaques <icon=fieldUp> <c=green>x1.5</c> . . . ",feToStringName(PBFields::FORESTF, :MOVEDAMAGEBOOST, 1.5)),
    PBFieldNote.new(15,"Coupe <icon=fieldChange> <c=green>x2</c> vs <icon=Field#{pbGetTypeNameFile(PBTypes::GRASS)}> " ),
    PBFieldNote.new(15,"Certaines attaques <icon=fieldDown> <c=red>x0.5</c> . . . ",feToStringName(PBFields::FORESTF, :MOVEDAMAGEBOOST, 0.5)),
    PBFieldNote.new(15,"Herbivore <c=green>rend des PV</c> chaque tour"),
    PBFieldNote.new(15,"Soin de Racines <icon=fieldUp> <c=green>x2</c> "),
    PBFieldNote.new(15,"Effet de certaines capacités <icon=fieldUp> . . .","Appel Défense, Croissance"),
    PBFieldNote.new(15,"Soin de Appel Soins <icon=fieldChange> <c=green>66 %</c> "),
    PBFieldNote.new(15,"Effet de Toile Gluante <icon=fieldUp> <c=green>x2</c> "),
    PBFieldNote.new(15,"Précision de Longue Portée <icon=fieldDown> <c=red>x0.9</c> "),
    PBFieldNote.new(15,"Soin de Vol-Force <icon=fieldUp> <c=green>x1.3</c> "),
    PBFieldNote.new(15,"Dégâts d'Ire de la Nature <icon=fieldChange> <c=green>75 %</c> "),
    PBFieldNote.new(15,"Maléfice Sylvain <icon=fieldPlus> . . .","Maléfice Sylvain applique l'effet de Malédiction en plus de son effet habituel."),
    PBFieldNote.new(15,"Devient <c=orange>Terrain Enflammé</c> si . . .", "...si #{feToStringName(PBFields::FORESTF, :FIELDCHANGE, PBFields::BURNINGF)} est utilisé en l'absence de pluie ou de Tourniquet."),
    PBFieldNote.new(15,"Force-Nature <icon=fieldChange> #{feToStringName(PBFields::FORESTF, :NATUREMOVES)}"),
    PBFieldNote.new(15,"Camouflage <icon=fieldChange> <icon=Field#{pbGetTypeNameFile(PBTypes::GRASS)}> "),
    PBFieldNote.new(15,"Force Cachée <icon=fieldChange> <icon=fieldSleep#{getSuffixFile()}> "),
    PBFieldNote.new(15,"Active <c=orange>Graine Tellurique</c> . . .","Applique Pico-Défense."),
  #Super-Heated Field
    PBFieldNote.new(16,"<c=orange>\"#{FIELDEFFECTS.dig(PBFields::SUPERHEATEDF, :INTROMESSAGE)}\"</c> "),
    PBFieldNote.new(16,"Attaques <icon=Field#{pbGetTypeNameFile(PBTypes::FIRE)}> <icon=fieldUp> <c=green>x1.1</c> "),
    PBFieldNote.new(16,"Attaques <icon=Field#{pbGetTypeNameFile(PBTypes::ICE)}> <icon=fieldDown> <c=red>x0.5</c> "),
    PBFieldNote.new(16,"Attaques <icon=Field#{pbGetTypeNameFile(PBTypes::WATER)}> <icon=fieldDown> <c=red>x0.9</c> "),
    PBFieldNote.new(16,"Certaines attaques <icon=fieldDown> <c=red>x0.5</c> . . . ",feToStringName(PBFields::SUPERHEATEDF, :MOVEDAMAGEBOOST, 0.625)),
    PBFieldNote.new(16,"Certaines attaques <icon=fieldChange> <c=orange>vapeur</c> . . .","Super Tourbillon Abyssal, Ocroupi, Symphonie des Ondines, Aria de l'Écume, Surf, Aire d'Eau, Tourniquet, et Giclédo génèrent de la vapeur, réduisant la Précision de tous les Pokémon."),
    PBFieldNote.new(16,"Certaines attaques <icon=fieldUp> <c=green>x1.5</c> . . . ",feToStringName(PBFields::SUPERHEATEDF, :MOVEDAMAGEBOOST, 1.667)),
    PBFieldNote.new(16,"Devient <c=orange>Terrain Enflammé</c> si . . .","...si #{feToStringName(PBFields::SUPERHEATEDF, :FIELDCHANGE, PBFields::BURNINGF)} est utilisé en l'absence de pluie ou de Tourniquet."),
    PBFieldNote.new(16,"<c=red>Détruit</c> par ces attaques . . .", feToStringName(PBFields::SUPERHEATEDF, :FIELDCHANGE, 0)),
    PBFieldNote.new(16,"Grêle <c=red>échoue</c> "),
    PBFieldNote.new(16,"Fatigue après <c=red>1</c> tour . . .","Colère, Danse-Fleur et Mania rendent confus le lanceur dès le premier tour."),
    PBFieldNote.new(16,"Force-Nature <icon=fieldChange> #{feToStringName(PBFields::SUPERHEATEDF, :NATUREMOVES)}"),
    PBFieldNote.new(16,"Camouflage <icon=fieldChange> <icon=field#{pbGetTypeNameFile(PBTypes::FIRE)}> "),
    PBFieldNote.new(16,"Force Cachée <icon=fieldChange> <icon=fieldBurn#{getSuffixFile()}> "),
    PBFieldNote.new(16,"Active <c=orange>Graine Tellurique</c> . . .","Augmente la Défense et applique Carapiège."),
  #Factory Field
    PBFieldNote.new(17,"<c=orange>\"#{FIELDEFFECTS.dig(PBFields::FACTORYF, :INTROMESSAGE)}\"</c> "),
    PBFieldNote.new(17,"Attaques <icon=Field#{pbGetTypeNameFile(PBTypes::ELECTRIC)}> <icon=fieldUp> <c=green>x1.2</c> "),
    PBFieldNote.new(17,"Boost de Motorisé <icon=fieldUp> <c=green>x2</c> "),
    PBFieldNote.new(17,"Boost de Télécharge <icon=fieldUp> <c=green>x2</c> "),
    PBFieldNote.new(17,"Technicien s'applique jusqu'à <c=green>80</c> ","...de Puissance."),
    PBFieldNote.new(17,"Certaines attaques <icon=fieldUp> <c=green>x1.5</c> . . . ",feToStringName(PBFields::FACTORYF, :MOVEDAMAGEBOOST, 1.5)),
    PBFieldNote.new(17,"Certaines attaques <icon=fieldUp> <c=green>x2</c> . . . ",feToStringName(PBFields::FACTORYF, :MOVEDAMAGEBOOST, 2.0)),
    PBFieldNote.new(17,"Effet de certaines capacités <icon=fieldUp> . . .","Allègement, Mur de Fer, Strido-Son, Chgt Vitesse"),
    PBFieldNote.new(17,"Vol Magnétik dure <c=green>8</c> tours"),
    PBFieldNote.new(17,"Devient <c=orange>Terrain Déchargé</c> si . . .","...si #{feToStringName(PBFields::FACTORYF, :FIELDCHANGE, PBFields::SHORTCIRCUITF)} est utilisé. Coup d'Jus fait alterner le terrain entre Terraindustriel et Terrain Déchargé pour chaque cible en Combat Double."),
    PBFieldNote.new(17,"Engrenage <icon=fieldUp> <c=green>x2</c> . . .","...et augmente de 2 crans l'Att/Att.Spé. des cibles et du lanceur."),
    PBFieldNote.new(17,"Boost de Peau Électrique <icon=fieldChange> <c=green>x1.5</c> "),
    PBFieldNote.new(17,"Boost d'Expert Acier <icon=fieldChange> <c=green>x2</c> "),
    PBFieldNote.new(17,"Force-Nature <icon=fieldChange> #{feToStringName(PBFields::FACTORYF, :NATUREMOVES)}"),
    PBFieldNote.new(17,"Camouflage <icon=fieldChange> <icon=field#{pbGetTypeNameFile(PBTypes::STEEL)}> "),
    PBFieldNote.new(17,"Force Cachée <icon=fieldChange> <c=red>réduit</c> l'Attaque"),
    PBFieldNote.new(17,"Active <c=orange>Graine Synthétique</c> . . .","Augmente l'Att.Spé. et applique Affilage."),
  #Short-Circuit Field
    PBFieldNote.new(18,"<c=orange>\"#{FIELDEFFECTS.dig(PBFields::SHORTCIRCUITF, :INTROMESSAGE)}\"</c> "),
    PBFieldNote.new(18,"Chances de Statik <icon=fieldUp> <c=green>x2</c> "),
    PBFieldNote.new(18,"Absorb Volt <c=green>restaure</c> lentement les PV "),
    PBFieldNote.new(18,"<c=green>Active</c> Plus et Minus"),
    PBFieldNote.new(18,"Attaques <icon=Field#{pbGetTypeNameFile(PBTypes::ELECTRIC)}> <icon=fieldChange> dégâts modifiés", "Jets de dégâts entre x0.5 et x2 suivant un motif spécifique."),
    PBFieldNote.new(18,"Certaines attaques <icon=fieldUp> <c=green>x1.3</c> . . . ",feToStringName(PBFields::SHORTCIRCUITF, :MOVEDAMAGEBOOST, 1.3)),
    PBFieldNote.new(18,"Certaines attaques <icon=fieldUp> <c=green>x1.5</c> . . . ",feToStringName(PBFields::SHORTCIRCUITF, :MOVEDAMAGEBOOST, 1.5)),
    PBFieldNote.new(18,"Certaines attaques <icon=fieldDown> <c=red>x0.5</c> . . . ",feToStringName(PBFields::SHORTCIRCUITF, :MOVEDAMAGEBOOST, 0.5)),
    PBFieldNote.new(18,"Certaines attaques <icon=fieldPlus> <icon=field#{pbGetTypeNameFile(PBTypes::ELECTRIC)}> . . .",feToStringName(PBFields::SHORTCIRCUITF, :MOVETYPEMOD, PBTypes::ELECTRIC)),
    PBFieldNote.new(18,"Devient <c=orange>Terraindustriel</c> si . . .","...si #{feToStringName(PBFields::SHORTCIRCUITF, :FIELDCHANGE, PBFields::FACTORYF)} est utilisé. Coup d'Jus fait alterner le terrain entre Terraindustriel et Terrain Déchargé pour chaque cible en Combat Double."),
    PBFieldNote.new(18,"Effet de certaines capacités <icon=fieldUp> . . .","Flash, Strido-Son"),
    PBFieldNote.new(18,"Précision d'Élécanon<icon=fieldChange> <c=green>80</c> "),
    PBFieldNote.new(18,"Vol Magnétik dure for <c=green>8</c> tours"),
    PBFieldNote.new(18,"<c=green>Active</c> Surf Caudal"),
    PBFieldNote.new(18,"Boost de Peau Électrique<icon=fieldChange> <c=green>x2</c> "),
    PBFieldNote.new(18,"Expert Acier <icon=fieldPlus> <icon=field#{pbGetTypeNameFile(PBTypes::ELECTRIC)}> "),
    PBFieldNote.new(18,"Force-Nature <icon=fieldChange> #{feToStringName(PBFields::SHORTCIRCUITF, :NATUREMOVES)}"),
    PBFieldNote.new(18,"Camouflage <icon=fieldChange> <icon=field#{pbGetTypeNameFile(PBTypes::ELECTRIC)}> "),
    PBFieldNote.new(18,"Force Cachée <icon=fieldChange> <icon=fieldParalyze> "),
    PBFieldNote.new(18,"Active <c=orange>Graine Synthétique</c> . . .","Augmente la Déf.Spé. et applique Vol Magnétik."),
  #Wasteland
    PBFieldNote.new(19,"<c=orange>\"#{FIELDEFFECTS.dig(PBFields::WASTELAND, :INTROMESSAGE)}\"</c> "),
    PBFieldNote.new(19,"Les pièges sont <c=orange>absorbés</c> . . .","Les pièges absorbés réapparaissent à la fin du tour, en déclenchant un effet spécial sur le terrain: \nPiège de Roc inflige le double des dégâts normaux aux Pokémon. \nPicots inflige 33% PV Max aux Pokémon au sol. \nPics Toxik inflige 12.5% PV Max aux Pokémon non Poison/Acier au sol, et empoisonne. \nToile Gluante fait baisser la Vitesse de deux crans."),
    PBFieldNote.new(19,"Certaines attaques <icon=fieldUp> <c=green>x1.2</c> . . . ",feToStringName(PBFields::WASTELAND, :MOVEDAMAGEBOOST, 1.2)),
    PBFieldNote.new(19,"Certaines attaques <icon=fieldUp> <c=green>x1.5</c> . . . ",feToStringName(PBFields::WASTELAND, :MOVEDAMAGEBOOST, 1.5)),
    PBFieldNote.new(19,"Certaines attaques <icon=fieldDown> <c=red>x0.25</c> . . . ",feToStringName(PBFields::WASTELAND, :MOVEDAMAGEBOOST, 0.25)),
    PBFieldNote.new(19,"Certaines attaques <icon=fieldPlus> <icon=Field#{pbGetTypeNameFile(PBTypes::POISON)}> . . .",feToStringName(PBFields::WASTELAND, :MOVETYPEMOD, PBTypes::POISON)),
    PBFieldNote.new(19,"Certaines attaques <icon=fieldPlus> statut . . .","Déluge Causti-Toxique, Détricanon, Octazooka, Détritus, Bomb-Beurk, Cradovague infligent un statut aléatoire sauf si la cible est de type Poison ou Acier, ou possède l'un de ces talents: Vaccin, Soin Poison, Rage Poison"),
    PBFieldNote.new(19,"Chances de certains talents <icon=fieldUp> <c=green>x2</c> ","Pose Spore, Point Poison, Puanteur"),
    PBFieldNote.new(19,"Dégâts de Suintement <icon=fieldUp> <c=green>x2</c> "),
    PBFieldNote.new(19,"<c=green>Active</c> certains talents . . .", "Soin Poison, Rage Poison, Cruauté"),
    PBFieldNote.new(19,"Effet de Poisseux <icon=fieldPlus> <icon=FieldPoisonStatus#{getSuffixFile()}> "),
    PBFieldNote.new(19,"<c=green>Active</c> Piège de Venin et Choc Venin"),
    PBFieldNote.new(19,"Relâche <icon=fieldUp> <c=green>x2</c> "),
    PBFieldNote.new(19,"Avale <icon=fieldUp> <c=green>x2</c> <icon=fieldPlus> . . .","guérit le statut à trois effets cumulés."),
    PBFieldNote.new(19,"Effet de Vampigraine <icon=fieldUp> <c=green>x2</c>"),
    PBFieldNote.new(19,"Attaques de Corrosion <icon=fieldPlus> <icon=fieldAllStat#{getSuffixFile()}> "),
    PBFieldNote.new(19,"Force-Nature <icon=fieldChange> #{feToStringName(PBFields::WASTELAND, :NATUREMOVES)}"),
    PBFieldNote.new(19,"Camouflage <icon=fieldChange> <icon=Field#{pbGetTypeNameFile(PBTypes::POISON)}> "),
    PBFieldNote.new(19,"Force Cachée <icon=fieldChange> <icon=fieldAllStat#{getSuffixFile()}> "),
    PBFieldNote.new(19,"Active <c=orange>Graine Tellurique</c> . . .","Augmente l'Attaque et l'Att.Spé. et place des Piège de Roc de chaque côté du terrain."),
  #Ashen Beach
    PBFieldNote.new(20,"<c=orange>\"#{FIELDEFFECTS.dig(PBFields::ASHENB, :INTROMESSAGE)}\"</c> "),
    PBFieldNote.new(20,"Certaines attaques <icon=fieldChange> <c=orange>cendres</c> . . .","Toutes les attaques Vol spéciales, Danse Flamme, Phytomixeur, Coupe-Vent, Ouragan, et Siphon soulèvent des cendres et baissent la Précision de tous les Pokémon."),
    PBFieldNote.new(20,"Pokémon <icon=Field#{pbGetTypeNameFile(PBTypes::FIGHTING)}> et Pokémon avec . . ."," ...avec Attention ne peuvent pas être confus."),
    PBFieldNote.new(20,"Précision/Esquive <c=red>ignorées</c> si . . .","...si l'un de ces talents est actif: Tempo Perso, Force Pure, Voile Sable, Impassible, à moins que la cible ait Tension."),
    PBFieldNote.new(20,"<c=green>Active</c> certains talents . . .", "Baigne Sable, Force Sable, Voile Sable"),
    PBFieldNote.new(20,"Mode Transe <c=green>toujours actif</c> "),
    PBFieldNote.new(20,"Effet de certaines capacités <icon=fieldUp> . . .","Plénitude, Télékinésie, Yoga, Jet de Sable"),
    PBFieldNote.new(20,"Tempêtesable dure <c=green>8</c> tours"),
    PBFieldNote.new(20,"Boost <icon=fieldPlus> <c=green>guérit</c> le statut"),
    PBFieldNote.new(20,"Effet de Puissance <icon=fieldUp> "),
    PBFieldNote.new(20,"Certaines attaques <icon=fieldUp> <c=green>x2</c> . . . ",feToStringName(PBFields::ASHENB, :MOVEDAMAGEBOOST, 2.0)),
    PBFieldNote.new(20,"Certaines attaques <icon=fieldUp> <c=green>x1.5</c> . . . ",feToStringName(PBFields::ASHENB, :MOVEDAMAGEBOOST, 1.5)),
    PBFieldNote.new(20,"Certaines attaques <icon=fieldUp> <c=green>x1.3</c> . . . ",feToStringName(PBFields::ASHENB, :MOVEDAMAGEBOOST, 1.3)),
    PBFieldNote.new(20,"Psyko <icon=fieldUp> <c=green>x1.2</c> "),
    PBFieldNote.new(20,"Force <icon=fieldChange> dégâts <icon=Field#{pbGetTypeNameFile(PBTypes::FIGHTING)}>/<icon=Field#{pbGetTypeNameFile(PBTypes::PSYCHIC)}> "),
    PBFieldNote.new(20,"Tourbi-Sable <icon=fieldPlus> <c=green>baisse</c> la Précision"),
    PBFieldNote.new(20,"Sable Humide <icon=fieldPlus> <c=green>augmente</c> la Déf.Spé."),
    PBFieldNote.new(20,"Précision d'Exploforce <icon=fieldChange> <c=green>90</c> "),
    PBFieldNote.new(20,"Soin d'Amass'Sable <icon=fieldChange> <c=green>75 %</c> PV"),
    PBFieldNote.new(20,"Soin du Grelot Coque <icon=fieldChange> <c=green>25 %</c> dégâts"),
    PBFieldNote.new(20,"Force-Nature <icon=fieldChange> Yoga"),
    PBFieldNote.new(20,"Camouflage <icon=fieldChange> <icon=Field#{pbGetTypeNameFile(PBTypes::GROUND)}> "),
    PBFieldNote.new(20,"Force Cachée <icon=fieldChange> <c=red>réduit</c> Précision"),
    PBFieldNote.new(20,"Active <c=orange>Graine Tellurique</c> . . .","Applique Puissance."),
  #Water Surface
    PBFieldNote.new(21,"<c=orange>\"#{FIELDEFFECTS.dig(PBFields::WATERS, :INTROMESSAGE)}\"</c> "),
    PBFieldNote.new(21,"Vitesse <icon=fieldDown> <c=red>x0.75</c> sauf <icon=Field#{pbGetTypeNameFile(PBTypes::WATER)}> ou . . .", "...sauf si le Pokémon est de type Eau, en l'air, ou que les talents Surf Caudal ou Glissade sont actifs."),
    PBFieldNote.new(21,"<c=red>Empêche</c> les attaques <icon=Field#{pbGetTypeNameFile(PBTypes::GROUND)}> "),
    PBFieldNote.new(21,"Les Picots/Pics Toxiks sont <c=red>détruits</c> "),
    PBFieldNote.new(21,"Plongée dure 1 tour"),
    PBFieldNote.new(21,"Ignifu-Voile <icon=fieldPlus> <c=green>guérit</c> le statut"),
    PBFieldNote.new(21,"<c=green>Active</c> certains talents . . .","Hydratation, Banc, Surf Caudal, Glissade, Torrent, et Sable Humide chaque tour."),
    PBFieldNote.new(21,"Trempette <icon=fieldPlus> <c=green>baisse</c> la Précision"),
    PBFieldNote.new(21,"Anneau Hydro rend <icon=fieldChange> <c=green>1/8 PV</c> "),
    PBFieldNote.new(21,"Certains talents <c=green>rendent des PV</c> . . .","Peau Sèche, Absorb Eau"),
    PBFieldNote.new(21,"Amass'Sable <c=green>active</c> Sable Humide"),
    PBFieldNote.new(21,"Dégâts de Siphon <icon=fieldChange> <c=green>1/6 PV</c> "),
    PBFieldNote.new(21,"Siphon <icon=fieldPlus> rend confus"),
    PBFieldNote.new(21,"Attaques <icon=Field#{pbGetTypeNameFile(PBTypes::WATER)}> <icon=fieldUp> <c=green>x1.5</c> "),
    PBFieldNote.new(21,"Attaques <icon=Field#{pbGetTypeNameFile(PBTypes::ELECTRIC)}> <icon=fieldUp> <c=green>x1.5</c> si . . .","...si la cible est au sol."),   
    PBFieldNote.new(21,"Attaques <icon=Field#{pbGetTypeNameFile(PBTypes::FIRE)}> <icon=fieldDown> <c=red>x0.5</c> si . . .","...si la cible est au sol."),
    PBFieldNote.new(21,"Certaines attaques <icon=fieldUp> <c=green>x1.5</c> . . . ",feToStringName(PBFields::WATERS, :MOVEDAMAGEBOOST, 1.5)),
    PBFieldNote.new(21,"Devient <c=orange>Sous l'Eau</c> si . . .","...si #{feToStringName(PBFields::WATERS, :FIELDCHANGE, PBFields::UNDERWATER)} est utilisé."),
    PBFieldNote.new(21,"Devient <c=orange>Terrain Glacé</c> si . . .","...si #{feToStringName(PBFields::WATERS, :FIELDCHANGE, PBFields::ICYF)} est utilisé."),
    PBFieldNote.new(21,"Devient <c=orange>Eau Polluée</c> si . . .","...si Déluge Causti-Toxique est utilisé, ou Cradovague est utilisé deux fois."),
    PBFieldNote.new(21,"Force-Nature <icon=fieldChange> #{feToStringName(PBFields::WATERS, :NATUREMOVES)}"),
    PBFieldNote.new(21,"Camouflage <icon=fieldChange> <icon=Field#{pbGetTypeNameFile(PBTypes::WATER)}> "),
    PBFieldNote.new(21,"Force Cachée <icon=fieldChange> <c=red>réduit</c> Vitesse"),
    PBFieldNote.new(21,"Active <c=orange>Graine Élémentaire</c> . . .","Augmente la Déf.Spé. et applique Anneau Hydro."),
  #Underwater
    PBFieldNote.new(22,"<c=orange>\"#{FIELDEFFECTS.dig(PBFields::UNDERWATER, :INTROMESSAGE)}\"</c> "),
    PBFieldNote.new(22,"Vitesse <icon=fieldDown> <c=red>x0.5</c> sauf <icon=Field#{pbGetTypeNameFile(PBTypes::WATER)}> ou . . .", "...sauf si le Pokémon est de type Eau ou possède Glissade."),
    PBFieldNote.new(22,"<c=red>Empêche</c> les attaques <icon=field#{pbGetTypeNameFile(PBTypes::FIRE)}> "),
    PBFieldNote.new(22,"<c=red>Empêche</c> la génération de Terrains"),
    PBFieldNote.new(22,"Tous les climats sont <c=red>annulés</c> "),
    PBFieldNote.new(22,"Attaques <icon=Field#{pbGetTypeNameFile(PBTypes::WATER)}> <icon=fieldChange> x1 vs <icon=Field#{pbGetTypeNameFile(PBTypes::WATER)}> "),
    PBFieldNote.new(22,"Dégâts physiques <icon=fieldDown> <c=red>x0.5</c> sauf . . .", "...sauf si l'attaque est de type Eau ou que le lanceur a Expert Acier."),
    PBFieldNote.new(22,"<c=orange>Dégâts</c> de fin de tour <icon=Field#{pbGetTypeNameFile(PBTypes::WATER)}> si . . .", "...si le Pokémon est faible à l'Eau."),
    PBFieldNote.new(22,"<c=green>Immunité</c> aux <c=orange>dégâts de terrain</c> si . . .","...si Garde Magik ou Glissade est actif."),
    PBFieldNote.new(22,"<c=orange>Dégâts de terrain</c> <icon=fieldRedUp> si . . .","...si Corps Ardent ou Armumagma est actif."),
    PBFieldNote.new(22,"Plongée dure 1 tour"),
    PBFieldNote.new(22,"Ignifu-Voile <icon=fieldPlus> <c=green>guérit</c> le statut"),
    PBFieldNote.new(22,"<c=green>Active</c> certains talents . . .","Hydratation, Banc, Surf Caudal, Glissade, Torrent, et Sable Humide chaque tour."),
    PBFieldNote.new(22,"Soin d'Anneau Hydro <icon=fieldChange> <c=green>1/8 PV</c> "),
    PBFieldNote.new(22,"Certains talents <c=green>rendent des PV</c> . . .","Peau Sèche, Absorb Eau"),
    PBFieldNote.new(22,"Dégâts de Siphon <icon=fieldChange> <c=green>1/6 PV</c> "),
    PBFieldNote.new(22,"Siphon <icon=fieldPlus> rend confus"),
    PBFieldNote.new(22,"Attaques <icon=Field#{pbGetTypeNameFile(PBTypes::GROUND)}> <icon=fieldPlus> dégâts <icon=Field#{pbGetTypeNameFile(PBTypes::WATER)}> "),
    PBFieldNote.new(22,"Attaques <icon=Field#{pbGetTypeNameFile(PBTypes::WATER)}> <icon=fieldUp> <c=green>x1.5</c> "),
    PBFieldNote.new(22,"Attaques <icon=Field#{pbGetTypeNameFile(PBTypes::ELECTRIC)}> <icon=fieldUp> <c=green>x2</c> "),
    PBFieldNote.new(22,"Attaques <icon=Field#{pbGetTypeNameFile(PBTypes::ELECTRIC)}> <c=green>ne ratent jamais</c> "),
    PBFieldNote.new(22,"Puissance de Vibraqua <icon=fieldUp> x1.5"),
    PBFieldNote.new(22,"Puissance d'Ancrage <icon=fieldUp> x2"),
    PBFieldNote.new(22,"Devient <c=orange>Surface de l'Eau</c> si . . .","...si #{feToStringName(PBFields::UNDERWATER, :FIELDCHANGE, PBFields::WATERS)} est utilisé."),
    PBFieldNote.new(22,"Devient <c=orange>Eau Polluée</c> si . . .","... Déluge Causti-toxique est utilisé, ou si Cradovague est utilisé deux fois. Met K.O. tous les Pokémon de types autres que Poison et Acier."),
    PBFieldNote.new(22,"Force-Nature <icon=fieldChange> #{feToStringName(PBFields::UNDERWATER, :NATUREMOVES)}"),
    PBFieldNote.new(22,"Camouflage <icon=fieldChange> <icon=Field#{pbGetTypeNameFile(PBTypes::WATER)}> "),
    PBFieldNote.new(22,"Force Cachée <icon=fieldChange> <c=red>réduit</c> l'Attaque"),
    PBFieldNote.new(22,"Active <c=orange>Graine Élémentaire</c> . . .","Augmente la Vitesse et applique Détrempage."),
  #Cave
    PBFieldNote.new(23,"<c=orange>\"#{FIELDEFFECTS.dig(PBFields::CAVE, :INTROMESSAGE)}\"</c> "),
    PBFieldNote.new(23,"Attaques <icon=Field#{pbGetTypeNameFile(PBTypes::GROUND)}> touchent <icon=Field#{pbGetTypeNameFile(PBTypes::FLYING)}> ","... ou les Pokémon ayant Lévitation."),
    PBFieldNote.new(23,"Tous les Pokémon <icon=fieldChange> <icon=fieldfaint#{getSuffixFile()}> si . . .", "...si #{feToStringName(PBFields::CAVE, :FIELDCHANGE, PBFields::CAVE)} est utilisé deux fois. Les Pokémon avec Fermeté ou sous Ténacité tombent à 1 PV. Les Pokémon avec Armurbaston ou Coque Armure perdent 50% PV. Les Pokémon avec Prisme-Armure ou Solide Roc perdent 33% PV. Les Pokémon utilisant une capacité de protection comme Abri, ou possédant Pare-Balles ou Tête de Roc sont immunisés aux dégâts."),
    PBFieldNote.new(23,"Vol et Rebond durent 1 tour"),
    PBFieldNote.new(23,"<c=red>Empêche</c> Chute Libre"),
    PBFieldNote.new(23,"Dégâts de Piège de Roc <icon=fieldUp> <c=green>x2</c> "),
    PBFieldNote.new(23,"Attaques <icon=Field#{pbGetTypeNameFile(PBTypes::ROCK)}> <icon=fieldUp> <c=green>x1.5</c> "),
    PBFieldNote.new(23,"Attaques <icon=Field#{pbGetTypeNameFile(PBTypes::FLYING)}> <icon=fieldDown> <c=red>x0.5</c> si . . .","...pas de contact."),
    PBFieldNote.new(23,"Attaques sonores <icon=fieldUp> <c=green>x1.5</c> "),
    PBFieldNote.new(23,"Tomberoche <icon=fieldUp> <c=green>x1.5</c> "),
    PBFieldNote.new(23,"Devient <c=orange>Caverne de Cristaux</c> si . . .","...si #{feToStringName(PBFields::CAVE, :FIELDCHANGE, PBFields::CRYSTALC)} est utilisé."),
    PBFieldNote.new(23,"Force-Nature <icon=fieldChange> #{feToStringName(PBFields::CAVE, :NATUREMOVES)}"),
    PBFieldNote.new(23,"Camouflage <icon=fieldChange> <icon=Field#{pbGetTypeNameFile(PBTypes::ROCK)}> "),
    PBFieldNote.new(23,"Force Cachée <icon=fieldChange> Apeure"),
    PBFieldNote.new(23,"Active <c=orange>Graine Tellurique</c> . . .","Augmente la Défense de deux crans et inflige les dégâts de Piège de Roc."),
  #Glitch Field
    PBFieldNote.new(24,"<c=orange>\"#{FIELDEFFECTS.dig(PBFields::GLITCHF, :INTROMESSAGE)}\"</c> "),
    PBFieldNote.new(24,"Certains types <icon=fieldChange> physiques . . .","Normal, Combat, Poison, Sol, Vol, Insecte, Roche, Spectre."),
    PBFieldNote.new(24,"Certains types <icon=fieldChange> spéciaux . . .","Feu, Eau, Plante, Électrik, Glace, Psy, Dragon."),
    PBFieldNote.new(24,"Dégâts spéciaux <c=orange>calculés</c> sur . . .","Les dégâts des attaques spéciales sont calculés en se basant sur la stat la plus haute entre Att.Spé. et Déf.Spé., pour l'attaquant et le défenseur."),
    PBFieldNote.new(24,"Attaques <icon=Field#{pbGetTypeNameFile(PBTypes::DARK)}>, <icon=field#{pbGetTypeNameFile(PBTypes::STEEL)}>, <icon=Field#{pbGetTypeNameFile(PBTypes::FAIRY)}> <icon=fieldChange> <icon=Field#{pbGetTypeNameFile(PBTypes::NORMAL)}> "),
    PBFieldNote.new(24,"La table des types est <c=orange>altérée</c> . . .","Dragon inflige toujours des dégâts neutres. Insecte et Poison sont super efficaces l'un sur l'autre. Glace est neutre sur Feu. Psy est immunisé à Spectre."),
    PBFieldNote.new(24,"Taux de coups critiques <icon=fieldUp> si . . .","Le taux de coups critiques est augmenté d'un cran si l'attaquant est plus rapide que sa cible."),
    PBFieldNote.new(24,"Frénésie <c=red>bloque</c> le lanceur"),
    PBFieldNote.new(24,"Attaques à recharge <icon=fieldChange>. . .","...le tour de recharge est annulé si l'attaque met K.O. la cible."),
    PBFieldNote.new(24,"Attaques <icon=Field#{pbGetTypeNameFile(PBTypes::PSYCHIC)}> <icon=fieldUp> <c=green>x1.2</c> "),
    PBFieldNote.new(24,"Précision de Blizzard <icon=fieldChange> <c=green>90</c> "),
    PBFieldNote.new(24,"Métronome <c=green>choisit</c> attaques . . .","...ne choisit que des attaques de 70 de puissance ou plus."),
    PBFieldNote.new(24,"Destruction et Explosion . . .","...divisent la Défense de la cible par deux avant d'appliquer les dégâts."),
    PBFieldNote.new(24,"Système Alpha<icon=fieldChange> <icon=Field#{pbGetTypeNameFile(PBTypes::QMARKS)}> "),
    PBFieldNote.new(24,"<c=green>Créé</c> si . . .", "Si Conversion et Conversion 2 sont utilisées l'une après l'autre, le terrain est généré pendant 5 tours."),
    PBFieldNote.new(24,"Force-Nature <icon=fieldChange> #{feToStringName(PBFields::GLITCHF, :NATUREMOVES)}"),
    PBFieldNote.new(24,"Camouflage <icon=fieldChange> <icon=Field#{pbGetTypeNameFile(PBTypes::QMARKS)}> "),
    PBFieldNote.new(24,"Force Cachée <icon=fieldChange> <c=red>réduit</c> Vitesse"),
    PBFieldNote.new(24,"Active <c=orange>Graine Synthétique</c> . . .","Augmente la Défense et brouille le type."),
  #Crystal Cavern
    PBFieldNote.new(25,"<c=orange>\"#{FIELDEFFECTS.dig(PBFields::CRYSTALC, :INTROMESSAGE)}\"</c> "),
    PBFieldNote.new(25,"Attaques <icon=Field#{pbGetTypeNameFile(PBTypes::ROCK)}> <icon=fieldUp> <c=green>x1.5</c> "),
    PBFieldNote.new(25,"Certaines attaques <icon=fieldUp> <c=green>x1.5</c> ",feToStringName(PBFields::CRYSTALC, :MOVEDAMAGEBOOST, 1.5)),
    PBFieldNote.new(25,"Certaines attaques <icon=fieldPlus> . . .","Les attaques Roche, ainsi que Jugement, Coup Varia-Type, Escalade et Force gagnent un type additionnel parmi Plante, Feu, Eau et Psy suivant un ordre invariable."),
    PBFieldNote.new(25,"Attaques <icon=Field#{pbGetTypeNameFile(PBTypes::DRAGON)}> <icon=fieldUp> <c=green>x1.5</c> "),
    PBFieldNote.new(25,"Certaines attaques <icon=fieldUp> <c=green>x1.3</c> ",feToStringName(PBFields::CRYSTALC, :MOVEDAMAGEBOOST, 1.3)),
    PBFieldNote.new(25,"Devient <c=orange>Caverne Obscure</c> si . . .","...si #{feToStringName(PBFields::CRYSTALC, :FIELDCHANGE, PBFields::DARKCRYSTALC)} est utilisé."),
    PBFieldNote.new(25,"Devient une <c=orange>Caverne</c> si . . .","...si #{feToStringName(PBFields::CRYSTALC, :FIELDCHANGE, PBFields::CAVE)} est utilisé."),
    PBFieldNote.new(25,"Poliroche <icon=fieldPlus> <c=green>augmente</c> Att/Att.Spé."),
    PBFieldNote.new(25,"Piège de Roc <icon=fieldPlus> type aléatoire","Piège de Roc inflige aléatoirement des dégâts de type Plante, Feu, Eau ou Psy."),
    PBFieldNote.new(25,"<c=green>Autorise</c> Voile Aurore"),
    PBFieldNote.new(25,"Prisme-Armure <c=green>réduit les dégâts</c> x0.75"),
    PBFieldNote.new(25,"Force-Nature <icon=fieldChange> #{feToStringName(PBFields::CRYSTALC, :NATUREMOVES)}"),
    PBFieldNote.new(25,"Camouflage <icon=fieldChange> type aléatoire . . .","Camouflage peut choisir le type Plante, Feu, Eau ou Psy."),
    PBFieldNote.new(25,"Force Cachée <icon=fieldChange> statut aléatoire . . .","Force Cachée applique un statut aléatoire parmi Brûlure, Gel, Sommeil et Confusion."),
    PBFieldNote.new(25,"Active <c=orange>Graine Magique</c> . . .","Augmente l'Att.Spé. et applique Reflet Magik."),
  #Murkwater Surface
    PBFieldNote.new(26,"<c=orange>\"#{FIELDEFFECTS.dig(PBFields::MURKWATERS, :INTROMESSAGE)}\"</c> "),
    PBFieldNote.new(26,"Vitesse <icon=fieldDown> <c=red>x0.75</c> sauf <icon=Field#{pbGetTypeNameFile(PBTypes::WATER)}> ou . . .", "...sauf si le Pokémon est de type Eau, en l'air, ou que le talent Glissade ou Surf Caudal es actif."),
    PBFieldNote.new(26,"<c=orange>Dégâts</c> <icon=Field#{pbGetTypeNameFile(PBTypes::POISON)}> en fin de tour si . . .","...si au sol, sauf pour les Pokémon Poison et Acier."),
    PBFieldNote.new(26,"<c=green>Immunité</c> aux <c=orange>dégâts</c> du terrain si . . .","...si l'un de ces talent est actif: Vaccin, Garde Magik, Garde Mystik, Soin Poison, Rage Poison"),
    PBFieldNote.new(26,"<c=orange>Dégâts</c> du terrain <icon=fieldRedUp> si . . .","...si le Pokémon est sous l'eau (x4) ou possède l'un de ces talents (x2): Peau Sèche, Corps Ardent, Armumagma, Absorb Eau"),
    PBFieldNote.new(26,"Peau Sèche <c=green>rend des PV</c> si . . .","...si le Pokémon est au sol et de type Poison."),
    PBFieldNote.new(26,"Absorb Eau <c=green>rend des PV</c> si . . .","...si le Pokémon est au sol et de type Poison."),
    PBFieldNote.new(26,"<c=green>Active</c> certains talents si . . .","...si au sol, active Cruauté, Soin Poison, Banc, Surf Caudal, Glissade, Rage Poison et Sable Humide chaque tour."),
    PBFieldNote.new(26,"<c=red>Empêche</c> les attaques <icon=Field#{pbGetTypeNameFile(PBTypes::GROUND)}> "),
    PBFieldNote.new(26,"Picots/Pics Toxik <c=red>détruits</c> "),
    PBFieldNote.new(26,"Amass'Sable <c=green>active</c> Sable Humide"),
    PBFieldNote.new(26,"Attaques <icon=Field#{pbGetTypeNameFile(PBTypes::WATER)}> <icon=fieldUp> <c=green>x1.5</c> "),
    PBFieldNote.new(26,"Attaques <icon=Field#{pbGetTypeNameFile(PBTypes::WATER)}> <icon=fieldPlus> <icon=Field#{pbGetTypeNameFile(PBTypes::POISON)}> "),
    PBFieldNote.new(26,"Attaques <icon=Field#{pbGetTypeNameFile(PBTypes::POISON)}> <icon=fieldUp> <c=green>x1.5</c> "),
    PBFieldNote.new(26,"Attaques <icon=Field#{pbGetTypeNameFile(PBTypes::ELECTRIC)}> <icon=fieldUp> <c=green>x1.3</c> si . . .","...si la cible est au sol."),
    PBFieldNote.new(26,"Cradovague <icon=fieldPlus> <icon=Field#{pbGetTypeNameFile(PBTypes::WATER)}> "),
    PBFieldNote.new(26,"Certaines attaques <icon=fieldChange> <icon=Field#{pbGetTypeNameFile(PBTypes::WATER)}> / <icon=Field#{pbGetTypeNameFile(PBTypes::POISON)}> ","Coud'Boue, Tir de Boue, Boue-Bombe, Myria-Flèches"),
    PBFieldNote.new(26,"Certaines attaques <icon=fieldPlus> <icon=Field#{pbGetTypeNameFile(PBTypes::POISON)}> . . .","Anti-Air"),
    PBFieldNote.new(26,"Certaines attaques <icon=fieldUp> <c=green>x1.5</c> . . . ",feToStringName(PBFields::MURKWATERS, :MOVEDAMAGEBOOST, 1.5)),
    PBFieldNote.new(26,"Effet de Poisseux <icon=fieldUp> <c=green>x2</c> "),
    PBFieldNote.new(26,"Chances de Puanteur <icon=fieldUp> <c=green>x2</c> "),
    PBFieldNote.new(26,"Effet d'Acidarmure <icon=fieldUp> <c=green>x2</c> "),
    PBFieldNote.new(26,"<c=green>Active</c> Choc Venin"),
    PBFieldNote.new(26,"<c=green>Active</c> Piège de Venin"),
    PBFieldNote.new(26,"Suintement <icon=fieldUp> <c=green>x2</c> "),
    PBFieldNote.new(26,"Devient <c=orange>Surface de l'Eau</c> si . . .","...si #{feToStringName(PBFields::MURKWATERS, :FIELDCHANGE, PBFields::WATERS)} est utilisé."),
    PBFieldNote.new(26,"Devient <c=orange>Terrain Glacé</c> si . . .","...si #{feToStringName(PBFields::MURKWATERS, :FIELDCHANGE, PBFields::ICYF)} est utilisé."),
    PBFieldNote.new(26,"Force-Nature <icon=fieldChange> #{feToStringName(PBFields::MURKWATERS, :NATUREMOVES)}"),
    PBFieldNote.new(26,"Camouflage <icon=fieldChange> <icon=Field#{pbGetTypeNameFile(PBTypes::POISON)}> "),
    PBFieldNote.new(26,"Force Cachée <icon=fieldChange> <icon=FieldPoisonStatus#{getSuffixFile()}> "),
    PBFieldNote.new(26,"Active <c=orange>Graine Élémentaire</c> . . .","Augmente la Vitesse et applique Anneau Hydro, mais empoisonne."),
  #Mountain
    PBFieldNote.new(27,"<c=orange>\"Pourtant, que la montagne est belle...\"</c>"),
    PBFieldNote.new(27,"Vent Arrière dure <c=green>5</c> tours"),
    PBFieldNote.new(27,"Vent Arrière <icon=fieldPlus> Vent Mystérieux"),
    PBFieldNote.new(27,"Certaines attaques <icon=fieldUp> <c=green>x1.5</c> . . . ",feToStringName(PBFields::MOUNTAIN, :MOVEDAMAGEBOOST, 1.5)),
    PBFieldNote.new(27,"Certaines attaques <icon=fieldUp> <c=green>x1.5</c> si . . .","...si Vent Mystérieux est actif, améliore les attaques Vol spéciales, ainsi que Vent Féérique, Tornade, Vent Glace, Vent Mauvais, Coupe-Vent, Vent Argenté, Ouragan"),
    PBFieldNote.new(27,"Le soleil dure <c=green>8</c> tours"),
    PBFieldNote.new(27,"Fatal-Foudre <c=green>ne rate jamais</c> "),
    PBFieldNote.new(27,"Devient <c=orange>Montagne Enneigée</c> si . . .","...si #{feToStringName(PBFields::MOUNTAIN, :FIELDCHANGE, PBFields::SNOWYM)} est utilisé, ou s'il grêle depuis 3 tours."),
    PBFieldNote.new(27,"Attaques <icon=Field#{pbGetTypeNameFile(PBTypes::FLYING)}> <icon=fieldUp> <c=green>x1.5</c> "),
    PBFieldNote.new(27,"Attaques <icon=Field#{pbGetTypeNameFile(PBTypes::ROCK)}> <icon=fieldUp> <c=green>x1.5</c> "),
    PBFieldNote.new(27,"Dégâts de Longue Portée <icon=fieldUp> <c=green>x1.5</c> "),
    PBFieldNote.new(27,"<c=green>Active</c> Ailes Bourrasque s'il vente"),
    PBFieldNote.new(27,"Boost de Peau Céleste <icon=fieldChange> <c=green>x1.5</c> "),
    PBFieldNote.new(27,"Force-Nature <icon=fieldChange> #{feToStringName(PBFields::MOUNTAIN, :NATUREMOVES)}"),
    PBFieldNote.new(27,"Camouflage <icon=fieldChange> <icon=Field#{pbGetTypeNameFile(PBTypes::ROCK)}> "),
    PBFieldNote.new(27,"Force Cachée <icon=fieldChange> apeure"),
    PBFieldNote.new(27,"Active <c=orange>Graine Tellurique</c> . . .","Augmente l'Attaque de deux crans, mais diminue la Précision."),
  #Snowy Mountain
    PBFieldNote.new(28,"<c=orange>\"L'hiver s'installe doucement . . .","...sur la montagne...\"</c> "),
    PBFieldNote.new(28,"Vent Arrière dure <c=green>5</c> tours"),
    PBFieldNote.new(28,"Vent Arrière <icon=fieldPlus> Vent Mystérieux"),
    PBFieldNote.new(28,"Attaques <icon=Field#{pbGetTypeNameFile(PBTypes::ROCK)}> <icon=fieldPlus> <icon=Field#{pbGetTypeNameFile(PBTypes::ICE)}> "),
    PBFieldNote.new(28,"Attaques <icon=Field#{pbGetTypeNameFile(PBTypes::ICE)}> <icon=fieldUp> <c=green>x1.5</c> "),
    PBFieldNote.new(28,"Attaques <icon=Field#{pbGetTypeNameFile(PBTypes::ROCK)}> <icon=fieldUp> <c=green>x1.5</c> "),
    PBFieldNote.new(28,"Attaques <icon=Field#{pbGetTypeNameFile(PBTypes::FLYING)}> <icon=fieldUp> <c=green>x1.5</c> "),
    PBFieldNote.new(28,"Attaques <icon=Field#{pbGetTypeNameFile(PBTypes::FIRE)}> <icon=fieldDown> <c=red>x0.5</c> "),
    PBFieldNote.new(28,"Déf. des Pokémon <icon=Field#{pbGetTypeNameFile(PBTypes::ICE)}> <icon=fieldUp> <c=green>x1.5</c> . . .", "...s'il grêle."),
    PBFieldNote.new(28,"Certaines attaques <icon=fieldUp> <c=green>x1.5</c> . . . ",feToStringName(PBFields::SNOWYM, :MOVEDAMAGEBOOST, 1.5)),
    PBFieldNote.new(28,"Certaines attaques <icon=fieldUp> <c=green>x1.5</c> si . . .","...si Vent Mystérieux est actif, améliore les attaques Vol spéciales, ainsi que Vent Féérique, Tornade, Vent Glace, Vent Mauvais, Coupe-Vent, Vent Argenté, Ouragan"),
    PBFieldNote.new(28,"Certaines attaques <icon=fieldDown> <c=red>x0.5</c> . . . ",feToStringName(PBFields::SNOWYM, :MOVEDAMAGEBOOST, 0.5)),
    PBFieldNote.new(28,"Zénith et Grêle durent <c=green>8</c> tours"),
    PBFieldNote.new(28,"Fatal-Foudre <c=green>ne rate jamais</c> "),
    PBFieldNote.new(28,"<c=green>Active</c> certains talents . . .","Corps Gel, Chasse-Neige, Rideau Neige"),
    PBFieldNote.new(28,"Boost de Peau Gelée <icon=fieldChange> <c=green>x1.5</c> "),
    PBFieldNote.new(28,"Devient une <c=orange>Montagne</c> si . . .", "...si #{feToStringName(PBFields::SNOWYM, :FIELDCHANGE, PBFields::MOUNTAIN)} est utilisé"),
    PBFieldNote.new(28,"<c=green>Active</c> Ailes Bourrasque s'il vente"),
    PBFieldNote.new(28,"<c=green>Autorise</c> Voile Aurore"),
    PBFieldNote.new(28,"Dégâts de Longue Portée <icon=fieldUp> <c=green>x1.5</c> "),
    PBFieldNote.new(28,"Boost de Peau Céleste <icon=fieldChange> <c=green>x1.5</c> "),
    PBFieldNote.new(28,"Force-Nature <icon=fieldChange> #{feToStringName(PBFields::SNOWYM, :NATUREMOVES)}"),
    PBFieldNote.new(28,"Camouflage <icon=fieldChange> <icon=Field#{pbGetTypeNameFile(PBTypes::ICE)}> "),
    PBFieldNote.new(28,"Force Cachée <icon=fieldChange> <icon=fieldFreeze#{getSuffixFile()}> "),
    PBFieldNote.new(28,"Active <c=orange>Graine Tellurique</c> . . .","Augmente l'Att.Spé. de deux crans, mais diminue la Précision."),
  #Holy Field
    PBFieldNote.new(29,"<c=orange>\"#{FIELDEFFECTS.dig(PBFields::HOLYF, :INTROMESSAGE)}\"</c> "),
    PBFieldNote.new(29,"La table des types est <c=orange>altérée</c> . . .","Normal est super efficace sur Spectre et Ténèbres."),
    PBFieldNote.new(29,"Attaques <icon=Field#{pbGetTypeNameFile(PBTypes::GHOST)}> <icon=fieldDown> <c=red>x0.5</c> "),
    PBFieldNote.new(29,"Attaques <icon=Field#{pbGetTypeNameFile(PBTypes::DARK)}> spéciales <icon=fieldDown> <c=red>x0.5</c> "),
    PBFieldNote.new(29,"Attaques <icon=Field#{pbGetTypeNameFile(PBTypes::FAIRY)}> spéciales <icon=fieldUp> <c=green>x1.5</c> "),
    PBFieldNote.new(29,"Certaines attaques <icon=fieldUp> <c=green>x1.5</c> . . . ",feToStringName(PBFields::HOLYF, :MOVEDAMAGEBOOST, 1.5)),
    PBFieldNote.new(29,"Certaines attaques <icon=fieldUp> <c=green>x1.3</c> . . . ",feToStringName(PBFields::HOLYF, :MOVEDAMAGEBOOST, 1.3)),
    PBFieldNote.new(29,"Attaques <icon=Field#{pbGetTypeNameFile(PBTypes::PSYCHIC)}> <icon=fieldUp> <c=green>x1.2</c> "),
    PBFieldNote.new(29,"Attaques <icon=Field#{pbGetTypeNameFile(PBTypes::DRAGON)}> <icon=fieldUp> <c=green>x1.2</c> "),
    PBFieldNote.new(29,"Attaques <icon=Field#{pbGetTypeNameFile(PBTypes::NORMAL)}> spéciales <icon=fieldUp> <c=green>x1.5</c> "),
    PBFieldNote.new(29,"Effet de Cœur Noble <icon=fieldUp> <c=green>x2</c> "),
    PBFieldNote.new(29,"Soin de Vœu <icon=fieldChange> <c=green>75 % PV</c> "),
    PBFieldNote.new(29,"<c=red>Empêche</c> Corps Maudit"),
    PBFieldNote.new(29,"Lève les Malédictions chaque tour"),
    PBFieldNote.new(29,"Les Pokémon alliés <c=green>esquivent</c>  . . ","...les attaques de leurs partenaires."),
    PBFieldNote.new(29,"Œil Miracle <icon=fieldPlus> <c=green>augmente</c> l'Att.Spé."),
    PBFieldNote.new(29,"Effet de Force Cosmik <icon=fieldUp> "),
    PBFieldNote.new(29,"Dégâts d'Ire de la Nature <icon=fieldChange> <c=green>75 % PV</c> "),
    PBFieldNote.new(29,"Système Alpha <icon=fieldChange> <icon=Field#{pbGetTypeNameFile(PBTypes::DARK)}> "),
    PBFieldNote.new(29,"<c=red>Détruit</c> par ces attaques . . .", feToStringName(PBFields::HOLYF, :FIELDCHANGE, 0)),
    PBFieldNote.new(29,"Force-Nature <icon=fieldChange> #{feToStringName(PBFields::HOLYF, :NATUREMOVES)}"),
    PBFieldNote.new(29,"Camouflage <icon=fieldChange> <icon=field#{PBTypes.getName(FIELDEFFECTS.dig(PBFields::HOLYF, :MIMICRY))}> "),
    PBFieldNote.new(29,"Force Cachée <icon=fieldChange> <c=red>réduit</c> l'Att.Spé."),
    PBFieldNote.new(29,"Active <c=orange>Graine Magique</c> . . .","Augmente l'Att.Spé. et applique Reflet Magik."),
  #Mirror Field
    PBFieldNote.new(30,"<c=orange>\"Miroir, mon beau miroir, . . .</c> ", "...À qui donneras-tu la victoire?\""),
    PBFieldNote.new(30,"Taux de coups critiques <icon=fieldUp> si . . .","Le taux de coups critiques est augmenté d'un cran pour chaque amélioration de la Précision/Esquive du lanceur, et chaque baisse de Précision/Esquive de la cible."),
    PBFieldNote.new(30,"Certaines attaques <icon=fieldChange> <c=orange>réfléchies</c> . . .","Les attaques spéciales monocibles sans contact touchent toujours une cible dont l'Esquive est augmentée."),
    PBFieldNote.new(30,"Certains <c=orange>reflets</c> <icon=fieldUp> <c=green>x2</c> . . .","Les attaques suivantes: Bulles d'O, Rayon Chargé, Canon Floral, Ultralaser, Laser Glace, Onde Originelle, Rayons Séléno-Explosifs, Rafale Psy, Lance-Soleil, et Triplattaque sont améliorées si elles touchent une cible dont l'Esquive est augmentée."),
    PBFieldNote.new(30,"Attaques physiques ratées <icon=fieldChange> . . .","Rater une attaque de contact physique fait perdre 25% de PV au lanceur, et fait baisser l'Esquive d'un cran si elle était augmentée."),
    PBFieldNote.new(30,"Certains talents <icon=fieldUp> Esquive . . .","Déguisement, Illusion, Reflet Magik, Voile Sable, Rideau Neige et Pieds Confus augmentent l'Esquive d'un cran."),
    PBFieldNote.new(30,"Certains objets <icon=fieldUp> Esquive . . .","Encens Doux et Poudreclaire augmentent l'Esquive d'un cran."),
    PBFieldNote.new(30,"Certaines attaques <icon=fieldUp> <c=green>x1.5</c> et . . .","...et ne ratent jamais: #{feToStringName(PBFields::MIRRORA, :MOVEDAMAGEBOOST, 1.5)}"),
    PBFieldNote.new(30,"Lumiattirance <icon=fieldPlus> <c=green>baisse</c> la Précision . . .","Lumiattirance fait baisser la Précision adverse d'un cran."),
    PBFieldNote.new(30,"Certains talents <icon=fieldUp> Précision . . .","Regard Vif et Œil Composé augmentent la Précision d'un cran, et appliquent Affilage."),
    PBFieldNote.new(30,"Certains objets <icon=fieldUp> Précision . . .","Loupe et Lentille Zoom augmentent la Précision d'un cran, et appliquent Affilage."),
    PBFieldNote.new(30,"Reflet Magik <icon=fieldPlus> Esquive <icon=fieldUp> . . .","...chaque fois qu'une capacité est renvoyée."),
    PBFieldNote.new(30,"Protection/Mur Lumière <icon=fieldChange> <c=green>8</c> tours"),
    PBFieldNote.new(30,"<c=green>Autorise</c> Voile Aurore"),
    PBFieldNote.new(30,"Protection/Mur Lumière <icon=fieldPlus> Esquive <icon=fieldUp> "),
    PBFieldNote.new(30,"Voile Miroir <icon=fieldPlus> <icon=fieldUp> . . .","Voile Miroir augmente l'Esquive, la Défense et la Défense Spéciale d'un cran."),
    PBFieldNote.new(30,"Mimique <icon=fieldPlus> <icon=fieldUp> . . .","Mimique augmente la Précision, l'Attaque et l'Attaque Spéciale d'un cran."),
    PBFieldNote.new(30,"Puissance de Miroi-Tir <icon=fieldUp> <c=green>x2</c> "),
    PBFieldNote.new(30,"Effet de Miroi-Tir <icon=fieldChange> <c=green>100 %</c> "),
    PBFieldNote.new(30,"Effet de certaines capacités <icon=fieldUp> . . .", "Reflet, Flash"),
    PBFieldNote.new(30,"<c=red>Détruit</c> par ces attaques . . .", "...#{feToStringName(PBFields::MIRRORA, :FIELDCHANGE, 0)}.\nLes bris de verre blessent tous les Pokémon actifs à hauteur de 50% de leurs PV Max, sauf les Pokémon qui se protègent par une capacité ou possédant Coque Armure ou Armurbaston."),
    PBFieldNote.new(30,"Force-Nature <icon=fieldChange> #{feToStringName(PBFields::MIRRORA, :NATUREMOVES)}"),
    PBFieldNote.new(30,"Camouflage <icon=fieldChange> <icon=field#{pbGetTypeNameFile(PBTypes::STEEL)}> "), #sisi jvous jure, chais pas pourquoi non plus
    PBFieldNote.new(30,"Force Cachée <icon=fieldChange> <c=red>réduit</c> l'Esquive"),
    PBFieldNote.new(30,"Active <c=orange>Graine Synthétique</c> . . .","Augmente l'Esquive d'un cran et applique Reflet Magik."),
  #Fairy Tale Field
    PBFieldNote.new(31,"<c=orange>\"#{FIELDEFFECTS.dig(PBFields::FAIRYTALEF, :INTROMESSAGE)}\"</c> "),
    PBFieldNote.new(31,"Attaques <icon=Field#{pbGetTypeNameFile(PBTypes::FAIRY)}> <icon=fieldUp> <c=green>x1.5</c> "),
    PBFieldNote.new(31,"Attaques <icon=field#{pbGetTypeNameFile(PBTypes::STEEL)}> <icon=fieldUp> <c=green>x1.5</c> "),
    PBFieldNote.new(31,"Attaques <icon=Field#{pbGetTypeNameFile(PBTypes::DRAGON)}> <icon=fieldUp> <c=green>x2</c> "),
    PBFieldNote.new(31,"Attaques <icon=field#{pbGetTypeNameFile(PBTypes::STEEL)}> <icon=fieldChange> <c=green>x2</c> vs <icon=fieldDragon> "),
    PBFieldNote.new(31,"Attaques <icon=Field#{pbGetTypeNameFile(PBTypes::FIRE)}> <icon=fieldUp> <icon=fieldplus> <icon=fieldDragon> "),
    PBFieldNote.new(31,"Certains talents <icon=fieldPlus> Défense <icon=fieldUp> . . .","Armurbaston, Osmose et Coque Armure augmentent la Défense d'un cran."),
    PBFieldNote.new(31,"Certains talents <icon=fieldPlus> Déf.Spé. <icon=fieldUp> . . .","Garde Magik, Reflet Magik et Osmose augmentent la Déf.Spé. d'un cran."),
    PBFieldNote.new(31,"Magicien <icon=fieldPlus> Att.Spé. <icon=fieldUp> "),
    PBFieldNote.new(31,"Aura Féérique <icon=fieldPlus> . . .","...effet d'Annule-Garde."),
    PBFieldNote.new(31,"<c=green>Active</c> Écaille Spéciale"),
    PBFieldNote.new(31,"Certaines attaques <icon=fieldChange> <icon=field#{pbGetTypeNameFile(PBTypes::STEEL)}> ","Coupe, Lame Sainte, Lame Ointe, Tranche"),
    PBFieldNote.new(31,"Déclic Tactique <icon=fieldChange> . . .","Les Pokémon possédant Déclic Tactique alternent augmentation et baisse d'Attaque et de Défense à chaque changement de forme."),
    PBFieldNote.new(31,"Certaines attaques <icon=fieldUp> <c=green>x1.5</c> . . . ",feToStringName(PBFields::FAIRYTALEF, :MOVEDAMAGEBOOST, 1.5)),
    PBFieldNote.new(31,"Vampibaiser <icon=fieldUp> <c=green>x2</c> "),
    PBFieldNote.new(31,"Certaines capcaités <icon=fieldPlus> . . .","Vigilance et Garde Florale augmentent d'un cran la Défense et la Défense Spéciale."),
    PBFieldNote.new(31,"Effet de Bouclier Royal <icon=fieldUp> . . .","...Bouclier Royal protège de toutes les attaques et baisse l'Attaque Spéciale de l'attaquant."),
    PBFieldNote.new(31,"Effet de certaines capacités <icon=fieldUp> . . .","Acidarmure, Râle Mâle, Danse-Lames"),
    PBFieldNote.new(31,"Effet de certaines capacités <icon=fieldPlus> . . .","Doux Baiser et Vampibaiser réveillent une cible endormie."),
    PBFieldNote.new(31,"Soin de Vœu <icon=fieldChange> <c=green> 75 % PV</c> "),
    PBFieldNote.new(31,"Effet de Vœu Soin <icon=fieldPlus> . . .","Vœu Soin augmente l'Attaque et l'Attaque Spéciale de la cible."),
    PBFieldNote.new(31,"Œil Miracle <c=green>augmente</c> l'Att.Spé."),
    PBFieldNote.new(31,"Maléfice Sylvain <icon=fieldPlus> . . .","...Maléfice Sylvain applique Malédiction."),
    PBFieldNote.new(31,"Soin de Soin Floral <icon=fieldChange> <c=green>100 %</c> "),
    PBFieldNote.new(31,"Dégâts de Prestance Royale <icon=fieldUp> <c=green>x1.5</c> "),
    PBFieldNote.new(31,"Animacœur <c=green>augmente</c> la Déf.Spé."),
    PBFieldNote.new(31,"Force-Nature <icon=fieldChange> #{feToStringName(PBFields::FAIRYTALEF, :NATUREMOVES)}"),
    PBFieldNote.new(31,"Camouflage <icon=fieldChange> <icon=Field#{pbGetTypeNameFile(PBTypes::FAIRY)}> "),
    PBFieldNote.new(31,"Force Cachée <icon=fieldChange> <icon=fieldSleep#{getSuffixFile()}> "),
    PBFieldNote.new(31,"Active <c=orange>Graine Magique</c> . . .","Applique Bouclier Royal."),
  #Dragon's Den
    PBFieldNote.new(32,"<c=orange>\"Qui trop combat le dragon...</c>","...devient dragon lui-même\"."),
    PBFieldNote.new(32,"Attaques <icon=FieldDragon> <icon=fieldUp> <c=green>x1.5</c> "),
    PBFieldNote.new(32,"Attaques <icon=field#{pbGetTypeNameFile(PBTypes::FIRE)}> <icon=fieldUp> <c=green>x1.5</c> "),
    PBFieldNote.new(32,"Attaques <icon=Field#{pbGetTypeNameFile(PBTypes::WATER)}> <icon=fieldDown> <c=red>x0.5</c> "),
    PBFieldNote.new(32,"Attaques <icon=Field#{pbGetTypeNameFile(PBTypes::ICE)}> <icon=fieldDown> <c=red>x0.5</c> "),
    PBFieldNote.new(32,"Défenses des Pokémon <icon=FieldDragon> <icon=fieldUp> <c=green>x1.3</c>"),
    PBFieldNote.new(32,"<c=green>Active</c> Écaille Spéciale"),
    PBFieldNote.new(32,"Effet de Multiécaille <icon=fieldPlus> . . . ","Multiécaille annule les faiblesses Dragon du Pokémon de façon permanente."),
    PBFieldNote.new(32,"Effet de Mue <icon=fieldPlus> . . . ","À l'activation, Mue soigne de 25% les PV, et augmente d'un cran la Vitesse et l'Att.Spé. tout en baissant d'un cran les défenses. \nS'active toujours."),
    PBFieldNote.new(32,"Certaines attaques <icon=fieldPlus> <icon=field#{pbGetTypeNameFile(PBTypes::FIRE)}> . . .","#{feToStringName(PBFields::DRAGONSD, :MOVETYPEMOD, PBTypes::FIRE)}"),
    PBFieldNote.new(32,"Certaines attaques <icon=fieldUp> <c=green>x2</c> . . . ",feToStringName(PBFields::DRAGONSD, :MOVEDAMAGEBOOST, 2.0)),
    PBFieldNote.new(32,"Certaines attaques <icon=fieldUp> <c=green>x1.5</c> . . . ",feToStringName(PBFields::DRAGONSD, :MOVEDAMAGEBOOST, 1.5)),
    PBFieldNote.new(32,"Dégâts de Vortex Magma <icon=fieldChange> <c=green>1/6 PV</c> "),
    PBFieldNote.new(32,"Effet d'Armumagma <icon=fieldPlus> . . .","Armumagma augmente la Défense et la Déf.Spé. d'un cran, et rend immunisé au type Feu."),
    PBFieldNote.new(32,"Effet de certaines capacités <icon=fieldUp> . . .","Danse Draco, Râle Mâle"),
    PBFieldNote.new(32,"Devient une <c=orange>Caverne</c> si . . .","...si Ère Glaciaire, Super Tourbillon Abyssal, Symphonie des Ondines ou Laser Cryogénique est utilisé, ou si Ocroupi, Aria de l'Écume ou Surf est utilisé deux fois."),
    PBFieldNote.new(32,"Force-Nature <icon=fieldChange> #{feToStringName(PBFields::DRAGONSD, :NATUREMOVES)}"),
    PBFieldNote.new(32,"Camouflage <icon=fieldChange> <icon=fieldDragon> "),
    PBFieldNote.new(32,"Force Cachée <icon=fieldChange> <icon=fieldBurn#{getSuffixFile()}> "),
    PBFieldNote.new(32,"Active <c=orange>Graine Élémentaire</c> . . .","Augmente l' Att.Spé. et applique le boost de Torche."),
  #Flower Garden Field
    PBFieldNote.new(33,"<c=orange>\"#{FIELDEFFECTS.dig(PBFields::FLOWERGARDENF, :INTROMESSAGE)}\"</c> "),
    PBFieldNote.new(33,"<c=orange>Croît</c> du <c=orange>Niveau 1</c> au <c=orange>Niveau 5</c> "),
    PBFieldNote.new(33,"Coupe et Plaie-Croix <c=red>réduisents</c> le <c=orange>Niveau</c> de 1","","<c=ffb347>2</c>+"),
    PBFieldNote.new(33,"Certaines capacités <icon=fieldChange> <icon=fieldPlus> <c=green>1</c> <c=orange>Niveau</c> . . .","Pétalexplosion Éblouissante, Croissance, Danse Pluie, Fertilisation, Zénith, Tourniquet, Racines.\nLes talents suivants augmentent également le terrain d'un Niveau: Crachin, Sécheresse, Don Floral, Flora-Voile"),
    PBFieldNote.new(33,"<c=green>Active</c> certains talents . . .","Don Floral, Essaim","<c=7CFC00>1</c>+"),
    PBFieldNote.new(33,"Effet de Fertilisation <icon=fieldUp> ","","<c=7CFC00>1</c>+"),
    PBFieldNote.new(33,"Effet de Fertilisation <icon=fieldPlus> . . .","Fertilisation augmente également d'un cran l'Attaque et l'Att.Spé. du lanceur.","<c=7CFC00>1</c>+"),
    PBFieldNote.new(33,"Effet de Croissance <icon=fieldUp> . . .","Augmente (x2,x3) aux Niveaux (1,3)","<c=7CFC00>1</c>,<c=ec5800>3</c> "),
    PBFieldNote.new(33,"Coupe <icon=fieldUp> <c=green>x1.5</c> ","","<c=ffb347>2</c>+"),
    PBFieldNote.new(33,"Coupe <icon=fieldChange> <c=green>x2</c> vs <icon=Field#{pbGetTypeNameFile(PBTypes::GRASS)}> ","","<c=ffb347>2</c>+"),
    PBFieldNote.new(33,"<c=green>Active</c> certains talents . . . ","Récolte, Feuille Garde","<c=ffb347>2</c>+"),
    PBFieldNote.new(33,"Effet de Garde Florale <icon=fieldPlus> . . .","Garde Florale augmente également la Déf.Spé. ainsi que les défenses du lanceur.","<c=ffb347>2</c>+"),
    PBFieldNote.new(33,"Garde Florale <icon=fieldPlus> <c=green>réduit</c> les dégâts . . .","Garde Florale réduit passivement (x0.75) les dégâts subis par les Pokémon Plante alliés.","<c=ec5800>3</c>+"),
    PBFieldNote.new(33,"Devient <c=orange>Terrain Enflammé</c> si . . .","#{feToStringName(PBFields::FLOWERGARDENF, :FIELDCHANGE, PBFields::BURNINGF)} est utilisé en l'absence de pluie ou de Tourniquet.","<c=ec5800>3</c>+"),
    PBFieldNote.new(33,"Doux Parfum <icon=fieldPlus> <c=green>réduit</c> les défenses","","<c=ec5800>3</c>+"),
    PBFieldNote.new(33,"Attaques <icon=field#{pbGetTypeNameFile(PBTypes::FIRE)}> <icon=fieldUp> <c=green>x1.5</c> ","","<c=ec5800>3</c>+"),
    PBFieldNote.new(33,"Effet de Garde Florale <icon=fieldUp> ","","<c=ec5800>3</c>+"),
    PBFieldNote.new(33,"<c=green>Active</c> Chlorophylle","","<c=ff2800>4</c>+"),
    PBFieldNote.new(33,"Faiblesses du type Plante <c=green>annullées</c> ","","<c=ff2800>4</c>+"),
    PBFieldNote.new(33,"Certaines attaques <icon=fieldChange> <c=green>multicible</c> ","Tempête Florale, Danse Fleur et les capacités de Poudre touchent les 2 adversaires au Niveau 5.","<c=ff00ff>5</c> "),
    PBFieldNote.new(33,"Attaques <icon=Field#{pbGetTypeNameFile(PBTypes::GRASS)}> <icon=fieldUp> ","Les attaques Plante gagnent en Puissance (x1.1,x1.3,x1.5,x2) aux Niveaux (2,3,4,5).","<c=ffb347>2</c>-<c=ff00ff>5</c> "),
    #PBFieldNote.new(33,"Damage <icon=fieldDown> vs <icon=Field#{pbGetTypeNameFile(PBTypes::GRASS)}> Pokémon . . .","Grass type Pokémon take damage reduced to (x0.75,x0.67,x0.5) aux Niveaux (3,4,5).","<c=ffb347>2</c>-<c=ff00ff>5</c> "),
    PBFieldNote.new(33,"Attaques <icon=Field#{pbGetTypeNameFile(PBTypes::BUG)}> <icon=fieldUp> . . .","Les attaques Insecte gagnent en Puissance (x1.5,x2) aux Niveaux (2,4).","<c=ffb347>2</c>,<c=ff2800>4</c> "),
    PBFieldNote.new(33,"Effet d'Essaim <icon=fieldUp> . . .","Essaime augmente la Puissance des attaques Insecte (x1.8,x2) aux Niveaux (3,5).","<c=ec5800>3</c>,<c=ff00ff>5</c> "),
    PBFieldNote.new(33,"<c=green>Active</c> Engrais si . . .","Engrais s'active à (66% PV, 100% PV) aux Niveaux (2,3).","<c=ffb347>2</c>,<c=ec5800>3</c> "),
    PBFieldNote.new(33,"Effet d'Engrais <icon=fieldUp> . . .","Engrais augmente la Puissance des attaques Plante (x1.8,x2) aux Niveaux (4,5).","<c=ff2800>4</c>,<c=ff00ff>5</c> "),
    PBFieldNote.new(33,"Effet de Doux Parfum <icon=fieldUp> . . .","Aux Niveaux 3 et plus, Doux Parfum réduit les défenses adverses. Cet effet est augmenté (x2,x3) aux Niveaux (4,5).","<c=ff2800>4</c>,<c=ff00ff>5</c> "),
    PBFieldNote.new(33,"Effet de Racines <icon=fieldUp> . . .","L'effet de Racines augmente (x2,x4) aux Niveaux (2,4).","<c=ffb347>2</c>,<c=ff2800>4</c> "),
    PBFieldNote.new(33,"Certaines attaques <icon=fieldUp> . . .","La Puissance de Canon Floral, Tempête Florale et Danse Fleur augmente (x1.2,x1.5) aux Niveaux (3,4).","<c=ec5800>3</c>,<c=ff2800>4</c> "),
    PBFieldNote.new(33,"Dégâts de Harcèlement <icon=fieldUp> . . .","Harcèlement inflige (1/6,1/4,1/3) des PV Max par tour aux Niveaux (3,4,5).","<c=ec5800>3</c>-<c=ff00ff>5</c> "),
    PBFieldNote.new(33,"Soin de Soin Floral <icon=fieldChange> <c=green>100 %</c> ","","<c=ec5800>3</c>+"),
    PBFieldNote.new(33,"Déluge Causti-Toxique fait <c=red>décroître</c> . . . ","...le terrain au Niveau 1."),
    PBFieldNote.new(33,"Force-Nature <icon=fieldChange> Croissance","","<c=7CFC00>1</c>-<c=ff2800>4</c> "),
    PBFieldNote.new(33,"Force-Nature <icon=fieldChange> Tempête Florale","","<c=ff00ff>5</c> "),
    PBFieldNote.new(33,"Camouflage <icon=fieldChange> <icon=Field#{pbGetTypeNameFile(PBTypes::GRASS)}> "),
    PBFieldNote.new(33,"Force Cachée <icon=fieldChange> <c=red>réduit</c> les stats . . .", "Force Cachée peut réduire l'Esquive, ainsi que les défenses aux Niveaux 3 et plus. Cet effet est doublé au Niveau 5.","<c=7CFC00>1</c> <c=ec5800>3</c> <c=ff00ff>5</c> "),
    PBFieldNote.new(33,"Active <c=orange>Graine Synthétique</c> . . .","Augmente la Déf.Spé. et applique Racines. Fait croître le terrain d'un Niveau."),
  #Starlight Arena
    PBFieldNote.new(34,"<c=orange>Cette obscure clarté . . .</c>","...qui tombe des étoiles..."),
    PBFieldNote.new(34,"<c=red>Destroyed</c> si . . .","...when Light That Burns The Sky est utilisé."),
    PBFieldNote.new(34,"Weather <c=red>stops</c> boosts . . .","...when weather is up, the field power boosts to moves and types isn't applied"),
    PBFieldNote.new(34,"Attaques <icon=Field#{pbGetTypeNameFile(PBTypes::PSYCHIC)}> <icon=fieldUp> <c=green>x1.5</c> "),
    PBFieldNote.new(34,"Attaques <icon=Field#{pbGetTypeNameFile(PBTypes::FAIRY)}> <icon=fieldUp> <c=green>x1.3</c> "),
    PBFieldNote.new(34,"Attaques <icon=Field#{pbGetTypeNameFile(PBTypes::DARK)}> <icon=fieldUp> <c=green>x1.5</c> "),
    PBFieldNote.new(34,"Attaques <icon=Field#{pbGetTypeNameFile(PBTypes::DARK)}> attacks <icon=fieldPlus> <icon=Field#{pbGetTypeNameFile(PBTypes::FAIRY)}> "),
    PBFieldNote.new(34,"Victory Star <icon=fieldPlus> <c=green>boosts</c> damage"),
    PBFieldNote.new(34,"Geomancy <icon=fieldChange> <c=green>no charge turn</c> "),
    PBFieldNote.new(34,"<c=green>Active</c> Marvel Scale"),
    PBFieldNote.new(34,"Illuminate <icon=fieldPlus> <c=green>boosts</c> stats . . .","Illuminate boosts Att.Spé. upon switching in."),
    PBFieldNote.new(34,"Certaines attaques <icon=fieldUp> <c=green>x1.5</c> . . . ",feToStringName(PBFields::STARLIGHTA, :MOVEDAMAGEBOOST, 1.5)),
    PBFieldNote.new(34,"Certaines attaques <icon=fieldUp> <c=green>x2</c> . . . ",feToStringName(PBFields::STARLIGHTA, :MOVEDAMAGEBOOST, 2.0)),
    PBFieldNote.new(34,"Doom Desire <icon=fieldUp> <c=green>x4</c> and <icon=fieldPlus> <icon=field#{pbGetTypeNameFile(PBTypes::FIRE)}> "),
    PBFieldNote.new(34,"Certaines attaques <icon=fieldChange> <icon=Field#{pbGetTypeNameFile(PBTypes::FAIRY)}> . . .","Solar Beam, Solar Blade"),
    PBFieldNote.new(34,"Effet de certaines capacités <icon=fieldUp> . . .","Cosmic Power, Flash"),
    PBFieldNote.new(34,"Wish recovery <icon=fieldChange> <c=green>75 % PV</c> "),
    PBFieldNote.new(34,"Certaines attaques <icon=fieldPlus> <c=green>boost</c> stats","Healing Wish and Lunar Dance boost recipient's Attack and Special Attack"),
    PBFieldNote.new(34,"Moonlight recovery <icon=fieldChange> <c=green>75 % PV</c> "),
    PBFieldNote.new(34,"<c=green>Autorise</c> Voile Aurore"),
    PBFieldNote.new(34,"Shadow Shield <c=green>reduces</c> damage","Shadow Shield reduces damage of super effective hits by 0.75"),
    PBFieldNote.new(34,"Force-Nature <icon=fieldChange> #{feToStringName(PBFields::STARLIGHTA, :NATUREMOVES)}"),
    PBFieldNote.new(34,"Camouflage <icon=fieldChange> <icon=Field#{pbGetTypeNameFile(PBTypes::DARK)}> "),
    PBFieldNote.new(34,"Force Cachée <icon=fieldChange> <c=red>réduit</c> Déf.Spé."),
    PBFieldNote.new(34,"Active <c=orange>Graine Magique</c> . . .","Boosts Att.Spé. et applique Wish to the user."),
  #New World
    PBFieldNote.new(35,"<c=orange>\"From darkness, from stardust . . .</c> ", "From darkness, from stardust, from memories of eons past and visions yet to come..."),
    PBFieldNote.new(35,"certains talents change type . . .", "Multitype and RKS System randomly select a new type chaque tour."),
    PBFieldNote.new(35,"Vitesse <icon=fieldDown> <c=red>x0.75</c> si au sol"),
    PBFieldNote.new(35,"Airborne Pokémon defenses <icon=fieldDown> <c=red>x0.9</c>"),
    PBFieldNote.new(35,"<c=red>Prevents</c> all generated weather"),
    PBFieldNote.new(35,"<c=red>Prevents</c> generated Fields"),
    PBFieldNote.new(35,"Attaques <icon=Field#{pbGetTypeNameFile(PBTypes::DARK)}> <icon=fieldUp> <c=green>x1.5</c> "),
    PBFieldNote.new(35,"Certaines attaques <icon=fieldUp> <c=green>x1.5</c> . . . ",feToStringName(PBFields::NEWW, :MOVEDAMAGEBOOST, 1.5)),
    PBFieldNote.new(35,"Certaines attaques <icon=fieldUp> <c=green>x2</c> . . . ",feToStringName(PBFields::NEWW, :MOVEDAMAGEBOOST, 2.0)),
    PBFieldNote.new(35,"Certaines attaques <icon=fieldDown> <c=red>x0.25</c> . . . ",feToStringName(PBFields::NEWW, :MOVEDAMAGEBOOST, 0.25)),
    PBFieldNote.new(35,"Fissure <c=red>fails</c> "),
    PBFieldNote.new(35,"Doom Desire <icon=fieldUp> <c=green>x4</c> and <icon=fieldPlus> <icon=field#{pbGetTypeNameFile(PBTypes::FIRE)}> "),
    PBFieldNote.new(35,"Heart Swap <icon=fieldPlus> Pain Split effect"),
    PBFieldNote.new(35,"Victory Star damage <icon=fieldUp> <c=green>x1.5</c> "),
    PBFieldNote.new(35,"Dark Void's Précision <icon=fieldChange> <c=green>85</c> "),
    PBFieldNote.new(35,"Lunar Dance <icon=fieldPlus> <c=green>boosts</c> all stats"),
    PBFieldNote.new(35,"Certain moves last <c=green>8</c> tours . . .","Trick Room, Magic Room, Wonder Room"),
    PBFieldNote.new(35,"Effet de certaines capacités <icon=fieldUp> . . .","Cosmic Power, Flash"),
    PBFieldNote.new(35,"Moonlight recovery <icon=fieldChange> <c=green>75 % PV</c> "),
    PBFieldNote.new(35,"Devient a <c=orange>Starlight Arena</c> si . . .","...when Geomancy est utilisé, or when Gravity est utilisé for as long as Gravity dure."),
    PBFieldNote.new(35,"Nature's Madness damage <icon=fieldChange> <c=green>75 % PV</c> "),
    PBFieldNote.new(35,"Shadow Shield <c=green>reduces</c> damage","Shadow Shield reduces damage of super effective hits by 0.75"),
    PBFieldNote.new(35,"Force-Nature <icon=fieldChange> #{feToStringName(PBFields::NEWW, :NATUREMOVES)}"),
    PBFieldNote.new(35,"Camouflage <icon=fieldChange> random type "),
    PBFieldNote.new(35,"Force Cachée <icon=fieldChange> <c=red>réduit</c> all stats"),
    PBFieldNote.new(35,"Active <c=orange>Graine Magique</c> . . .","Boosts all stats, but makes the user recharge."),
  #Inverse Field
    PBFieldNote.new(36,"<c=orange>\"#{FIELDEFFECTS.dig(PBFields::INVERSEF, :INTROMESSAGE)}\"</c> "),
    PBFieldNote.new(36,"The type chart is <c=orange> inverted</c> "),
    PBFieldNote.new(36,"<c=green>Créé</c> par Renversement . . .","...Créé pendant 3 tours si l'attaquant ne tient pas de Pierre Stase."),
    PBFieldNote.new(36,"Force-Nature <icon=fieldChange> #{feToStringName(PBFields::INVERSEF, :NATUREMOVES)}"),
    PBFieldNote.new(36,"Camouflage <icon=fieldChange> <icon=field#{PBTypes.getName(FIELDEFFECTS.dig(PBFields::INVERSEF, :MIMICRY))}> "),
    PBFieldNote.new(36,"Force Cachée <icon=fieldChange> rend confus"),
    PBFieldNote.new(36,"Active <c=orange>Graine Magique</c> . . .","Booste toutes les stats, mais provoque un tour de recharge."),
  #Psychic Field
    PBFieldNote.new(37,"<c=orange>\"#{FIELDEFFECTS.dig(PBFields::PSYCHICT, :INTROMESSAGE)}\"</c> "),
    PBFieldNote.new(37,"Les attaques de priorité <c=red>échouent</c> . . .","...si la cible est au sol."),
    PBFieldNote.new(37,"<c=green>Créé</c> par . . .","...Champ Psychique, Créa-Psy, ou Supernova Originelle (5 tours)."),
    PBFieldNote.new(37,"Attaques <icon=Field#{pbGetTypeNameFile(PBTypes::PSYCHIC)}> <icon=fieldUp> <c=green>x1.5</c> si . . .","...si l'attaquant est au sol."),
    PBFieldNote.new(37,"Certaines attaques <icon=fieldUp> <c=green>x1.5</c> . . . ",feToStringName(PBFields::PSYCHICT, :MOVEDAMAGEBOOST, 1.5)),
    PBFieldNote.new(37,"Boost de Force Pure <icon=fieldChange> Att.Spé."),
    PBFieldNote.new(37,"Anticipation <c=green>augmente</c> l'Att.Spé."),
    PBFieldNote.new(37,"Télépathe <c=green>augmente</c> la Vitesse <c=green>x2</c> "),
    PBFieldNote.new(37,"Effet de certaines capacités <icon=fieldUp> . . .","Plénitude, Force Cosmik, Télékinésie, Yoga, Machination."),
    PBFieldNote.new(37,"Certaines capacités <icon=fieldPlus> Att.Spé. . . .","Lire-Esprit et Œil Miracle augmentent l'Att.Spé. d'un cran. Boost augmente l'Att.Spé. de deux crans."),
    PBFieldNote.new(37,"Précision d'Hypnose <icon=fieldChange> <c=green>90</c> "),
    PBFieldNote.new(37,"Télékinésie <icon=fieldPlus> <icon=fieldUp> Att/Att.Spé."),
    PBFieldNote.new(37,"Lévikinésie <icon=fieldPlus> <icon=fieldDown> Déf/Déf.Spé. <c=red>x2</c> "),
    PBFieldNote.new(37,"Certaines capacités <icon=fieldChange> <c=green>8</c> tours","Gravité, Zone Magique, Zone Étrange, Distorsion."),
    PBFieldNote.new(37,"Psycho-Pulvarisation EX <icon=fieldPlus> confusion"),
    PBFieldNote.new(37,"Force-Nature <icon=fieldChange> #{feToStringName(PBFields::PSYCHICT, :NATUREMOVES)}"),
    PBFieldNote.new(37,"Camouflage <icon=fieldChange> <icon=Field#{pbGetTypeNameFile(PBTypes::PSYCHIC)}> "),
    PBFieldNote.new(37,"Force Cachée <icon=fieldChange> peut rendre confus"),
    PBFieldNote.new(37,"Active <c=orange>Graine Magique</c> . . .","Augmente l'Att.Spé. de deux crans mais rend confus.")

  ]

  File.open("Data/fieldnotes_" + LANGUAGES[$idk[:settings].language][1] + ".dat","wb"){|file|
    Marshal.dump(all_field_notes,file)
  }
end
