FIELDEFFECTS = {
	PBFields::NONE => { #can also be used as a prototype!
		:FIELDNAME => nil,
		:INTROMESSAGE => nil,
		:FIELDGRAPHICS => "IndoorA",
		:SECRETPOWERANIM => PBMoves::TRIATTACK,
		:NATUREMOVES => PBMoves::TRIATTACK,
		:MIMICRY => PBTypes::NORMAL,
		:MOVEDAMAGEBOOST => {},
		:MOVEMESSAGES => {},
		:MOVETYPEMOD => {},
		:MOVETYPECHANGE => {},
		:MOVEACCURACYBOOST => {},
		:TYPEDAMAGEBOOST => {},
		:TYPEMESSAGES => {},
		:TYPECONDITION => {},
		:TYPETYPEMOD => {}, #type modifier based on original type
		:TYPETYPECHANGE => {},
		:FIELDCHANGE => {},
		:DONTCHANGEBACKUP => [],
		:CHANGEMESSAGE => {},
		:CHANGECONDITION => {},
		:CHANGEEFFECTS => {},
		:SEED => nil,
		:SEEDEFFECT => nil,
		:SEEDEFFECTVAL => nil,
		:SEEDEFFECTSTR => nil,
		:SEEDANIM => nil,
		:SEEDSTATS => {}
		},
	# 1 Electric Terrain
	PBFields::ELECTRICT => {
		:FIELDNAME => "Champ Électrifié",
		:INTROMESSAGE => "Le Terrain est surchargé!",
		:FIELDGRAPHICS => "Electric",
		:SECRETPOWERANIM => PBMoves::SHOCKWAVE,
		:NATUREMOVES => PBMoves::THUNDERBOLT,
		:MIMICRY => PBTypes::ELECTRIC,
		:MOVEDAMAGEBOOST => {
		1.5 => [PBMoves::EXPLOSION, PBMoves::SELFDESTRUCT, PBMoves::HURRICANE, PBMoves::SURF,
						PBMoves::SMACKDOWN, PBMoves::MUDDYWATER, PBMoves::THOUSANDARROWS],
		2.0 => [PBMoves::MAGNETBOMB]},
		:MOVEMESSAGES => {
		"L'explosion est surchargée!" => [PBMoves::EXPLOSION, PBMoves::SELFDESTRUCT],
		"L'attaque est surchargée!" => [PBMoves::HURRICANE, PBMoves::SURF, 
			PBMoves::SMACKDOWN, PBMoves::MUDDYWATER, PBMoves::THOUSANDARROWS],
		"L'attaque est amplifiée!" => [PBMoves::MAGNETBOMB]},
		:MOVETYPEMOD => {
		PBTypes::ELECTRIC => [PBMoves::EXPLOSION, PBMoves::SELFDESTRUCT, PBMoves::SMACKDOWN, 
			PBMoves::SURF, PBMoves::MUDDYWATER, PBMoves::HURRICANE, PBMoves::THOUSANDARROWS, PBMoves::HYDROVORTEX]},
		:MOVEACCURACYBOOST => {},
		:TYPEDAMAGEBOOST => {1.5 => [PBTypes::ELECTRIC]},
		:TYPEMESSAGES => {"Le Champ Électrifié renforce l'attaque!" => [PBTypes::ELECTRIC]},
		:TYPECONDITION => {PBTypes::ELECTRIC => "!attacker.isAirborne?" },
		:FIELDCHANGE => {0 => [PBMoves::MUDSPORT, PBMoves::TECTONICRAGE]},
		:CHANGEMESSAGE => {"Le terrain se décharge!" => [PBMoves::MUDSPORT, PBMoves::TECTONICRAGE]},
		:STATUSMOVEBOOST => [PBMoves::CHARGE, PBMoves::EERIEIMPULSE,PBMoves::MAGNETRISE],
		:CHANGEEFFECTS => {},
		:SEED => PBItems::ELEMENTALSEED,
		:SEEDEFFECT => PBEffects::Charge,
		:SEEDEFFECTVAL => 2,
		:SEEDEFFECTSTR => "{1} se charge en électricité!",
		:SEEDANIM => PBMoves::CHARGE,
		:SEEDSTATS => {PBStats::SPEED => 1}
		},
	# 2 Grassy Terrain
	PBFields::GRASSYT => {
		:FIELDNAME => "Champ Herbu",
		:INTROMESSAGE => "Le terrain est un beau gazon.",
		:FIELDGRAPHICS =>  "Grassy",
		:SECRETPOWERANIM => PBMoves::SEEDBOMB,
		:NATUREMOVES => PBMoves::ENERGYBALL,
		:MIMICRY => PBTypes::GRASS,
		:MOVEDAMAGEBOOST => {
		1.5 => [PBMoves::FAIRYWIND, PBMoves::SILVERWIND],
		0.5 => [PBMoves::MUDDYWATER, PBMoves::SURF, PBMoves::EARTHQUAKE,
						PBMoves::MAGNITUDE, PBMoves::BULLDOZE]
		},
		:MOVEACCURACYBOOST => {80 => [PBMoves::GRASSWHISTLE]},
		:MOVEMESSAGES => {
		"Le vent est renforcé par le terrain!" => [PBMoves::FAIRYWIND, PBMoves::SILVERWIND],
		"L'herbe affaiblit l'attaque..." => [PBMoves::MUDDYWATER, PBMoves::SURF, 
			PBMoves::EARTHQUAKE, PBMoves::MAGNITUDE, PBMoves::BULLDOZE]},
		:TYPEDAMAGEBOOST => {1.5 => [PBTypes::GRASS,PBTypes::FIRE]},
		:TYPEMESSAGES => {
		"Le Champ Herbu renforce l'attaque!" => [PBTypes::GRASS],
		"La pelouse prend feu!" => [PBTypes::FIRE]},
		:TYPECONDITION => {
			PBTypes::GRASS => "!attacker.isAirborne?",
			PBTypes::FIRE =>  "!opponent.isAirborne?"
		},
		:FIELDCHANGE => {
		PBFields::BURNINGF => PBFields::IGNITEMOVES,
		PBFields::CORROSIVEF => [PBMoves::SLUDGEWAVE, PBMoves::ACIDDOWNPOUR]},
		:DONTCHANGEBACKUP => PBFields::IGNITEMOVES + [PBMoves::SLUDGEWAVE, PBMoves::ACIDDOWNPOUR],
		:CHANGEMESSAGE => {
		"La pelouse prend feu!" => PBFields::IGNITEMOVES,
		"la pelouse est intoxiquée!" => [PBMoves::SLUDGEWAVE, PBMoves::ACIDDOWNPOUR]},
		:CHANGECONDITION => {PBFields::BURNINGF => "ignitecheck"},
		:STATUSMOVEBOOST => [PBMoves::COIL,PBMoves::GROWTH,PBMoves::FLORALHEALING,PBMoves::GRASSWHISTLE],
		:CHANGEEFFECTS => {},
		:SEED => PBItems::ELEMENTALSEED,
		:SEEDEFFECT => PBEffects::Ingrain,
		:SEEDEFFECTVAL => true,
		:SEEDEFFECTSTR => "{1} plante ses racines!",
		:SEEDANIM => PBMoves::INGRAIN,
		:SEEDSTATS => {PBStats::DEFENSE => 1}
		},
	# 3 Misty Terrain
	PBFields::MISTYT => {
		:FIELDNAME => "Champ Brumeux",
		:INTROMESSAGE => "La brume s'installe sur le terrain.",
		:FIELDGRAPHICS =>  "Misty",
		:SECRETPOWERANIM => PBMoves::MISTBALL,
		:NATUREMOVES => PBMoves::MISTBALL,
		:MIMICRY => PBTypes::FAIRY,
		:MOVEDAMAGEBOOST => {
		1.5 => [PBMoves::FAIRYWIND, PBMoves::MYSTICALFIRE, PBMoves::MOONBLAST, 
						PBMoves::MAGICALLEAF, PBMoves::DOOMDUMMY, PBMoves::ICYWIND,
						PBMoves::MISTBALL, PBMoves::AURASPHERE, PBMoves::STEAMERUPTION, 
						PBMoves::DAZZLINGGLEAM, PBMoves::SILVERWIND, PBMoves::MOONGEISTBEAM],
		0.5 => [PBMoves::DARKPULSE, PBMoves::SHADOWBALL, PBMoves::NIGHTDAZE]},
		:MOVEMESSAGES => {
		"La brume renforce l'attaque!" => [PBMoves::FAIRYWIND, PBMoves::MYSTICALFIRE, 
			PBMoves::MOONBLAST, PBMoves::MAGICALLEAF, PBMoves::DOOMDUMMY, PBMoves::ICYWIND, 
			PBMoves::MISTBALL, PBMoves::AURASPHERE, PBMoves::STEAMERUPTION, PBMoves::DAZZLINGGLEAM, 
			PBMoves::SILVERWIND, PBMoves::MOONGEISTBEAM],
		"La brume affaiblit l'attaque..." => [PBMoves::DARKPULSE, PBMoves::SHADOWBALL, PBMoves::NIGHTDAZE]},
		:TYPEDAMAGEBOOST => {0.5 => [PBTypes::DRAGON]},
		:TYPEMESSAGES => {"Le Champ Brumeux affaiblit l'attaque!" => [PBTypes::DRAGON]},
		:FIELDCHANGE => {0 => PBFields::BLOWMOVES},
		:CHANGEMESSAGE => {"La brume se dissipe!" => PBFields::BLOWMOVES},
		:STATUSMOVEBOOST => [PBMoves::COSMICPOWER, PBMoves::AROMATICMIST, PBMoves::SWEETSCENT],
		:CHANGEEFFECTS => {},
		:SEED => PBItems::ELEMENTALSEED,
		:SEEDEFFECT => PBEffects::Wish,
		:SEEDEFFECTVAL => 2,
		:SEEDEFFECTSTR => "Un vœu est fait pour {1}!",
		:SEEDANIM => PBMoves::WISH,
		:SEEDSTATS => {PBStats::SPDEF => 1}
		},
	# 4 Dark Crystal Cavern
	PBFields::DARKCRYSTALC => {
		:FIELDNAME => "Caverne Obscure",
		:INTROMESSAGE => "L'obscurité s'amasse...",
		:FIELDGRAPHICS => "DarkCrystalCavern",
		:SECRETPOWERANIM => PBMoves::DARKPULSE,
		:NATUREMOVES => PBMoves::DARKPULSE,
		:MIMICRY => PBTypes::DARK,
		:MOVEDAMAGEBOOST => {
		1.5 => [PBMoves::DARKPULSE, PBMoves::NIGHTDAZE, PBMoves::NIGHTSLASH,
						PBMoves::SHADOWBALL, PBMoves::SHADOWPUNCH, PBMoves::SHADOWCLAW, 
						PBMoves::SHADOWSNEAK, PBMoves::SHADOWFORCE, PBMoves::SHADOWBONE, 
						PBMoves::AURORABEAM, PBMoves::SIGNALBEAM, PBMoves::FLASHCANNON, 
						PBMoves::LUSTERPURGE, PBMoves::DAZZLINGGLEAM, PBMoves::MIRRORSHOT, 
						PBMoves::TECHNOBLAST, PBMoves::DOOMDUMMY, PBMoves::POWERGEM, 
						PBMoves::MOONGEISTBEAM, PBMoves::PHOTONGEYSER, PBMoves::DIAMONDSTORM,
						PBMoves::MENACINGMOONRAZEMAELSTROM],
		2.0 => [PBMoves::PRISMATICLASER, PBMoves::BLACKHOLEECLIPSE],
		0.5 => [PBMoves::LIGHTTHATBURNSTHESKY]},
		:MOVEACCURACYBOOST => {100 => [PBMoves::DARKVOID]},
		:MOVEMESSAGES => {
		"L'obscurité s'amasse...!" => [PBMoves::DARKPULSE, PBMoves::NIGHTDAZE, PBMoves::NIGHTSLASH],
		"L'obscurité renforce l'attaque!"	=> [PBMoves::SHADOWBALL, PBMoves::SHADOWPUNCH, 
			PBMoves::SHADOWCLAW, PBMoves::SHADOWSNEAK, PBMoves::SHADOWFORCE, PBMoves::SHADOWBONE,
			PBMoves::MENACINGMOONRAZEMAELSTROM], 
		"La lumière des cristaux renforce l'attaque!" =>	[PBMoves::AURORABEAM, 
			PBMoves::SIGNALBEAM, PBMoves::FLASHCANNON, PBMoves::LUSTERPURGE, 
			PBMoves::DAZZLINGGLEAM, PBMoves::MIRRORSHOT, PBMoves::TECHNOBLAST, 
			PBMoves::DOOMDUMMY, PBMoves::POWERGEM, PBMoves::MOONGEISTBEAM, 
			PBMoves::PHOTONGEYSER, PBMoves::DIAMONDSTORM],
		"Le cristal diffracte l'attaque!" => [PBMoves::PRISMATICLASER], 
		"L'attaque se nourrit de l'obscurité!" => [PBMoves::BLACKHOLEECLIPSE],
		"{1} n'a pas de lumière à consumer..." => [PBMoves::LIGHTTHATBURNSTHESKY]},
		:FIELDCHANGE => {
			PBFields::CAVE => PBFields::QUAKEMOVES,
			PBFields::CRYSTALC => [PBMoves::SUNNYDAY]},
		:DONTCHANGEBACKUP => [PBMoves::SUNNYDAY],
		:CHANGEMESSAGE => {
			"Les cristaux sont fracassés!" => PBFields::QUAKEMOVES,
			"Le soleil éclaire la caverne!" => [PBMoves::SUNNYDAY]},
		:CHANGECONDITION => {PBFields::CRYSTALC => "suncheck"},
		:STATUSMOVEBOOST => [PBMoves::FLASH, PBMoves::DARKVOID, PBMoves::MOONLIGHT],
		:CHANGEEFFECTS => {},
		:SEED => PBItems::MAGICALSEED,
		:SEEDEFFECT => PBEffects::MagicCoat,
		:SEEDEFFECTVAL => true,
		:SEEDEFFECTSTR => "{1} s'entoure du Reflet Magik!",
		:SEEDANIM => PBMoves::MAGICCOAT,
		:SEEDSTATS => {PBStats::SPDEF => 1}
		},
	# 5 Chess Board
	PBFields::CHESSB => {
		:FIELDNAME => "Échiquier",
		:INTROMESSAGE => "Ouverture.",
		:FIELDGRAPHICS =>  "Chess",
		:SECRETPOWERANIM => PBMoves::FEINT,
		:NATUREMOVES => PBMoves::ANCIENTPOWER,
		:MIMICRY => PBTypes::PSYCHIC,
		:MOVEDAMAGEBOOST => {1.5 => [PBMoves::FEINT, PBMoves::FEINTATTACK, PBMoves::FAKEOUT, PBMoves::SUCKERPUNCH, 
			PBMoves::FIRSTIMPRESSION, PBMoves::SHADOWSNEAK, PBMoves::SMARTSTRIKE] + PBFields::CHESSMOVES},
		:MOVEMESSAGES => {"En passant!" => [PBMoves::FEINT, PBMoves::FEINTATTACK, PBMoves::FAKEOUT,
			PBMoves::SUCKERPUNCH, PBMoves::FIRSTIMPRESSION, PBMoves::SHADOWSNEAK, PBMoves::SMARTSTRIKE]},
		:MOVETYPEMOD => {PBTypes::ROCK => PBFields::CHESSMOVES},
		:FIELDCHANGE => {0 => [PBMoves::STOMPINGTANTRUM, PBMoves::TECTONICRAGE]},
		:CHANGEMESSAGE => {"Le plateau est détruit!" => [PBMoves::STOMPINGTANTRUM, PBMoves::TECTONICRAGE]},
		:STATUSMOVEBOOST => [PBMoves::CALMMIND, PBMoves::NASTYPLOT, PBMoves::TRICKROOM],
		:CHANGEEFFECTS => {},
		:SEED => PBItems::SYNTHETICSEED,
		:SEEDEFFECT => PBEffects::MagicCoat,
		:SEEDEFFECTVAL => true,
		:SEEDEFFECTSTR => "{1} s'entoure du Reflet Magik!",
		:SEEDANIM => PBMoves::MAGICCOAT,
		:SEEDSTATS => {PBStats::SPATK => 1}
		},
	# 6 Big Top Arena
	PBFields::BIGTOPA => {
		:FIELDNAME => "Scène de Spectacle",
		:INTROMESSAGE => "Le prochain numéro...!",
		:FIELDGRAPHICS =>  "BigTop",
		:SECRETPOWERANIM => PBMoves::DYNAMICPUNCH,
		:NATUREMOVES => PBMoves::ACROBATICS,
		:MIMICRY => PBTypes::NORMAL,
		:MOVEDAMAGEBOOST => {
		1.5 => [PBMoves::VINEWHIP, PBMoves::POWERWHIP, PBMoves::FIRELASH, 
						PBMoves::FIERYDANCE, PBMoves::PETALDANCE, PBMoves::REVELATIONDANCE, 
						PBMoves::FLY, PBMoves::ACROBATICS, PBMoves::FIRSTIMPRESSION],
		2.0 => [PBMoves::PAYDAY]},
		:MOVEACCURACYBOOST => {100 => [PBMoves::SING]},
		:MOVEMESSAGES => {
		"Arrière, fauve!" => [PBMoves::VINEWHIP, PBMoves::POWERWHIP, PBMoves::FIRELASH], 
		"Quelle grâce!" => [PBMoves::FIERYDANCE, PBMoves::PETALDANCE, PBMoves::REVELATIONDANCE], 
		"Un final aérien extravagant!" => [PBMoves::FLY, PBMoves::ACROBATICS], 
		"Quelle entrée!" => [PBMoves::FIRSTIMPRESSION],
		"Et un petit bonus pour toi, mon cœur!!" => [PBMoves::PAYDAY]},
		:STATUSMOVEBOOST => [PBMoves::ENCORE, PBMoves::DRAGONDANCE, PBMoves::QUIVERDANCE, PBMoves::SWORDSDANCE, PBMoves::FEATHERDANCE,
			PBMoves::SING, PBMoves::RAINDANCE, PBMoves::BELLYDRUM, PBMoves::SPOTLIGHT],
		:CHANGEEFFECTS => {},
		:SEED => PBItems::SYNTHETICSEED,
		:SEEDEFFECT => PBEffects::HelpingHand,
		:SEEDEFFECTVAL => true,
		:SEEDEFFECTSTR => "{1} accepte l'aide de la foule!",
		:SEEDANIM => PBMoves::HELPINGHAND,
		:SEEDSTATS => {PBStats::ATTACK => 1}
		},
	# 7 Burning Field
	PBFields::BURNINGF => {
		:FIELDNAME => "Terrain Enflammé",
		:INTROMESSAGE => "Le terrain est en feu!",
		:FIELDGRAPHICS =>  "Burning",
		:SECRETPOWERANIM => PBMoves::FLAMETHROWER,
		:NATUREMOVES => PBMoves::FLAMETHROWER,
		:MIMICRY => PBTypes::FIRE,
		:MOVEDAMAGEBOOST => {
		1.5 => [PBMoves::SMOG, PBMoves::CLEARSMOG],
		2.0 => [PBMoves::SMACKDOWN, PBMoves::THOUSANDARROWS]},
		:MOVEACCURACYBOOST => {100 => [PBMoves::WILLOWISP]},
		:MOVEMESSAGES => {
		"Les flammes se propagent!" => [PBMoves::SMOG, PBMoves::CLEARSMOG],
		"{1} est poussé dans les flammes!" => [PBMoves::SMACKDOWN, PBMoves::THOUSANDARROWS]},
		:MOVETYPEMOD => {
		PBTypes::FIRE => [PBMoves::SMACKDOWN, PBMoves::SMOG,
											PBMoves::CLEARSMOG, PBMoves::THOUSANDARROWS]},
		:TYPEDAMAGEBOOST => {
		1.5 => [PBTypes::FIRE],
		0.5 => [PBTypes::GRASS,PBTypes::ICE]},
		:TYPEMESSAGES => {
		"Le brasier amplifie l'attaque!" => [PBTypes::FIRE],
    	"Le brasier affaiblit l'attaque..." => [PBTypes::GRASS,PBTypes::ICE]},
    	:TYPECONDITION => {
			PBTypes::FIRE =>  "!attacker.isAirborne?",
			PBTypes::GRASS => "!opponent.isAirborne?"
		},
		:FIELDCHANGE => {
		0 => PBFields::BLOWMOVES + [PBMoves::WATERSPORT,PBMoves::SURF, PBMoves::MUDDYWATER, 
		PBMoves::WATERSPOUT, PBMoves::WATERPLEDGE, PBMoves::SPARKLINGARIA, 
		PBMoves::SLUDGEWAVE, PBMoves::SANDTOMB, PBMoves::CONTINENTALCRUSH, PBMoves::HYDROVORTEX, PBMoves::OCEANICOPERETTA]},
		:CHANGEMESSAGE => {
		"La crasse étouffe les flammes!" => [PBMoves::SLUDGEWAVE],
		"Le vent étouffe les flammes!" => PBFields::BLOWMOVES,
		"L'eau étouffe les flammes!" => [PBMoves::WATERSPORT,PBMoves::SURF, 
			PBMoves::MUDDYWATER, PBMoves::WATERSPOUT, PBMoves::WATERPLEDGE, 
			PBMoves::SPARKLINGARIA, PBMoves::HYDROVORTEX, PBMoves::OCEANICOPERETTA],
		"The sand snuffed out the flame!" => [PBMoves::SANDTOMB, PBMoves::CONTINENTALCRUSH]},
		:STATUSMOVEBOOST => [PBMoves::WILLOWISP, PBMoves::SMOKESCREEN],
		:CHANGEEFFECTS => {},
		:SEED => PBItems::ELEMENTALSEED,
		:SEEDEFFECT => PBEffects::MultiTurnAttack,
		:SEEDEFFECTVAL => PBMoves::FIRESPIN,
		:SEEDEFFECTSTR => "{1} est piégé dans le vortex!",
		:SEEDANIM => PBMoves::FIRESPIN,
		:SEEDSTATS => {PBStats::ATTACK => 1, PBStats::SPATK => 1, PBStats::SPEED => 1}
		},
	# 8 Swamp Field
	PBFields::SWAMPF => {
		:FIELDNAME => "Marécage",
		:INTROMESSAGE => "Le terrain est marécageux.",
		:FIELDGRAPHICS =>  "Swamp",
		:SECRETPOWERANIM => PBMoves::MUDDYWATER,
		:NATUREMOVES => PBMoves::MUDDYWATER,
		:MIMICRY => PBTypes::WATER,
		:MOVEDAMAGEBOOST => {
		1.5 => [PBMoves::MUDBOMB, PBMoves::MUDSHOT, PBMoves::MUDSLAP, PBMoves::MUDDYWATER, 
						PBMoves::SURF, PBMoves::SLUDGEWAVE, PBMoves::GUNKSHOT, PBMoves::BRINE, 
						PBMoves::SMACKDOWN, PBMoves::THOUSANDARROWS, PBMoves::HYDROVORTEX],
		0.25 => [PBMoves::EARTHQUAKE, PBMoves::MAGNITUDE, PBMoves::BULLDOZE]},
		:MOVEACCURACYBOOST => {100 => [PBMoves::SLEEPPOWDER]},
		:MOVEMESSAGES => {
		"La vase renforce l'attaque!" => [PBMoves::MUDBOMB, PBMoves::MUDSHOT, 
			PBMoves::MUDSLAP, PBMoves::MUDDYWATER, PBMoves::SURF, PBMoves::SLUDGEWAVE, 
			PBMoves::GUNKSHOT, PBMoves::BRINE, PBMoves::SMACKDOWN, PBMoves::THOUSANDARROWS, PBMoves::HYDROVORTEX],
		"L'attaque se dissipe sur le sol vaseux..." => [PBMoves::EARTHQUAKE, 
			PBMoves::MAGNITUDE, PBMoves::BULLDOZE]},
		:MOVETYPEMOD => {PBTypes::WATER => [PBMoves::SMACKDOWN, PBMoves::THOUSANDARROWS]},
		:TYPEDAMAGEBOOST => {1.5 => [PBTypes::POISON]},
		:TYPEMESSAGES => {"Le poison infecte la vase environnante!" => [PBTypes::POISON]},
		:TYPECONDITION => {PBTypes::POISON => "!opponent.isAirborne?" },
		:STATUSMOVEBOOST => [PBMoves::SLEEPPOWDER, PBMoves::AQUARING],
		:CHANGEEFFECTS => {},
		:SEED => PBItems::TELLURICSEED,
		:SEEDEFFECT => PBEffects::Ingrain,
		:SEEDEFFECTVAL => true,
		:SEEDEFFECTSTR => "{1} plante ses racines!",
		:SEEDANIM => PBMoves::INGRAIN,
		:SEEDSTATS => {PBStats::DEFENSE => 1,PBStats::SPDEF => 1}
		},
	# 9 Rainbow Field
	PBFields::RAINBOWF => {
		:FIELDNAME => "Champ Arc-en-ciel",
		:INTROMESSAGE => "Qu'est-ce que ça veut dire?",
		:FIELDGRAPHICS =>  "Rainbow",
		:SECRETPOWERANIM => PBMoves::AURORABEAM,
		:NATUREMOVES => PBMoves::AURORABEAM,
		:MIMICRY => PBTypes::DRAGON,
		:MOVEDAMAGEBOOST => {
		1.5 => [PBMoves::SILVERWIND, PBMoves::MYSTICALFIRE, PBMoves::DRAGONPULSE, 
					PBMoves::TRIATTACK, PBMoves::SACREDFIRE, PBMoves::FIREPLEDGE, 
					PBMoves::WATERPLEDGE, PBMoves::GRASSPLEDGE, PBMoves::AURORABEAM, 
					PBMoves::JUDGMENT, PBMoves::RELICSONG, PBMoves::HIDDENPOWER, 
					PBMoves::SECRETPOWER, PBMoves::WEATHERBALL, PBMoves::MISTBALL, 
					PBMoves::HEARTSTAMP, PBMoves::MOONBLAST, PBMoves::ZENHEADBUTT, 
					PBMoves::SPARKLINGARIA, PBMoves::FLEURCANNON, PBMoves::PRISMATICLASER, PBMoves::TWINKLETACKLE,
					PBMoves::OCEANICOPERETTA, PBMoves::SOLARBEAM, PBMoves::SOLARBLADE, PBMoves::DAZZLINGGLEAM,
					PBMoves::HIDDENPOWERNOR,PBMoves::HIDDENPOWERFIR,PBMoves::HIDDENPOWERFIG,PBMoves::HIDDENPOWERWAT,PBMoves::HIDDENPOWERFLY,
					PBMoves::HIDDENPOWERGRA,PBMoves::HIDDENPOWERPOI,PBMoves::HIDDENPOWERELE,PBMoves::HIDDENPOWERGRO,PBMoves::HIDDENPOWERPSY,
					PBMoves::HIDDENPOWERROC,PBMoves::HIDDENPOWERICE,PBMoves::HIDDENPOWERBUG,PBMoves::HIDDENPOWERDRA,PBMoves::HIDDENPOWERGHO,
					PBMoves::HIDDENPOWERDAR,PBMoves::HIDDENPOWERSTE,PBMoves::HIDDENPOWERFAI],
		0.5 => [PBMoves::DARKPULSE, PBMoves::SHADOWBALL, PBMoves::NIGHTDAZE, PBMoves::NEVERENDINGNIGHTMARE]},
		:MOVEMESSAGES => {
		"L'attaque se charge dans l'arc-en-ciel!" => [PBMoves::SILVERWIND, PBMoves::MYSTICALFIRE, 
			PBMoves::DRAGONPULSE, PBMoves::TRIATTACK, PBMoves::SACREDFIRE, PBMoves::FIREPLEDGE, 
			PBMoves::WATERPLEDGE, PBMoves::GRASSPLEDGE, PBMoves::AURORABEAM, PBMoves::JUDGMENT, 
			PBMoves::RELICSONG, PBMoves::HIDDENPOWER, PBMoves::SECRETPOWER, PBMoves::WEATHERBALL, 
			PBMoves::MISTBALL, PBMoves::HEARTSTAMP, PBMoves::MOONBLAST, PBMoves::ZENHEADBUTT, 
			PBMoves::SPARKLINGARIA, PBMoves::FLEURCANNON, PBMoves::PRISMATICLASER, PBMoves::TWINKLETACKLE,
			PBMoves::OCEANICOPERETTA, PBMoves::SOLARBEAM, PBMoves::SOLARBLADE, PBMoves::DAZZLINGGLEAM,
			PBMoves::HIDDENPOWERNOR,PBMoves::HIDDENPOWERFIR,PBMoves::HIDDENPOWERFIG,PBMoves::HIDDENPOWERWAT,PBMoves::HIDDENPOWERFLY,
			PBMoves::HIDDENPOWERGRA,PBMoves::HIDDENPOWERPOI,PBMoves::HIDDENPOWERELE,PBMoves::HIDDENPOWERGRO,PBMoves::HIDDENPOWERPSY,
			PBMoves::HIDDENPOWERROC,PBMoves::HIDDENPOWERICE,PBMoves::HIDDENPOWERBUG,PBMoves::HIDDENPOWERDRA,PBMoves::HIDDENPOWERGHO,
			PBMoves::HIDDENPOWERDAR,PBMoves::HIDDENPOWERSTE,PBMoves::HIDDENPOWERFAI],
		"L'arc-en-ciel affaiblit l'attaque..." => [PBMoves::DARKPULSE, PBMoves::SHADOWBALL, 
			PBMoves::NIGHTDAZE, PBMoves::NEVERENDINGNIGHTMARE]},
		:TYPEDAMAGEBOOST => {1.5 => [PBTypes::NORMAL]},
		:TYPEMESSAGES => {"L'arc-en-ciel énergise l'attaque!" => [PBTypes::NORMAL]},
		:TYPECONDITION => {PBTypes::NORMAL => "self.pbIsSpecial?(type)" },
		:FIELDCHANGE => {0 => [PBMoves::LIGHTTHATBURNSTHESKY]},
		:CHANGEMESSAGE => {"L'arc-en-ciel est consumé!" => [PBMoves::LIGHTTHATBURNSTHESKY]},
		:STATUSMOVEBOOST => [PBMoves::COSMICPOWER, PBMoves::MEDITATE, PBMoves::WISH],
		:CHANGEEFFECTS => {},
		:SEED => PBItems::MAGICALSEED,
		:SEEDEFFECT => PBEffects::Wish,
		:SEEDEFFECTVAL => 2,
		:SEEDEFFECTSTR => "Un vœu est fait pour {1}!",
		:SEEDANIM => PBMoves::WISH,
		:SEEDSTATS => {PBStats::SPATK => 1}
		},
	# 10 Corrosive Field
	PBFields::CORROSIVEF => {
		:FIELDNAME => "Terrain Corrosif",
		:INTROMESSAGE => "Le terrain est intoxiqué!",
		:FIELDGRAPHICS =>  "Corrosive",
		:SECRETPOWERANIM => PBMoves::ACID,
		:NATUREMOVES => PBMoves::ACIDSPRAY,
		:MIMICRY => PBTypes::POISON,
		:MOVEDAMAGEBOOST => {
		1.5 => [PBMoves::SMACKDOWN, PBMoves::MUDSLAP, PBMoves::MUDSHOT, PBMoves::MUDBOMB, 
						PBMoves::MUDDYWATER, PBMoves::WHIRLPOOL, PBMoves::THOUSANDARROWS],
		2.0 => [PBMoves::ACID, PBMoves::ACIDSPRAY, PBMoves::GRASSKNOT]},
		:MOVEACCURACYBOOST => {100 => [PBMoves::POISONPOWDER, PBMoves::SLEEPPOWDER, PBMoves::STUNSPORE, PBMoves::TOXIC]},
		:MOVEMESSAGES => {
		"La corrosion renforce l'attaque!" => [PBMoves::SMACKDOWN, PBMoves::MUDSLAP, 
			PBMoves::MUDSHOT, PBMoves::MUDBOMB, PBMoves::MUDDYWATER, PBMoves::WHIRLPOOL, PBMoves::THOUSANDARROWS,
			PBMoves::ACID, PBMoves::ACIDSPRAY, PBMoves::GRASSKNOT]},
		:MOVETYPEMOD => {
		PBTypes::POISON => [PBMoves::SMACKDOWN, PBMoves::MUDSLAP, PBMoves::MUDSHOT, 
			PBMoves::MUDDYWATER, PBMoves::WHIRLPOOL, PBMoves::MUDBOMB, PBMoves::THOUSANDARROWS]},
		:TYPETYPEMOD => {PBTypes::POISON => [PBTypes::GRASS]},
		:FIELDCHANGE => {PBFields::GRASSYT => [PBMoves::SEEDFLARE]},
		:CHANGEMESSAGE => {"Le terrain est purifié!" => [PBMoves::SEEDFLARE]},
		:STATUSMOVEBOOST => [PBMoves::ACIDARMOR, PBMoves::POISONPOWDER, PBMoves::SLEEPPOWDER, PBMoves::STUNSPORE, PBMoves::TOXIC],
		:CHANGEEFFECTS => {},
		:SEED => PBItems::TELLURICSEED,
		:SEEDEFFECT => PBEffects::BanefulBunker,
		:SEEDEFFECTVAL => true,
		:SEEDEFFECTSTR => "La Graine Tellurique protège {1}!",
		:SEEDANIM => PBMoves::BANEFULBUNKER,
		:SEEDSTATS => {}
		},
	# 11 Corrosive Mist Field
	PBFields::CORROSIVEMISTF => {
		:FIELDNAME => "Brume Corrosive",
		:INTROMESSAGE => "La brume corrosive s'installe!",
		:FIELDGRAPHICS =>  "CorrosiveMist",
		:SECRETPOWERANIM => PBMoves::ACIDSPRAY,
		:NATUREMOVES => PBMoves::VENOSHOCK,
		:MIMICRY => PBTypes::POISON,
		:MOVEDAMAGEBOOST => {
		1.5 => [PBMoves::BUBBLEBEAM, PBMoves::ACIDSPRAY, PBMoves::BUBBLE, PBMoves::SMOG, 
						PBMoves::CLEARSMOG, PBMoves::SPARKLINGARIA]},
		:MOVEACCURACYBOOST => {100 => [PBMoves::TOXIC]},
		:MOVEMESSAGES => {
		"Le poison renforce l'attaque!" => [PBMoves::BUBBLEBEAM, PBMoves::ACIDSPRAY, 
			PBMoves::BUBBLE, PBMoves::SMOG, PBMoves::CLEARSMOG, PBMoves::SPARKLINGARIA]},
		:MOVETYPEMOD => {
		PBTypes::POISON => [PBMoves::BUBBLE, PBMoves::BUBBLEBEAM,
			PBMoves::ENERGYBALL, PBMoves::SPARKLINGARIA]},
		:TYPEDAMAGEBOOST => {1.5 => [PBTypes::FIRE]},
		:TYPEMESSAGES => {"La brume toxique prend feu!" => [PBTypes::FIRE]},
		:FIELDCHANGE => {
		0 => PBFields::BLOWMOVES + PBFields::IGNITEMOVES + [PBMoves::SELFDESTRUCT, PBMoves::EXPLOSION] + [PBMoves::SEEDFLARE],
		PBFields::CORROSIVEF => [PBMoves::GRAVITY]},
		:DONTCHANGEBACKUP => [PBMoves::GRAVITY],
		:CHANGEMESSAGE => {
		#"The toxic mist combusted!" => PBFields::IGNITEMOVES + [PBMoves::SELFDESTRUCT, PBMoves::EXPLOSION],
		"Le souffle de l'attaque disperse la brume!" => PBFields::BLOWMOVES,
		"La brume est purifiée!" => [PBMoves::SEEDFLARE],
		"La brume toxique se tasse sur le sol!" => [PBMoves::GRAVITY]},
		:STATUSMOVEBOOST => [PBMoves::ACIDARMOR],
		:CHANGEEFFECTS => {},
		:SEED => PBItems::ELEMENTALSEED,
		:SEEDEFFECT => 0,
		:SEEDEFFECTVAL => 0,
		:SEEDEFFECTSTR => "{1} est gravement empoisonné(e)!",
		:SEEDANIM => 0,
		:SEEDSTATS => {PBStats::ATTACK => 1, PBStats::SPATK => 1}
		},
	# 12 Desert Field
	PBFields::DESERTF => {
		:FIELDNAME => "Désert",
		:INTROMESSAGE => "Le terrain est recouvert de sable.",
		:FIELDGRAPHICS =>  "Desert",
		:SECRETPOWERANIM => PBMoves::SANDTOMB,
		:NATUREMOVES => PBMoves::SANDTOMB,
		:MIMICRY => PBTypes::GROUND,
		:MOVEDAMAGEBOOST => {
		1.5 => [PBMoves::NEEDLEARM, PBMoves::PINMISSILE, PBMoves::DIG, PBMoves::SANDTOMB, 
						PBMoves::HEATWAVE, PBMoves::THOUSANDWAVES, PBMoves::BURNUP, PBMoves::SEARINGSUNRAZESMASH,
						PBMoves::SOLARBLADE, PBMoves::SOLARBEAM]},
		:MOVEMESSAGES => {
		"Le désert renforce l'attaque!" => [PBMoves::NEEDLEARM, PBMoves::PINMISSILE, 
			PBMoves::DIG, PBMoves::SANDTOMB, PBMoves::HEATWAVE, PBMoves::THOUSANDWAVES, 
			PBMoves::BURNUP, PBMoves::SEARINGSUNRAZESMASH, PBMoves::SOLARBLADE, PBMoves::SOLARBEAM]},
		:TYPEDAMAGEBOOST => {0.5 => [PBTypes::WATER,PBTypes::ELECTRIC]},
		:TYPEMESSAGES => {"Le désert affaiblit l'attaque..." => [PBTypes::WATER,PBTypes::ELECTRIC]},
		:TYPECONDITION => {
			PBTypes::WATER => "!attacker.isAirborne?" ,
			PBTypes::ELECTRIC => "!opponent.isAirborne?" },
		:STATUSMOVEBOOST => [PBMoves::SANDSTORM, PBMoves::SUNNYDAY, PBMoves::SANDATTACK, PBMoves::SHOREUP],
		:CHANGEEFFECTS => {},
		:SEED => PBItems::TELLURICSEED,
		:SEEDEFFECT => PBEffects::MultiTurnAttack,
		:SEEDEFFECTVAL => PBMoves::SANDTOMB,
		:SEEDEFFECTSTR => "{1} est piégé(e) dans le Tourbi-Sable!",
		:SEEDANIM => PBMoves::SANDTOMB,
		:SEEDSTATS => {PBStats::DEFENSE => 1, PBStats::SPDEF => 1, PBStats::SPEED => 1}
		},
	# 13 Icy Field
	PBFields::ICYF => {
		:FIELDNAME => "Terrain Glacé",
		:INTROMESSAGE => "Le terrain est couvert de glace.",
		:FIELDGRAPHICS =>  "Icy",
		:SECRETPOWERANIM => PBMoves::ICESHARD,
		:NATUREMOVES => PBMoves::ICEBEAM,
		:MIMICRY => PBTypes::ICE,
		:MOVEDAMAGEBOOST => { 0.5 => [PBMoves::SCALD, PBMoves::STEAMERUPTION]},
		:MOVEMESSAGES => {"The cold softened the attack..." => [PBMoves::SCALD, PBMoves::STEAMERUPTION]},
		:TYPEDAMAGEBOOST => {
		1.5 => [PBTypes::ICE],
		0.5 => [PBTypes::FIRE]},
		:TYPEMESSAGES => {
		"Le froid renforce l'attaque!" => [PBTypes::ICE],
		"Le froid affaiblit l'attaque..." => [PBTypes::FIRE]},
		:TYPETYPEMOD => {PBTypes::ICE => [PBTypes::ROCK]},
		:FIELDCHANGE => {PBFields::WATERS => PBFields::IGNITEMOVES},
		:CHANGEMESSAGE => {"La glace fond!" => PBFields::IGNITEMOVES},
		:STATUSMOVEBOOST => [PBMoves::HAIL],
		:STATUSMOVEBOOST => [PBMoves::ACIDARMOR],
		:CHANGEEFFECTS => {},
		:SEED => PBItems::ELEMENTALSEED,
		:SEEDEFFECT => 0,
		:SEEDEFFECTVAL => 0,
		:SEEDEFFECTSTR => "{1} est blessé(e) par les picots glacés!",
		:SEEDANIM => 0,
		:SEEDSTATS => {PBStats::SPEED => 2}
		},
	# 14 Rocky Field
	PBFields::ROCKYF => {
		:FIELDNAME => "Lande de Pierre",
		:INTROMESSAGE => "Le terrain est parsemé de rochers.",
		:FIELDGRAPHICS =>  "Rocky",
		:SECRETPOWERANIM => PBMoves::ROCKTHROW,
		:NATUREMOVES => PBMoves::ROCKSMASH,
		:MIMICRY => PBTypes::ROCK,
		:MOVEDAMAGEBOOST => {
		1.5 => [PBMoves::ROCKCLIMB, PBMoves::STRENGTH, PBMoves::MAGNITUDE, 
						PBMoves::EARTHQUAKE, PBMoves::BULLDOZE, PBMoves::ACCELEROCK],
		2.0 => [PBMoves::ROCKSMASH]},
		:MOVEMESSAGES => {
		"Les pierres renforcent l'attaque!" => [PBMoves::ROCKCLIMB, PBMoves::STRENGTH, 
			PBMoves::MAGNITUDE, PBMoves::EARTHQUAKE, PBMoves::BULLDOZE, PBMoves::ACCELEROCK],
		"ÉCLATÉ!" => [PBMoves::ROCKSMASH]},
		:MOVETYPEMOD => {
		PBTypes::ROCK => [PBMoves::ROCKCLIMB, PBMoves::EARTHQUAKE, PBMoves::MAGNITUDE, 
			PBMoves::STRENGTH, PBMoves::BULLDOZE]},
		:TYPEDAMAGEBOOST => {1.5 => [PBTypes::ROCK]},
		:TYPEMESSAGES => {"Le terrain renforce l'attaque!" => [PBTypes::ROCK]},
		:STATUSMOVEBOOST => [PBMoves::ROCKPOLISH],
		:CHANGEEFFECTS => {},
		:SEED => PBItems::TELLURICSEED,
		:SEEDEFFECT => 0,
		:SEEDEFFECTVAL => 0,
		:SEEDEFFECTSTR => "Des pierres pointues transpercent {1}!",
		:SEEDANIM => 0,
		:SEEDSTATS => {PBStats::DEFENSE => 1}
		},
	# 15 Forest Field
	PBFields::FORESTF => {
		:FIELDNAME => "Forêt",
		:INTROMESSAGE => "Promenons-nous dans les bois...",
		:FIELDGRAPHICS =>  "Forest",
		:SECRETPOWERANIM => PBMoves::WOODHAMMER,
		:NATUREMOVES => PBMoves::WOODHAMMER,
		:MIMICRY => PBTypes::GRASS,
		:MOVEDAMAGEBOOST => {
		0.5 => [PBMoves::SURF, PBMoves::MUDDYWATER],
		1.5 => [PBMoves::ATTACKORDER, PBMoves::ELECTROWEB, PBMoves::CUT]},
		:MOVEMESSAGES => {
		"La forêt affaiblit l'attaque..." => [PBMoves::SURF, PBMoves::MUDDYWATER],
		"Les abeilles surgissent du bois!" => [PBMoves::ATTACKORDER],
		"La mousse des arbres renforce l'attaque!" => [PBMoves::ELECTROWEB],
		"La cible est taillée à ras!" => [PBMoves::CUT]},
		:TYPEDAMAGEBOOST => {1.5 => [PBTypes::BUG,PBTypes::GRASS]},
		:TYPEMESSAGES => {
		"Le terrain renforce l'attaque!" => [PBTypes::BUG],
		"La sylve renforce l'attaque!" => [PBTypes::GRASS]},
		:TYPECONDITION => {PBTypes::BUG => "self.pbIsSpecial?(type)" },
		:FIELDCHANGE => {PBFields::BURNINGF => PBFields::IGNITEMOVES},
		:DONTCHANGEBACKUP => PBFields::IGNITEMOVES,
		:CHANGEMESSAGE => {"La forêt prend feu!" => PBFields::IGNITEMOVES},
		:CHANGECONDITION => {PBFields::BURNINGF => "ignitecheck"},
		:STATUSMOVEBOOST => [PBMoves::STICKYWEB, PBMoves::DEFENDORDER, PBMoves::GROWTH,
		 	PBMoves::STRENGTHSAP, PBMoves::HEALORDER, PBMoves::NATURESMADNESS, PBMoves::FORESTSCURSE],
		:CHANGEEFFECTS => {},
		:SEED => PBItems::TELLURICSEED,
		:SEEDEFFECT => PBEffects::SpikyShield,
		:SEEDEFFECTVAL => true,
		:SEEDEFFECTSTR => "La Graine Tellurique protège {1} contre les dégâts!",
		:SEEDANIM => PBMoves::SPIKYSHIELD,
		:SEEDSTATS => {}
		},
	# 16 Superheated Field
	PBFields::SUPERHEATEDF => {
		:FIELDNAME => "Terrain Surchauffé",
		:INTROMESSAGE => "Le terrain est surchauffé!",
		:FIELDGRAPHICS =>  "Superheated",
		:SECRETPOWERANIM => PBMoves::FLAMEBURST,
		:NATUREMOVES => PBMoves::HEATWAVE,
		:MIMICRY => PBTypes::FIRE,
		:MOVEDAMAGEBOOST => {
		0.625 => [PBMoves::SURF, PBMoves::MUDDYWATER, PBMoves::WATERPLEDGE, 
							PBMoves::WATERSPOUT, PBMoves::SPARKLINGARIA, PBMoves::HYDROVORTEX, PBMoves::OCEANICOPERETTA],
		1.667 => [PBMoves::SCALD, PBMoves::STEAMERUPTION]},
		:MOVEMESSAGES => {
		#"cass couldn't find this message. make ame fix it." => [PBMoves::SURF, PBMoves::MUDDYWATER, PBMoves::WATERPLEDGE, 
		#		PBMoves::WATERSPOUT, PBMoves::SPARKLINGARIA, PBMoves::HYDROVORTEX, PBMoves::OCEANICOPERETTA],
		#This message is handled elsewhere, "Steam shot up from the field!"
		"Le terrain surchauffe l'attaque!" => [PBMoves::SCALD, PBMoves::STEAMERUPTION]},
		:TYPEDAMAGEBOOST => {
		0.5 => [PBTypes::ICE],
		0.9 => [PBTypes::WATER],
		1.1 => [PBTypes::FIRE]},
		:TYPEMESSAGES => {
		"La chaleur extrême affaiblit l'attaque..." => [PBTypes::ICE,PBTypes::WATER],
		"L'attaque est surchauffée!" => [PBTypes::FIRE]},
		:FIELDCHANGE => {
		PBFields::BURNINGF => PBFields::IGNITEMOVES + [PBMoves::SELFDESTRUCT, PBMoves::EXPLOSION],
		0 => [PBMoves::BLIZZARD, PBMoves::GLACIATE, PBMoves::SUBZEROSLAMMER]},
		:DONTCHANGEBACKUP => PBFields::IGNITEMOVES + [PBMoves::SELFDESTRUCT, PBMoves::EXPLOSION],
		:CHANGEMESSAGE => {
		"Le terrain prend feu!" => PBFields::IGNITEMOVES + [PBMoves::SELFDESTRUCT, PBMoves::EXPLOSION],
		"Le terrain refroidit!"=> [PBMoves::BLIZZARD, PBMoves::GLACIATE, PBMoves::SUBZEROSLAMMER]},
		:CHANGECONDITION => {PBFields::BURNINGF => "ignitecheck"},
		:STATUSMOVEBOOST => [],
		:CHANGEEFFECTS => {},
		:SEED => PBItems::TELLURICSEED,
		:SEEDEFFECT => PBEffects::ShellTrap,
		:SEEDEFFECTVAL => true,
		:SEEDEFFECTSTR => "{1} déclenche le Carapiège!",
		:SEEDANIM => PBMoves::SHELLTRAP,
		:SEEDSTATS => {PBStats::DEFENSE => 1}
		},
	# 17 Factory Field
	PBFields::FACTORYF => {
		:FIELDNAME => "Terraindustriel",
		:INTROMESSAGE => "Des machines tournent en fond.",
		:FIELDGRAPHICS =>  "Factory",
		:SECRETPOWERANIM => PBMoves::MAGNETBOMB,
		:NATUREMOVES => PBMoves::GEARGRIND,
		:MIMICRY => PBTypes::STEEL,
		:MOVEDAMAGEBOOST => {
		1.5 => [PBMoves::STEAMROLLER, PBMoves::TECHNOBLAST],
		2.0 => [PBMoves::FLASHCANNON, PBMoves::GYROBALL, PBMoves::MAGNETBOMB, PBMoves::GEARGRIND]},
		:MOVEMESSAGES => {
		"MISE À JOUR DE SÉQUENCE D'ATTAQUE." => [PBMoves::STEAMROLLER, PBMoves::TECHNOBLAST],
		"SÉQUENCE D'ATTAQUE INITIÉE." => [PBMoves::FLASHCANNON, PBMoves::GYROBALL, 
			PBMoves::MAGNETBOMB, PBMoves::GEARGRIND]},
		:TYPEDAMAGEBOOST => {1.5 => [PBTypes::ELECTRIC]},
		:TYPEMESSAGES => {"Le terrain énergise l'attaque!" => [PBTypes::ELECTRIC]},
		:FIELDCHANGE => {
		PBFields::SHORTCIRCUITF => PBFields::QUAKEMOVES + [PBMoves::SELFDESTRUCT, PBMoves::EXPLOSION, PBMoves::LIGHTTHATBURNSTHESKY]},
		:CHANGEMESSAGE => {
		"Le terrain est détruit!" => PBFields::QUAKEMOVES + [PBMoves::SELFDESTRUCT, PBMoves::EXPLOSION],
		"Toute la lumière est consumée!" => [PBMoves::LIGHTTHATBURNSTHESKY]},
		:STATUSMOVEBOOST => [PBMoves::AUTOTOMIZE, PBMoves::IRONDEFENSE, PBMoves::METALSOUND, PBMoves::SHIFTGEAR, PBMoves::MAGNETRISE, PBMoves::GEARUP],
		:CHANGEEFFECTS => {},
		:SEED => PBItems::SYNTHETICSEED,
		:SEEDEFFECT => PBEffects::LaserFocus,
		:SEEDEFFECTVAL => 1,
		:SEEDEFFECTSTR => "{1} aiguise son esprit!",
		:SEEDANIM => PBMoves::LASERFOCUS,
		:SEEDSTATS => {PBStats::SPATK => 1}
		},
	# 18 Short-Circuit Field
	PBFields::SHORTCIRCUITF => {
		:FIELDNAME => "Terrain Déchargé",
		:INTROMESSAGE => "Bzzt!",
		:FIELDGRAPHICS =>  "Shortcircuit",
		:SECRETPOWERANIM => PBMoves::ELECTROBALL,
		:NATUREMOVES => PBMoves::DISCHARGE,
		:MIMICRY => PBTypes::ELECTRIC,
		:MOVEDAMAGEBOOST => {
		1.5 => [PBMoves::DAZZLINGGLEAM, PBMoves::SURF, PBMoves::MUDDYWATER, PBMoves::MAGNETBOMB,
						PBMoves::GYROBALL, PBMoves::FLASHCANNON, PBMoves::GEARGRIND, PBMoves::HYDROVORTEX],
		1.3 => [PBMoves::DARKPULSE, PBMoves::NIGHTDAZE, PBMoves::NIGHTSLASH, 
						PBMoves::SHADOWBALL, PBMoves::SHADOWPUNCH, PBMoves::SHADOWCLAW,
						PBMoves::SHADOWSNEAK, PBMoves::SHADOWFORCE, PBMoves::SHADOWBONE],
		0.5 => [PBMoves::LIGHTTHATBURNSTHESKY]},
		:MOVEACCURACYBOOST => {80 => [PBMoves::ZAPCANNON]},
		:MOVEMESSAGES => {
		"Aveuglant!" => [PBMoves::DAZZLINGGLEAM], 
		"L'attaque amasse de l'électricité!" => [PBMoves::SURF, PBMoves::MUDDYWATER, 
			PBMoves::MAGNETBOMB, PBMoves::GYROBALL, PBMoves::FLASHCANNON, PBMoves::GEARGRIND, PBMoves::HYDROVORTEX],
		"L'obscurité renforce l'attaque!" => [PBMoves::DARKPULSE, PBMoves::NIGHTDAZE, 
			PBMoves::NIGHTSLASH, PBMoves::SHADOWBALL, PBMoves::SHADOWPUNCH, PBMoves::SHADOWCLAW, 
			PBMoves::SHADOWSNEAK, PBMoves::SHADOWFORCE, PBMoves::SHADOWBONE],
		"{1} n'a presque pas de lumière à consumer..." => [PBMoves::LIGHTTHATBURNSTHESKY]},
		:MOVETYPEMOD => {
		PBTypes::ELECTRIC => [PBMoves::SURF, PBMoves::MUDDYWATER, PBMoves::MAGNETBOMB, 
			PBMoves::GYROBALL, PBMoves::FLASHCANNON, PBMoves::GEARGRIND]},
		:FIELDCHANGE => {PBFields::FACTORYF => [PBMoves::PARABOLICCHARGE, PBMoves::WILDCHARGE,
											PBMoves::CHARGEBEAM, PBMoves::IONDELUGE, PBMoves::GIGAVOLTHAVOC]},
		:CHANGEMESSAGE => {"SYSTÈME EN LIGNE." => [PBMoves::PARABOLICCHARGE, PBMoves::WILDCHARGE, 
												PBMoves::CHARGEBEAM, PBMoves::IONDELUGE, PBMoves::GIGAVOLTHAVOC]},
		:STATUSMOVEBOOST => [PBMoves::FLASH, PBMoves::METALSOUND, PBMoves::MAGNETRISE],
		:CHANGEEFFECTS => {},
		:SEED => PBItems::SYNTHETICSEED,
		:SEEDEFFECT => PBEffects::MagnetRise,
		:SEEDEFFECTVAL => 5,
		:SEEDEFFECTSTR => "{1} lévite sur un champ magnétique!",
		:SEEDANIM => PBMoves::MAGNETRISE,
		:SEEDSTATS => {PBStats::SPDEF => 1}
		},
	# 19 Wasteland
	PBFields::WASTELAND => {
		:FIELDNAME => "Crassier",
		:INTROMESSAGE => "La crasse vous entoure...",
		:FIELDGRAPHICS =>  "Wasteland",
		:SECRETPOWERANIM => PBMoves::GUNKSHOT,
		:NATUREMOVES => PBMoves::GUNKSHOT,
		:MIMICRY => PBTypes::POISON,
		:MOVEDAMAGEBOOST => {
		1.5 => [PBMoves::VINEWHIP, PBMoves::POWERWHIP, PBMoves::MUDSLAP, 
						PBMoves::MUDBOMB, PBMoves::MUDSHOT],
		0.25 => [PBMoves::EARTHQUAKE, PBMoves::MAGNITUDE, PBMoves::BULLDOZE],
		2.0 => [PBMoves::SPITUP],
		1.2 => [PBMoves::OCTAZOOKA, PBMoves::SLUDGE, PBMoves::GUNKSHOT, 
						PBMoves::SLUDGEWAVE, PBMoves::SLUDGEBOMB]},
		:MOVEMESSAGES => {
		"La liane est pleine de crasse!" => [PBMoves::VINEWHIP, PBMoves::POWERWHIP], 
		"La boue est remplie de crasse!" => [PBMoves::MUDSLAP, PBMoves::MUDBOMB, PBMoves::MUDSHOT],
		"Blib blib blub blub blob..." => [PBMoves::EARTHQUAKE, PBMoves::MAGNITUDE, PBMoves::BULLDOZE],
		"BLEUUAARGGGH!" => [PBMoves::SPITUP],
		"La crasse se joint à l'attaque!" => [PBMoves::OCTAZOOKA, PBMoves::SLUDGE, PBMoves::GUNKSHOT, 
			PBMoves::SLUDGEWAVE, PBMoves::SLUDGEBOMB]},
		:MOVETYPEMOD => {
		PBTypes::POISON => [PBMoves::MUDBOMB, PBMoves::MUDSLAP, PBMoves::MUDSHOT]},
		:STATUSMOVEBOOST => [PBMoves::SWALLOW],
		:CHANGEEFFECTS => {},
		:SEED => PBItems::TELLURICSEED,
		:SEEDEFFECT => 0,
		:SEEDEFFECTVAL => 0,
		:SEEDEFFECTSTR => "",
		:SEEDANIM => 0,
		:SEEDSTATS => {PBStats::ATTACK => 1, PBStats::SPATK => 1}
		},
	# 20 Ashen Beach
	PBFields::ASHENB => {
		:FIELDNAME => "Plage de Cendres",
		:INTROMESSAGE => "Sable et cendres tapissent le sol.",
		:FIELDGRAPHICS =>  "AshenBeach",
		:SECRETPOWERANIM => PBMoves::MUDSHOT,
		:NATUREMOVES => PBMoves::MEDITATE,
		:MIMICRY => PBTypes::GROUND,
		:MOVEDAMAGEBOOST => {
		1.5 => [PBMoves::HIDDENPOWER, PBMoves::STRENGTH, PBMoves::LANDSWRATH, 
						PBMoves::THOUSANDWAVES, PBMoves::SURF, PBMoves::MUDDYWATER, PBMoves::CLANGOROUSSOULBLAZE,
						PBMoves::HIDDENPOWERNOR,PBMoves::HIDDENPOWERFIR,PBMoves::HIDDENPOWERFIG,PBMoves::HIDDENPOWERWAT,PBMoves::HIDDENPOWERFLY,
						PBMoves::HIDDENPOWERGRA,PBMoves::HIDDENPOWERPOI,PBMoves::HIDDENPOWERELE,PBMoves::HIDDENPOWERGRO,PBMoves::HIDDENPOWERPSY,
						PBMoves::HIDDENPOWERROC,PBMoves::HIDDENPOWERICE,PBMoves::HIDDENPOWERBUG,PBMoves::HIDDENPOWERDRA,PBMoves::HIDDENPOWERGHO,
						PBMoves::HIDDENPOWERDAR,PBMoves::HIDDENPOWERSTE,PBMoves::HIDDENPOWERFAI],
		2.0 => [PBMoves::MUDSLAP, PBMoves::MUDSHOT, PBMoves::MUDBOMB , PBMoves::SANDTOMB],
		1.3 => [PBMoves::STOREDPOWER, PBMoves::ZENHEADBUTT, 
						PBMoves::FOCUSBLAST, PBMoves::AURASPHERE],
		1.2 => [PBMoves::PSYCHIC]},
		:MOVEACCURACYBOOST => {90 => [PBMoves::FOCUSBLAST]},
		:MOVEMESSAGES => {
		"...Avec une concentration intense!" => [PBMoves::HIDDENPOWER, PBMoves::STRENGTH, PBMoves::CLANGOROUSSOULBLAZE,
		PBMoves::HIDDENPOWERNOR,PBMoves::HIDDENPOWERFIR,PBMoves::HIDDENPOWERFIG,PBMoves::HIDDENPOWERWAT,PBMoves::HIDDENPOWERFLY,
		PBMoves::HIDDENPOWERGRA,PBMoves::HIDDENPOWERPOI,PBMoves::HIDDENPOWERELE,PBMoves::HIDDENPOWERGRO,PBMoves::HIDDENPOWERPSY,
		PBMoves::HIDDENPOWERROC,PBMoves::HIDDENPOWERICE,PBMoves::HIDDENPOWERBUG,PBMoves::HIDDENPOWERDRA,PBMoves::HIDDENPOWERGHO,
		PBMoves::HIDDENPOWERDAR,PBMoves::HIDDENPOWERSTE,PBMoves::HIDDENPOWERFAI], 
		"Le sable renforce l'attaque!" => [PBMoves::LANDSWRATH, PBMoves::THOUSANDWAVES], 
		"On va surfer!" => [PBMoves::SURF, PBMoves::MUDDYWATER],
		"La cendre se mélange à l'attaque!" => [PBMoves::MUDSLAP, PBMoves::MUDSHOT, PBMoves::MUDBOMB , PBMoves::SANDTOMB],
		"...Avec une concentration totale!" => [PBMoves::STOREDPOWER, PBMoves::ZENHEADBUTT, 
			PBMoves::FOCUSBLAST, PBMoves::AURASPHERE],
		"...Avec concentration...!" => [PBMoves::PSYCHIC]},
		:MOVETYPEMOD => {PBTypes::PSYCHIC => [PBMoves::STRENGTH]},
		:STATUSMOVEBOOST => [PBMoves::CALMMIND, PBMoves::KINESIS, PBMoves::MEDITATE, PBMoves::SANDATTACK,
			PBMoves::SANDSTORM, PBMoves::FOCUSENERGY, PBMoves::SHOREUP],
		:CHANGEEFFECTS => {},
		:SEED => PBItems::TELLURICSEED,
		:SEEDEFFECT => PBEffects::FocusEnergy,
		:SEEDEFFECTVAL => 3,
		:SEEDEFFECTSTR => "{1} se gonfle grâce à la Graine Tellurique!",
		:SEEDANIM => PBMoves::FOCUSENERGY,
		:SEEDSTATS => {}
		},
	# 21 Water Surface
	PBFields::WATERS => {
		:FIELDNAME => "Surface de l'Eau",
		:INTROMESSAGE => "La surface de l'eau est calme.",
		:FIELDGRAPHICS =>  "WaterSurface",
		:SECRETPOWERANIM => PBMoves::AQUAJET,
		:NATUREMOVES => PBMoves::WHIRLPOOL,
		:MIMICRY => PBTypes::WATER,
		:MOVEDAMAGEBOOST => {
			1.5 => [PBMoves::SURF, PBMoves::MUDDYWATER, PBMoves::WHIRLPOOL, PBMoves::DIVE, PBMoves::HYDROVORTEX]},
		:MOVEMESSAGES => {
			"L'attaque chevauche le courant!" => [PBMoves::SURF, PBMoves::MUDDYWATER, 
				PBMoves::WHIRLPOOL, PBMoves::DIVE, PBMoves::HYDROVORTEX]},
		:TYPEDAMAGEBOOST => {
			1.5 => [PBTypes::WATER,PBTypes::ELECTRIC],
			0.5 => [PBTypes::FIRE]},
		:TYPEMESSAGES => {
			"L'eau conduit l'attaque!" => [PBTypes::ELECTRIC],
			"L'eau renforce l'attaque!" => [PBTypes::WATER],
			"L'eau détrempe l'attaque..." => [PBTypes::FIRE]},
		:TYPECONDITION => {
			PBTypes::FIRE => "!opponent.isAirborne?" ,
			PBTypes::ELECTRIC => "!opponent.isAirborne?" },
		:FIELDCHANGE => {
			PBFields::UNDERWATER => [PBMoves::GRAVITY,PBMoves::DIVE],
			PBFields::ICYF => [PBMoves::BLIZZARD, PBMoves::GLACIATE, PBMoves::SUBZEROSLAMMER]},
		:DONTCHANGEBACKUP => [PBMoves::BLIZZARD, PBMoves::GLACIATE, PBMoves::SUBZEROSLAMMER],
		:CHANGEMESSAGE => {
			"Le combat s'enfonce dans les profondeurs!" => [PBMoves::GRAVITY],
			"Le combat est plongé sous l'eau!" => [PBMoves::DIVE],
			"La surface de l'eau est gelée!" => [PBMoves::BLIZZARD, PBMoves::GLACIATE, PBMoves::SUBZEROSLAMMER]},
		:STATUSMOVEBOOST => [PBMoves::SPLASH, PBMoves::AQUARING],
		:CHANGEEFFECTS => {},
		:SEED => PBItems::ELEMENTALSEED,
		:SEEDEFFECT => PBEffects::AquaRing,
		:SEEDEFFECTVAL => true,
		:SEEDEFFECTSTR => "{1} s'entoure d'un voile d'eau!",
		:SEEDANIM => PBMoves::AQUARING,
		:SEEDSTATS => {PBStats::SPDEF => 1}
		},
	# 22 Underwater
	PBFields::UNDERWATER => {
		:FIELDNAME => "Sous l'Eau",
		:INTROMESSAGE => "Blub blub...",
		:FIELDGRAPHICS =>  "Underwater",
		:SECRETPOWERANIM => PBMoves::AQUATAIL,
		:NATUREMOVES => PBMoves::WATERPULSE,
		:MIMICRY => PBTypes::WATER,
		:MOVEDAMAGEBOOST => {
		1.5 => [PBMoves::WATERPULSE],
		2.0 => [PBMoves::ANCHORSHOT]},
		:MOVEMESSAGES => {
			"Toute l'eau vibre!" => [PBMoves::WATERPULSE],
			"Des profondeurs!" => [PBMoves::ANCHORSHOT]},
		:TYPETYPEMOD => {PBTypes::WATER => [PBTypes::GROUND]},
		:TYPEDAMAGEBOOST => {
		1.5 => [PBTypes::WATER],
		2.0 => [PBTypes::ELECTRIC]},
		:TYPEMESSAGES => {
		"L'eau renforce l'attaque!" => [PBTypes::WATER],
		"L'eau superconduit l'attaque!" => [PBTypes::ELECTRIC]},
		:FIELDCHANGE => {PBFields::WATERS => [PBMoves::DIVE, PBMoves::SKYDROP, PBMoves::FLY, PBMoves::BOUNCE]},
		:CHANGEMESSAGE => {"Le combat remonte en surface!" => [PBMoves::DIVE, 
			PBMoves::SKYDROP, PBMoves::FLY, PBMoves::BOUNCE]},
		:STATUSMOVEBOOST => [PBMoves::AQUARING],
		:CHANGEEFFECTS => {},
		:SEED => PBItems::ELEMENTALSEED,
		:SEEDEFFECT => 0,
		:SEEDEFFECTVAL => 0,
		:SEEDEFFECTSTR => "{1} devient de type Eau!",
		:SEEDANIM => PBMoves::SOAK,
		:SEEDSTATS => {PBStats::SPEED => 1}
		},
	# 23 Cave
	PBFields::CAVE => {
		:FIELDNAME => "Caverne",
		:INTROMESSAGE => "La caverne résonne...",
		:FIELDGRAPHICS =>  "Cave",
		:SECRETPOWERANIM => PBMoves::ROCKWRECKER,
		:NATUREMOVES => PBMoves::ROCKTOMB,
		:MIMICRY => PBTypes::ROCK,
		:MOVEDAMAGEBOOST => {1.5 => [PBMoves::ROCKTOMB]},
		:MOVEMESSAGES => {"...Empilé!" => [PBMoves::ROCKTOMB]},
		:TYPEDAMAGEBOOST => {
			1.5 => [PBTypes::ROCK],
			0.5 => [PBTypes::FLYING]},
		:TYPEMESSAGES => {
		"La caverne étouffe le courant d'air!" => [PBTypes::FLYING],
		"La caverne renforce l'attaque!" => [PBTypes::ROCK]},
		:TYPECONDITION => {PBTypes::FLYING => "!self.isContactMove?" },
		:FIELDCHANGE => {
			PBFields::CRYSTALC => [PBMoves::POWERGEM, PBMoves::DIAMONDSTORM],
			PBFields::CAVE => PBFields::QUAKEMOVES + [PBMoves::CONTINENTALCRUSH]},
		:DONTCHANGEBACKUP => [PBMoves::POWERGEM, PBMoves::DIAMONDSTORM],
		:CHANGEMESSAGE => {"La caverne est parsemée de cristaux!" => [PBMoves::POWERGEM, PBMoves::DIAMONDSTORM]},
		:CHANGECONDITION => {},
		:STATUSMOVEBOOST => [PBMoves::STEALTHROCK],
		:CHANGEEFFECTS => {},
		:SEED => PBItems::TELLURICSEED,
		:SEEDEFFECT => 0,
		:SEEDEFFECTVAL => 0,
		:SEEDEFFECTSTR => "Des pierres pointues transpercent {1}!",
		:SEEDANIM => 0,
		:SEEDSTATS => {PBStats::DEFENSE => 2}
		},
	# 24 Glitch Field
	PBFields::GLITCHF => {
		:FIELDNAME => "Glitch Field",
		:INTROMESSAGE => "1n!taliz3 .b//////attl3",
		:FIELDGRAPHICS =>  "Glitch",
		:SECRETPOWERANIM => PBMoves::TECHNOBLAST,
		:NATUREMOVES => PBMoves::METRONOME,
		:MIMICRY => PBTypes::QMARKS,
		:MOVEDAMAGEBOOST => {},
		:MOVEACCURACYBOOST => {90 => [PBMoves::BLIZZARD]},
		:MOVEMESSAGES => {},
		:TYPEDAMAGEBOOST => {1.2 => [PBTypes::PSYCHIC]},
		:TYPEMESSAGES => {".0P pl$ nerf!-//" => [PBTypes::PSYCHIC]},
		:STATUSMOVEBOOST => [],
		:CHANGEEFFECTS => {},
		:SEED => PBItems::SYNTHETICSEED,
		:SEEDEFFECT => 0,
		:SEEDEFFECTVAL => 0,
		:SEEDEFFECTSTR => "{1}.TYPE = (PBTypes::QMARKS)",
		:SEEDANIM => PBMoves::AMNESIA,
		:SEEDSTATS => {PBStats::DEFENSE => 1}
		},
	# 25 Crystal Cavern
	PBFields::CRYSTALC => {
		:FIELDNAME => "Caverne de Cristaux",
		:INTROMESSAGE => "La caverne est jonchée de cristaux.",
		:FIELDGRAPHICS =>  "CrystalCavern",
		:SECRETPOWERANIM => PBMoves::POWERGEM,
		:NATUREMOVES => PBMoves::POWERGEM,
		:MIMICRY => PBTypes::QMARKS, #RNG
		:MOVEDAMAGEBOOST => {
		1.3 => [PBMoves::AURORABEAM, PBMoves::SIGNALBEAM, PBMoves::FLASHCANNON, 
						PBMoves::LUSTERPURGE, PBMoves::DAZZLINGGLEAM, PBMoves::MIRRORSHOT, 
						PBMoves::TECHNOBLAST, PBMoves::DOOMDUMMY, PBMoves::MOONGEISTBEAM, 
						PBMoves::PHOTONGEYSER, PBMoves::MENACINGMOONRAZEMAELSTROM],
		1.5 => [PBMoves::POWERGEM, PBMoves::DIAMONDSTORM, PBMoves::ANCIENTPOWER, 
						PBMoves::JUDGMENT, PBMoves::ROCKSMASH, PBMoves::ROCKTOMB, PBMoves::STRENGTH, 
						PBMoves::ROCKCLIMB, PBMoves::MULTIATTACK]},
		:MOVEMESSAGES => {
		"La lumière des cristaux renforce l'attaque!" => [PBMoves::AURORABEAM, 
			PBMoves::SIGNALBEAM, PBMoves::FLASHCANNON, PBMoves::LUSTERPURGE, 
			PBMoves::DAZZLINGGLEAM, PBMoves::MIRRORSHOT, PBMoves::TECHNOBLAST, 
			PBMoves::DOOMDUMMY, PBMoves::MOONGEISTBEAM, PBMoves::PHOTONGEYSER,
			PBMoves::MENACINGMOONRAZEMAELSTROM],
		"Les cristaux renforcent l'attaque!" => [PBMoves::POWERGEM, PBMoves::DIAMONDSTORM, 
			PBMoves::ANCIENTPOWER, PBMoves::JUDGMENT, PBMoves::ROCKSMASH, PBMoves::ROCKTOMB, 
			PBMoves::STRENGTH, PBMoves::ROCKCLIMB, PBMoves::MULTIATTACK]},
		:TYPEDAMAGEBOOST => {1.5 => [PBTypes::ROCK,PBTypes::DRAGON]},
		:TYPEMESSAGES => {
			"Les cristaux chargent l'attaque!" => [PBTypes::ROCK],
			"L'énergie cristalline renforce l'attaque!" => [PBTypes::DRAGON]},
		:FIELDCHANGE => {
			PBFields::CAVE => PBFields::QUAKEMOVES,
			PBFields::DARKCRYSTALC => [PBMoves::DARKPULSE, PBMoves::DARKVOID, PBMoves::NIGHTDAZE, PBMoves::LIGHTTHATBURNSTHESKY]},
		:DONTCHANGEBACKUP => PBFields::QUAKEMOVES + [PBMoves::DARKPULSE, PBMoves::DARKVOID, PBMoves::NIGHTDAZE],
		:CHANGEMESSAGE => {
			"Les cristaux se brisent!" => PBFields::QUAKEMOVES,
			"La lumière des cristaux est engloutie dans l'obscurité!" => [PBMoves::DARKPULSE, 
				PBMoves::DARKVOID, PBMoves::NIGHTDAZE],
			"La lumière des cristaux est consumée!" => [PBMoves::LIGHTTHATBURNSTHESKY]},
		:STATUSMOVEBOOST => [PBMoves::ROCKPOLISH, PBMoves::STEALTHROCK],
		:CHANGEEFFECTS => {},
		:SEED => PBItems::MAGICALSEED,
		:SEEDEFFECT => PBEffects::MagicCoat,
		:SEEDEFFECTVAL => true,
		:SEEDEFFECTSTR => "{1} s'entoure du Reflet Magik!",
		:SEEDANIM => PBMoves::MAGICCOAT,
		:SEEDSTATS => {PBStats::SPATK => 1}
		},
	# 26 Murkwater Surface
	PBFields::MURKWATERS => {
		:FIELDNAME => "Eau Polluée",
		:INTROMESSAGE => "L'eau est souillée...",
		:FIELDGRAPHICS =>  "MurkwaterSurface",
		:SECRETPOWERANIM => PBMoves::SLUDGEBOMB,
		:NATUREMOVES => PBMoves::SLUDGEWAVE,
		:MIMICRY => PBTypes::POISON,
		:MOVEDAMAGEBOOST => {
		1.5 => [PBMoves::MUDBOMB, PBMoves::MUDSLAP, PBMoves::MUDSHOT, PBMoves::SMACKDOWN, 
						PBMoves::ACID, PBMoves::ACIDSPRAY, PBMoves::BRINE, PBMoves::THOUSANDWAVES]},
		:MOVEMESSAGES => {
		"L'eau toxique renforce l'attaque!" => [PBMoves::MUDBOMB, PBMoves::MUDSLAP, 
			PBMoves::MUDSHOT, PBMoves::SMACKDOWN, PBMoves::ACID, PBMoves::ACIDSPRAY, PBMoves::THOUSANDWAVES],
		"Ça brûle!" => [PBMoves::BRINE]},
		:MOVETYPEMOD => {
		PBTypes::POISON => [PBMoves::MUDBOMB, PBMoves::MUDSLAP, PBMoves::MUDSHOT, 
												PBMoves::SMACKDOWN, PBMoves::THOUSANDWAVES],
		PBTypes::WATER => [PBMoves::SLUDGEWAVE]},
		:TYPETYPEMOD => {PBTypes::POISON => [PBTypes::WATER]},
		:TYPEDAMAGEBOOST => {
			1.5 => [PBTypes::WATER,PBTypes::POISON],
			1.3 => [PBTypes::ELECTRIC],
		},
		:TYPEMESSAGES => {
		"L'eau toxique renforce l'attaque!" => [PBTypes::WATER,PBTypes::POISON],
		"L'eau toxique conduit l'attaque!" => [PBTypes::ELECTRIC]},
		:TYPECONDITION => {
			PBTypes::ELECTRIC => "!opponent.isAirborne?",
		},
		:FIELDCHANGE => {
		PBFields::WATERS => [PBMoves::WHIRLPOOL],
		PBFields::ICYF => [PBMoves::BLIZZARD, PBMoves::GLACIATE,PBMoves::SUBZEROSLAMMER]},
		:DONTCHANGEBACKUP => [PBMoves::WHIRLPOOL,PBMoves::BLIZZARD, PBMoves::GLACIATE,PBMoves::SUBZEROSLAMMER],
		:CHANGEMESSAGE => {
		"Le tourbillon nettoie l'eau souillée!" => [PBMoves::WHIRLPOOL],
		"L'eau toxique gèle!" => [PBMoves::BLIZZARD, PBMoves::GLACIATE,PBMoves::SUBZEROSLAMMER]},
		:STATUSMOVEBOOST => [PBMoves::ACIDARMOR],
		:CHANGEEFFECTS => {},
		:SEED => PBItems::ELEMENTALSEED,
		:SEEDEFFECT => PBEffects::AquaRing,
		:SEEDEFFECTVAL => true,
		:SEEDEFFECTSTR => "{1} s'entoure d'un voile d'eau!",
		:SEEDANIM => PBMoves::AQUARING,
		:SEEDSTATS => {PBStats::SPEED => 1}
		},
	# 27 Mountain
	PBFields::MOUNTAIN => {
		:FIELDNAME => "Montagne",
		:INTROMESSAGE => ["Pourtant, que la montagne est belle..."], #oh good, i hate spleen
		:FIELDGRAPHICS =>  "Mountain",
		:SECRETPOWERANIM => PBMoves::ROCKBLAST,
		:NATUREMOVES => PBMoves::ROCKSLIDE,
		:MIMICRY => PBTypes::ROCK,
		:MOVEDAMAGEBOOST => {
		1.5 => [PBMoves::VITALTHROW, PBMoves::CIRCLETHROW, PBMoves::STORMTHROW, 
						PBMoves::OMINOUSWIND, PBMoves::ICYWIND, PBMoves::SILVERWIND, PBMoves::TWISTER, 
						PBMoves::RAZORWIND, PBMoves::FAIRYWIND, PBMoves::THUNDER, PBMoves::ERUPTION, 
						PBMoves::AVALANCHE, PBMoves::HYPERVOICE]},
		:MOVEMESSAGES => {
		"{1} est projeté en contrebas!" => [PBMoves::VITALTHROW, 
			PBMoves::CIRCLETHROW, PBMoves::STORMTHROW],
		"Le vent renforce l'attaque!" => [PBMoves::OMINOUSWIND, PBMoves::ICYWIND, 
			PBMoves::SILVERWIND, PBMoves::TWISTER, PBMoves::RAZORWIND, PBMoves::FAIRYWIND], 
		"La montagne renforce l'attaque!" => [PBMoves::THUNDER, 
			PBMoves::ERUPTION, PBMoves::AVALANCHE],
		"Yodelahihouu~" => [PBMoves::HYPERVOICE]},
		:TYPEDAMAGEBOOST => {1.5 => [PBTypes::ROCK,PBTypes::FLYING]},
		:TYPEMESSAGES => {
		"La montagne renforce l'attaque!" => [PBTypes::ROCK],
		"Le grand air renforce l'attaque!" => [PBTypes::FLYING]},
		:FIELDCHANGE => {PBFields::SNOWYM => [PBMoves::BLIZZARD, PBMoves::GLACIATE,PBMoves::SUBZEROSLAMMER]},
		:DONTCHANGEBACKUP => [PBMoves::BLIZZARD, PBMoves::GLACIATE,PBMoves::SUBZEROSLAMMER],
		:CHANGEMESSAGE => {"La montagne se couvre de neige!" => [PBMoves::BLIZZARD, PBMoves::GLACIATE,PBMoves::SUBZEROSLAMMER]},
		:STATUSMOVEBOOST => [PBMoves::TAILWIND, PBMoves::SUNNYDAY],
		:CHANGEEFFECTS => {},
		:SEED => PBItems::TELLURICSEED,
		:SEEDEFFECT => 0,
		:SEEDEFFECTVAL => 0,
		:SEEDEFFECTSTR => "",
		:SEEDANIM => 0,
		:SEEDSTATS => {PBStats::ATTACK => 2, PBStats::ACCURACY => -1}
		},
	# 28 Snowy Mountain
	PBFields::SNOWYM => {
		:FIELDNAME => "Montagne Enneigée",
		:INTROMESSAGE => "L'hiver s'installe doucement sur la montagne...",
		:FIELDGRAPHICS =>  "SnowyMountain",
		:SECRETPOWERANIM => PBMoves::ICEBALL,
		:NATUREMOVES => PBMoves::AVALANCHE,
		:MIMICRY => PBTypes::ICE,
		:MOVEDAMAGEBOOST => {
		1.5 => [PBMoves::VITALTHROW, PBMoves::CIRCLETHROW, PBMoves::STORMTHROW, 
						PBMoves::OMINOUSWIND, PBMoves::SILVERWIND, PBMoves::TWISTER, PBMoves::RAZORWIND, 
						PBMoves::FAIRYWIND, PBMoves::AVALANCHE, PBMoves::POWDERSNOW, PBMoves::HYPERVOICE,
						PBMoves::GLACIATE],
		0.5 => [PBMoves::SCALD, PBMoves::STEAMERUPTION],
		2.0 => [PBMoves::ICYWIND]},
		:MOVEMESSAGES => {
		"{1} est projeté en contrebas!" => [PBMoves::VITALTHROW, 
			PBMoves::CIRCLETHROW, PBMoves::STORMTHROW],
		"Le vent renforce l'attaque!" => [PBMoves::OMINOUSWIND, PBMoves::SILVERWIND, 
			PBMoves::TWISTER, PBMoves::RAZORWIND, PBMoves::FAIRYWIND], 
		"La neige renforce l'attaque!" => [PBMoves::AVALANCHE, PBMoves::POWDERSNOW],
		"Le froid affaiblit l'attaque..." => [PBMoves::SCALD, PBMoves::STEAMERUPTION],
		"L'ai frais renforce l'attaque!" => [PBMoves::ICYWIND],
		"Yodelahihouu~" => [PBMoves::HYPERVOICE]},
		:TYPETYPEMOD => {PBTypes::ICE => [PBTypes::ROCK]},
		:TYPEDAMAGEBOOST => {
		1.5 => [PBTypes::ROCK,PBTypes::ICE,PBTypes::FLYING],
		0.5 => [PBTypes::FIRE]},
		:TYPEMESSAGES => {
		"La montagne enneigée renforce l'attaque!" => [PBTypes::ROCK,PBTypes::ICE],
		"Le grand air renforce l'attaque!" => [PBTypes::FLYING],
		"TLe froid affaiblit l'attaque!" => [PBTypes::FIRE]},
		:FIELDCHANGE => {PBFields::MOUNTAIN => PBFields::IGNITEMOVES},
		:CHANGEMESSAGE => {"La neige fond!" => PBFields::IGNITEMOVES},
		:STATUSMOVEBOOST => [PBMoves::TAILWIND, PBMoves::SUNNYDAY, PBMoves::HAIL],
		:CHANGEEFFECTS => {},
		:SEED => PBItems::TELLURICSEED,
		:SEEDEFFECT => 0,
		:SEEDEFFECTVAL => 0,
		:SEEDEFFECTSTR => "",
		:SEEDANIM => 0,
		:SEEDSTATS => {PBStats::SPATK => 2, PBStats::ACCURACY => -1}
		},
	# 29 Holy Field
	PBFields::HOLYF => {
		:FIELDNAME => "Terre Sainte",
		:INTROMESSAGE => "Benedictus Sanctus Spiritus...",
		:FIELDGRAPHICS =>  "Holy",
		:SECRETPOWERANIM => PBMoves::DAZZLINGGLEAM,
		:NATUREMOVES => PBMoves::JUDGMENT,
		:MIMICRY => PBTypes::NORMAL,
		:MOVEDAMAGEBOOST => {
		1.3 => [PBMoves::PSYSTRIKE, PBMoves::AEROBLAST, 
				PBMoves::ORIGINPULSE, PBMoves::DOOMDUMMY, PBMoves::MISTBALL, 
				PBMoves::CRUSHGRIP, PBMoves::LUSTERPURGE, PBMoves::SECRETSWORD, 
				PBMoves::PSYCHOBOOST, PBMoves::RELICSONG, PBMoves::SPACIALREND, 
				PBMoves::HYPERSPACEHOLE, PBMoves::ROAROFTIME, PBMoves::LANDSWRATH, 
				PBMoves::PRECIPICEBLADES, PBMoves::DRAGONASCENT, PBMoves::MOONGEISTBEAM, 
				PBMoves::SUNSTEELSTRIKE, PBMoves::PRISMATICLASER, PBMoves::FLEURCANNON, 
				PBMoves::DIAMONDSTORM, PBMoves::GENESISSUPERNOVA, PBMoves::SEARINGSUNRAZESMASH,
				PBMoves::MENACINGMOONRAZEMAELSTROM],
		1.5 => [PBMoves::MYSTICALFIRE, PBMoves::MAGICALLEAF, PBMoves::ANCIENTPOWER,PBMoves::JUDGMENT,
			PBMoves::SACREDFIRE, PBMoves::EXTREMESPEED, PBMoves::SACREDSWORD,PBMoves::RETURN]},
		:MOVEMESSAGES => {
		"La puissance légendaire est amplifiée!" => [PBMoves::PSYSTRIKE, 
			PBMoves::AEROBLAST, PBMoves::SACREDFIRE, PBMoves::ORIGINPULSE, PBMoves::DOOMDUMMY, 
			PBMoves::JUDGMENT, PBMoves::MISTBALL, PBMoves::CRUSHGRIP, PBMoves::LUSTERPURGE, 
			PBMoves::SECRETSWORD, PBMoves::PSYCHOBOOST, PBMoves::RELICSONG, PBMoves::SPACIALREND, 
			PBMoves::HYPERSPACEHOLE, PBMoves::ROAROFTIME, PBMoves::LANDSWRATH, 
			PBMoves::PRECIPICEBLADES, PBMoves::DRAGONASCENT, PBMoves::MOONGEISTBEAM, 
			PBMoves::SUNSTEELSTRIKE, PBMoves::PRISMATICLASER, PBMoves::FLEURCANNON, 
			PBMoves::DIAMONDSTORM, PBMoves::GENESISSUPERNOVA, PBMoves::SEARINGSUNRAZESMASH,
			PBMoves::MENACINGMOONRAZEMAELSTROM],
		"L'énergie sacrée résonne avec l'attaque!" => [PBMoves::MYSTICALFIRE, 
			PBMoves::MAGICALLEAF, PBMoves::ANCIENTPOWER, PBMoves::SACREDSWORD,PBMoves::RETURN],
		"À la vitesse de la lumière!" => [PBMoves::EXTREMESPEED]},
		:TYPEDAMAGEBOOST => {
		1.5 => [PBTypes::FAIRY,PBTypes::NORMAL],
		1.2 => [PBTypes::PSYCHIC,PBTypes::DRAGON],
		0.5 => [PBTypes::GHOST,PBTypes::DARK]},
		:TYPEMESSAGES => {
		"L'énergie sacrée résonne avec l'attaque!" => [PBTypes::FAIRY,PBTypes::NORMAL],
		"L'énergie légendaire résonne avec l'attaque!" => [PBTypes::PSYCHIC,PBTypes::DRAGON],
		"L'attaque est purifiée..." => [PBTypes::GHOST,PBTypes::DARK]},
		:TYPECONDITION => {
			PBTypes::FAIRY => "self.pbIsSpecial?(type)",
			PBTypes::NORMAL => "self.pbIsSpecial?(type)",
			PBTypes::DARK => "self.pbIsSpecial?(type)"
		},
		:FIELDCHANGE => {0 => [PBMoves::LIGHTTHATBURNSTHESKY]},
		:CHANGEMESSAGE => {"La lumière divine est consumée!" => [PBMoves::LIGHTTHATBURNSTHESKY]},
		:STATUSMOVEBOOST => [PBMoves::WISH, PBMoves::MIRACLEEYE, PBMoves::COSMICPOWER, PBMoves::NATURESMADNESS],
		:CHANGEEFFECTS => {},
		:SEED => PBItems::MAGICALSEED,
		:SEEDEFFECT => PBEffects::MagicCoat,
		:SEEDEFFECTVAL => true,
		:SEEDEFFECTSTR => "{1} s'entoure du Reflet Magik!",
		:SEEDANIM => PBMoves::MAGICCOAT,
		:SEEDSTATS => {PBStats::SPATK => 1}
		},
	# 30 Mirror Arena
	PBFields::MIRRORA => {
    	:FIELDNAME => "Palais des Glaces",  
    	:INTROMESSAGE => ["Miroir, mon beau miroir, à qui donneras-tu la victoire?"],
		:FIELDGRAPHICS =>  "Mirror",
		:SECRETPOWERANIM => PBMoves::MIRRORSHOT,
		:NATUREMOVES => PBMoves::MIRRORSHOT,
		:MIMICRY => PBTypes::STEEL,
		:MOVEDAMAGEBOOST => {
		1.5 => PBFields::BLINDINGMOVES,
		2.0 => [PBMoves::MIRRORSHOT]},
		:MOVEMESSAGES => {
		"La lumière réfléchie est aveuglante!" => PBFields::BLINDINGMOVES,
		"Les miroirs renforcent l'attaque!" => [PBMoves::MIRRORSHOT]},
		:FIELDCHANGE => {
		0 => PBFields::QUAKEMOVES + [PBMoves::BOOMBURST, PBMoves::HYPERVOICE, PBMoves::SELFDESTRUCT,
			 PBMoves::EXPLOSION]},
		:STATUSMOVEBOOST => [PBMoves::LIGHTSCREEN, PBMoves::AURORAVEIL, PBMoves::REFLECT, PBMoves::MIRRORMOVE,
		PBMoves::MIRRORCOAT, PBMoves::DOUBLETEAM, PBMoves::FLASH],
		:CHANGEEFFECTS => {},
		:SEED => PBItems::SYNTHETICSEED,
		:SEEDEFFECT => PBEffects::MagicCoat,
		:SEEDEFFECTVAL => true,
		:SEEDEFFECTSTR => "{1} s'entoure du Reflet Magik!",
		:SEEDANIM => PBMoves::MAGICCOAT,
		:SEEDSTATS => {PBStats::EVASION => 1}
		},
	# 31 Fairy Tale Field
	PBFields::FAIRYTALEF => {
		:FIELDNAME => "Conte de Fée",
		:INTROMESSAGE => "Il était une fois...",
		:FIELDGRAPHICS =>  "FairyTale",
		:SECRETPOWERANIM => PBMoves::SLASH,
		:NATUREMOVES => PBMoves::SECRETSWORD,
		:MIMICRY => PBTypes::FAIRY,
		:MOVEDAMAGEBOOST => {
		1.5 => [PBMoves::NIGHTSLASH, PBMoves::LEAFBLADE, PBMoves::PSYCHOCUT, 
						PBMoves::SMARTSTRIKE, PBMoves::AIRSLASH, PBMoves::SOLARBLADE, PBMoves::MAGICALLEAF, 
						PBMoves::MYSTICALFIRE, PBMoves::ANCIENTPOWER, PBMoves::RELICSONG, 
						PBMoves::SPARKLINGARIA, PBMoves::MOONGEISTBEAM, PBMoves::FLEURCANNON,
						PBMoves::OCEANICOPERETTA, PBMoves::MENACINGMOONRAZEMAELSTROM],
		2.0 => [PBMoves::DRAININGKISS]},
		:MOVEMESSAGES => {
		"\"Ma lame te pourfendra!\"" => [PBMoves::NIGHTSLASH, PBMoves::LEAFBLADE, PBMoves::PSYCHOCUT, 
			PBMoves::SMARTSTRIKE, PBMoves::AIRSLASH, PBMoves::SOLARBLADE],
		"L'énergie magique renforce l'attaque!" => [PBMoves::MAGICALLEAF, 
		PBMoves::MYSTICALFIRE, PBMoves::ANCIENTPOWER, PBMoves::RELICSONG, 
		PBMoves::SPARKLINGARIA, PBMoves::MOONGEISTBEAM, PBMoves::FLEURCANNON, PBMoves::OCEANICOPERETTA,
		PBMoves::MENACINGMOONRAZEMAELSTROM],
		"\"De l'amour à la haine!\"" => [PBMoves::DRAININGKISS]},
		:TYPETYPEMOD => {PBTypes::DRAGON => [PBTypes::FIRE]},
		:TYPEDAMAGEBOOST => {
		1.5 => [PBTypes::STEEL,PBTypes::FAIRY],
		2.0 => [PBTypes::DRAGON]},
		:TYPEMESSAGES => {
		"\"Pour l'éternité!\"" => [PBTypes::FAIRY],
		"\"Pour la justice!\"" => [PBTypes::STEEL],
		"L'attaque de la bête est renforcée!" => [PBTypes::DRAGON]},
		:STATUSMOVEBOOST => [PBMoves::KINGSSHIELD, PBMoves::SPIKYSHIELD, PBMoves::CRAFTYSHIELD, PBMoves::FLOWERSHIELD,
			PBMoves::ACIDARMOR, PBMoves::NOBLEROAR, PBMoves::SWORDSDANCE, PBMoves::WISH, PBMoves::HEALINGWISH,
			PBMoves::MIRACLEEYE, PBMoves::FORESTSCURSE, PBMoves::FLORALHEALING],
		:CHANGEEFFECTS => {},
		:SEED => PBItems::MAGICALSEED,
		:SEEDEFFECT => PBEffects::KingsShield,
		:SEEDEFFECTVAL => true,
		:SEEDEFFECTSTR => "La Graine Magique protège {1}!",
		:SEEDANIM => PBMoves::KINGSSHIELD,
		:SEEDSTATS => {}
		},
	# 32 Dragon's Den
	PBFields::DRAGONSD => {
		:FIELDNAME => "Antre du Dragon",
		:INTROMESSAGE => "Qui trop combat le dragon devient dragon lui-même.",
		:FIELDGRAPHICS =>  "DragonsDen",
		:SECRETPOWERANIM => PBMoves::DRAGONPULSE,
		:NATUREMOVES => PBMoves::DRAGONPULSE,
		:MIMICRY => PBTypes::DRAGON,
		:MOVEDAMAGEBOOST => {
		1.5 => [PBMoves::MEGAKICK, PBMoves::MAGMASTORM, PBMoves::LAVAPLUME],
		2.0 => [PBMoves::SMACKDOWN, PBMoves::THOUSANDARROWS, PBMoves::DRAGONASCENT, 
						PBMoves::PAYDAY, PBMoves::TECTONICRAGE, PBMoves::CONTINENTALCRUSH]},
		:MOVEMESSAGES => {
		"L'Épreuve du dragon!!!" => [PBMoves::MEGAKICK], 
		"La lave renforce l'attaque!" => [PBMoves::MAGMASTORM, PBMoves::LAVAPLUME],
		"{1} est projeté dans la lave!" => [PBMoves::SMACKDOWN, PBMoves::THOUSANDARROWS],
		"L'énergie draconique améliore l'attaque!" => [PBMoves::DRAGONASCENT], 
		"Le trésor du dragon!" => [PBMoves::PAYDAY]},
		:MOVETYPEMOD => {PBTypes::FIRE => [PBMoves::SMACKDOWN, PBMoves::THOUSANDARROWS, PBMoves::TECTONICRAGE, PBMoves::CONTINENTALCRUSH]},
		:TYPEDAMAGEBOOST => {
		1.5 => [PBTypes::DRAGON, PBTypes::FIRE],
		0.5 => [PBTypes::ICE,PBTypes::WATER]},
		:TYPEMESSAGES => {
		"La chaleur de la lave attise les flammes!" => [PBTypes::FIRE],
		"L'énergie draconique améliore l'attaque!" => [PBTypes::DRAGON],
		"La chaleur de la lave affaiblit l'attaque..." => [PBTypes::ICE,PBTypes::WATER]},
		:FIELDCHANGE => {PBFields::CAVE => [PBMoves::GLACIATE, PBMoves::SUBZEROSLAMMER, PBMoves::OCEANICOPERETTA, PBMoves::HYDROVORTEX]},
		:CHANGEMESSAGE => {
			"La lave est gelée!" => [PBMoves::GLACIATE, PBMoves::SUBZEROSLAMMER],
			"la lave durcit!" => [PBMoves::OCEANICOPERETTA, PBMoves::HYDROVORTEX]},
		:STATUSMOVEBOOST => [PBMoves::DRAGONDANCE, PBMoves::NOBLEROAR],
		:CHANGEEFFECTS => {},
		:SEED => PBItems::ELEMENTALSEED,
		:SEEDEFFECT => PBEffects::FlashFire,
		:SEEDEFFECTVAL => true,
		:SEEDEFFECTSTR => "{1} augmente sa puissance de Feu!",
		:SEEDANIM => 0,
		:SEEDSTATS => {PBStats::SPATK => 1}
		},
	# 33 Flower Garden Field
	PBFields::FLOWERGARDENF => { #fuck
		:FIELDNAME => "Jardin Fleuri",
		:INTROMESSAGE => "Des graines sillonnent le terrain.",
		:FIELDGRAPHICS => "FlowerGarden0", #fuck?
		:SECRETPOWERANIM => PBMoves::SWEETSCENT, #fuck
		:NATUREMOVES => PBMoves::GROWTH, #later stages handled in function
		:MIMICRY => PBTypes::GRASS,
		:MOVEDAMAGEBOOST => {}, #fuck
		:MOVEMESSAGES => {}, #fuck
		:FIELDCHANGE => {PBFields::BURNINGF => PBFields::IGNITEMOVES},
		:CHANGEMESSAGE => {"The garden caught fire!" => PBFields::IGNITEMOVES},
		:CHANGECONDITION => {PBFields::BURNINGF => "ignitecheck && @battle.field.counter > 1"},
		:DONTCHANGEBACKUP => PBFields::IGNITEMOVES,
		:STATUSMOVEBOOST => [PBMoves::GROWTH, PBMoves::ROTOTILLER, PBMoves::RAINDANCE, 
		PBMoves::WATERSPORT, PBMoves::SUNNYDAY, PBMoves::FLOWERSHIELD, PBMoves::SWEETSCENT, 
		PBMoves::INGRAIN, PBMoves::FLORALHEALING],
		:CHANGEEFFECTS => {},
		:SEED => PBItems::SYNTHETICSEED,
		:SEEDEFFECT => PBEffects::Ingrain,
		:SEEDEFFECTVAL => true,
		:SEEDEFFECTSTR => "{1} plante ses racines!",
		:SEEDANIM => PBMoves::INGRAIN,
		:SEEDSTATS => {PBStats::SPDEF => 1}
		},
	# 34 Starlight Arena
	PBFields::STARLIGHTA => {
		:FIELDNAME => "Piste aux Étoiles",
		:INTROMESSAGE => "Starlight fills the battlefield.",
		:FIELDGRAPHICS =>  "Starlight",
		:SECRETPOWERANIM => PBMoves::SWIFT,
		:NATUREMOVES => PBMoves::MOONBLAST,
		:MIMICRY => PBTypes::DARK,
		:MOVEDAMAGEBOOST => {
		1.5 => [PBMoves::AURORABEAM, PBMoves::SIGNALBEAM, PBMoves::FLASHCANNON, 
				PBMoves::LUSTERPURGE, PBMoves::DAZZLINGGLEAM, PBMoves::MIRRORSHOT, 
				PBMoves::TECHNOBLAST, PBMoves::SOLARBEAM, PBMoves::PHOTONGEYSER, 
				PBMoves::MOONBLAST,],
		2.0 => [PBMoves::DRACOMETEOR, PBMoves::METEORMASH, PBMoves::COMETPUNCH, 
				PBMoves::SPACIALREND, PBMoves::SWIFT, PBMoves::HYPERSPACEHOLE, 
				PBMoves::HYPERSPACEFURY, PBMoves::MOONGEISTBEAM, PBMoves::SUNSTEELSTRIKE,
				PBMoves::BLACKHOLEECLIPSE, PBMoves::SEARINGSUNRAZESMASH, PBMoves::MENACINGMOONRAZEMAELSTROM],
		4.0 => [PBMoves::DOOMDUMMY]},
		:MOVEMESSAGES => {
		"Starlight surged through the attack!" => [PBMoves::AURORABEAM, PBMoves::SIGNALBEAM, 
			PBMoves::FLASHCANNON, PBMoves::LUSTERPURGE, PBMoves::DAZZLINGGLEAM, PBMoves::MIRRORSHOT, 
			PBMoves::TECHNOBLAST, PBMoves::SOLARBEAM, PBMoves::PHOTONGEYSER],
		"Lunar energy surged through the attack!" => [PBMoves::MOONBLAST],
		"The astral energy boosted the attack!" => [PBMoves::DRACOMETEOR, PBMoves::METEORMASH, 
			PBMoves::COMETPUNCH, PBMoves::SPACIALREND, PBMoves::SWIFT,  
			PBMoves::HYPERSPACEFURY, PBMoves::MOONGEISTBEAM, PBMoves::SUNSTEELSTRIKE, 
			PBMoves::BLACKHOLEECLIPSE, PBMoves::SEARINGSUNRAZESMASH, PBMoves::MENACINGMOONRAZEMAELSTROM],
		"The astral vortex accelerated the attack!" => [PBMoves::HYPERSPACEHOLE],
		"A star came crashing down!" => [PBMoves::DOOMDUMMY]},
		:MOVETYPEMOD => {PBTypes::FIRE => [PBMoves::DOOMDUMMY]},
		:TYPETYPEMOD => {PBTypes::FAIRY => [PBTypes::DARK]},
		:TYPEDAMAGEBOOST => {
		1.5 => [PBTypes::DARK,PBTypes::PSYCHIC],
		1.3 => [PBTypes::FAIRY]},
		:TYPEMESSAGES => {
		"Starlight supercharged the attack!" => [PBTypes::FAIRY],
		"The night sky boosted the attack!" => [PBTypes::DARK],
		"The astral energy boosted the attack!" => [PBTypes::PSYCHIC]},
		:FIELDCHANGE => {0 => [PBMoves::LIGHTTHATBURNSTHESKY]},
		:CHANGEMESSAGE => {"The cosmic light was consumed!" => [PBMoves::LIGHTTHATBURNSTHESKY]},
		:STATUSMOVEBOOST => [PBMoves::COSMICPOWER, PBMoves::FLASH, PBMoves::WISH, PBMoves::HEALINGWISH, PBMoves::LUNARDANCE, PBMoves::MOONLIGHT],
		:CHANGEEFFECTS => {},
		:SEED => PBItems::MAGICALSEED,
		:SEEDEFFECT => PBEffects::Wish,
		:SEEDEFFECTVAL => 2,
		:SEEDEFFECTSTR => "A wish was made for {1}!",
		:SEEDANIM => PBMoves::WISH,
		:SEEDSTATS => {PBStats::SPATK => 1}
		},
	# 35 New World
	PBFields::NEWW => {
		:FIELDNAME => "Nouveau Monde",
		:INTROMESSAGE => ["From darkness, from stardust,","From memories of eons past and visions yet to come..."],
		:FIELDGRAPHICS =>  "NewWorld",
		:SECRETPOWERANIM => PBMoves::ROAROFTIME,
		:NATUREMOVES => PBMoves::SPACIALREND,
		:MIMICRY => PBTypes::QMARKS, #RNG
		:MOVEDAMAGEBOOST => {
		1.5 => [PBMoves::AURORABEAM, PBMoves::SIGNALBEAM, PBMoves::FLASHCANNON, 
				PBMoves::DAZZLINGGLEAM, PBMoves::MIRRORSHOT, PBMoves::PHOTONGEYSER, 
				PBMoves::PSYSTRIKE, PBMoves::AEROBLAST, PBMoves::SACREDFIRE, PBMoves::MISTBALL, 
				PBMoves::LUSTERPURGE, PBMoves::ORIGINPULSE, PBMoves::PRECIPICEBLADES, 
				PBMoves::DRAGONASCENT, PBMoves::PSYCHOBOOST, PBMoves::ROAROFTIME, 
				PBMoves::MAGMASTORM, PBMoves::CRUSHGRIP, PBMoves::JUDGMENT, PBMoves::SEEDFLARE, 
				PBMoves::SHADOWFORCE, PBMoves::SEARINGSHOT, PBMoves::VCREATE, 
				PBMoves::SECRETSWORD, PBMoves::SACREDSWORD, PBMoves::RELICSONG, 
				PBMoves::FUSIONBOLT, PBMoves::FUSIONFLARE, PBMoves::ICEBURN, 
				PBMoves::FREEZESHOCK, PBMoves::BOLTSTRIKE, PBMoves::BLUEFLARE, 
				PBMoves::TECHNOBLAST, PBMoves::OBLIVIONWING, PBMoves::LANDSWRATH, 
				PBMoves::THOUSANDARROWS, PBMoves::THOUSANDWAVES, PBMoves::DIAMONDSTORM, 
				PBMoves::STEAMERUPTION, PBMoves::COREENFORCER, PBMoves::FLEURCANNON, 
				PBMoves::PRISMATICLASER, PBMoves::SUNSTEELSTRIKE, PBMoves::SPECTRALTHIEF, 
				PBMoves::MOONGEISTBEAM, PBMoves::MULTIATTACK, PBMoves::MINDBLOWN, 
				PBMoves::PLASMAFISTS, PBMoves::EARTHPOWER, PBMoves::POWERGEM, 
				PBMoves::ERUPTION, PBMoves::CONTINENTALCRUSH, PBMoves::GENESISSUPERNOVA,
				PBMoves::SOULSTEALING7STARSTRIKE, PBMoves::SEARINGSUNRAZESMASH,
				PBMoves::MENACINGMOONRAZEMAELSTROM],
		2.0 => [PBMoves::VACUUMWAVE, PBMoves::DRACOMETEOR, PBMoves::METEORMASH, 
				PBMoves::MOONBLAST, PBMoves::COMETPUNCH, PBMoves::SWIFT, 
				PBMoves::HYPERSPACEHOLE, PBMoves::SPACIALREND, PBMoves::HYPERSPACEFURY, 
				PBMoves::ANCIENTPOWER, PBMoves::FUTUREDUMMY, PBMoves::BLACKHOLEECLIPSE],
		4.0 => [PBMoves::DOOMDUMMY],
		0.25 => [PBMoves::EARTHQUAKE, PBMoves::MAGNITUDE, PBMoves::BULLDOZE]},
		:MOVEACCURACYBOOST => {85 => [PBMoves::DARKVOID]},
		:MOVEMESSAGES => {
		"The light shone through the infinite darkness!" => [PBMoves::AURORABEAM, 
			PBMoves::SIGNALBEAM, PBMoves::FLASHCANNON, PBMoves::DAZZLINGGLEAM, 
			PBMoves::MIRRORSHOT, PBMoves::PHOTONGEYSER],
		"The ethereal energy strengthened the attack!" => [PBMoves::PSYSTRIKE, PBMoves::AEROBLAST,
			PBMoves::SACREDFIRE, PBMoves::MISTBALL, PBMoves::LUSTERPURGE, PBMoves::ORIGINPULSE, 
			PBMoves::PRECIPICEBLADES, PBMoves::DRAGONASCENT, PBMoves::PSYCHOBOOST, 
			PBMoves::ROAROFTIME, PBMoves::MAGMASTORM, PBMoves::CRUSHGRIP, PBMoves::JUDGMENT, 
			PBMoves::SEEDFLARE, PBMoves::SHADOWFORCE, PBMoves::SEARINGSHOT, PBMoves::VCREATE, 
			PBMoves::SECRETSWORD, PBMoves::SACREDSWORD, PBMoves::RELICSONG, PBMoves::FUSIONBOLT, 
			PBMoves::FUSIONFLARE, PBMoves::ICEBURN, PBMoves::FREEZESHOCK, PBMoves::BOLTSTRIKE, 
			PBMoves::BLUEFLARE, PBMoves::TECHNOBLAST, PBMoves::OBLIVIONWING, PBMoves::LANDSWRATH, 
			PBMoves::THOUSANDARROWS, PBMoves::THOUSANDWAVES, PBMoves::DIAMONDSTORM, 
			PBMoves::STEAMERUPTION, PBMoves::COREENFORCER, PBMoves::FLEURCANNON, 
			PBMoves::PRISMATICLASER, PBMoves::SUNSTEELSTRIKE, PBMoves::SPECTRALTHIEF, 
			PBMoves::MOONGEISTBEAM, PBMoves::MULTIATTACK, PBMoves::MINDBLOWN, 
			PBMoves::PLASMAFISTS, PBMoves::GENESISSUPERNOVA, PBMoves::SOULSTEALING7STARSTRIKE,
			PBMoves::SEARINGSUNRAZESMASH, PBMoves::MENACINGMOONRAZEMAELSTROM], 
		"The germinal matter amassed in the attack!" => [PBMoves::EARTHPOWER, PBMoves::POWERGEM, 
			PBMoves::ERUPTION, PBMoves::CONTINENTALCRUSH],
		"The astral energy boosted the attack!" => [PBMoves::VACUUMWAVE, PBMoves::DRACOMETEOR, 
			PBMoves::METEORMASH, PBMoves::MOONBLAST, PBMoves::COMETPUNCH, PBMoves::SWIFT, 
			PBMoves::HYPERSPACEHOLE, PBMoves::SPACIALREND, PBMoves::HYPERSPACEFURY, 
			PBMoves::ANCIENTPOWER, PBMoves::FUTUREDUMMY],
		"A star came crashing down on {1}!" => [PBMoves::DOOMDUMMY], 
		"{1} was swallowed up by the void!" => [PBMoves::BLACKHOLEECLIPSE],
		"The unformed land diffused the attack..." => [PBMoves::EARTHQUAKE, 
			PBMoves::MAGNITUDE, PBMoves::BULLDOZE]},
		:MOVETYPEMOD => {PBTypes::FIRE => [PBMoves::DOOMDUMMY]},
		:TYPEDAMAGEBOOST => {1.5 => [PBTypes::DARK]},
		:TYPEMESSAGES => {"Infinity boosted the attack!" => [PBTypes::DARK]},
		:FIELDCHANGE => {PBFields::STARLIGHTA => [PBMoves::GRAVITY, PBMoves::GEOMANCY]},
		:DONTCHANGEBACKUP => [PBMoves::GRAVITY],
		:CHANGEMESSAGE => {
		"The world's matter reformed!" => [PBMoves::GRAVITY],
		"The world was regenerated!" => [PBMoves::GEOMANCY]},
		:STATUSMOVEBOOST => [PBMoves::DARKVOID, PBMoves::HEARTSWAP, PBMoves::TRICKROOM, PBMoves::MAGICROOM, PBMoves::WONDERROOM, PBMoves::COSMICPOWER, PBMoves::FLASH, PBMoves::MOONLIGHT, PBMoves::NATURESMADNESS],
		:CHANGEEFFECTS => {},
		:SEED => PBItems::MAGICALSEED,
		:SEEDEFFECT => PBEffects::HyperBeam,
		:SEEDEFFECTVAL => 1,
		:SEEDEFFECTSTR => "{1} must recharge!",
		:SEEDANIM => 0,
		:SEEDSTATS => {PBStats::ATTACK => 1,PBStats::DEFENSE => 1,PBStats::SPEED => 1,PBStats::SPATK => 1,PBStats::SPDEF => 1}
		},
	# 36 Inverse Field
	PBFields::INVERSEF => {
		:FIELDNAME => "Terrain Inversé",
		:INTROMESSAGE => "!tabmoC ud tubéD",
		:FIELDGRAPHICS =>  "Inverse",
		:SECRETPOWERANIM => PBMoves::CONFUSION,
		:NATUREMOVES => PBMoves::TRICKROOM,
		:MIMICRY => PBTypes::NORMAL,
		:MOVEDAMAGEBOOST => {},
		:MOVEMESSAGES => {},
		:FIELDCHANGE => {},
		:CHANGEMESSAGE => {},
		:STATUSMOVEBOOST => [],
		:CHANGEEFFECTS => {},
		:SEED => PBItems::MAGICALSEED,
		:SEEDEFFECT => PBEffects::HyperBeam,
		:SEEDEFFECTVAL => 1,
		:SEEDEFFECTSTR => "{1} must recharge!",
		:SEEDANIM => 0,
		:SEEDSTATS => {PBStats::ATTACK => 1,PBStats::DEFENSE => 1,PBStats::SPEED => 1,PBStats::SPATK => 1,PBStats::SPDEF => 1}
		},
	# 37 Psychic Terrain
	PBFields::PSYCHICT => {
		:FIELDNAME => "Psychic Terrain",
		:INTROMESSAGE => "The field became mysterious!",
		:FIELDGRAPHICS =>  "Psychic",
		:SECRETPOWERANIM => PBMoves::PSYCHIC,
		:NATUREMOVES => PBMoves::PSYCHIC,
		:MIMICRY => PBTypes::PSYCHIC, #easy
		:MOVEDAMAGEBOOST => {
		1.5 => [PBMoves::HEX, PBMoves::MAGICALLEAF, PBMoves::MYSTICALFIRE, 
						PBMoves::MOONBLAST, PBMoves::AURASPHERE, PBMoves::MINDBLOWN]},
		:MOVEACCURACYBOOST => {90 => [PBMoves::HYPNOSIS]},
		:MOVEMESSAGES => {
		"The psychic energy strengthened the attack!" => [PBMoves::HEX, PBMoves::MAGICALLEAF, 
			PBMoves::MYSTICALFIRE, PBMoves::MOONBLAST, PBMoves::AURASPHERE, PBMoves::MINDBLOWN]},
		:TYPEDAMAGEBOOST => {1.5 => [PBTypes::PSYCHIC]},
		:TYPEMESSAGES => {"The Psychic Terrain strengthened the attack!" => [PBTypes::PSYCHIC]},
		:TYPECONDITION => {PBTypes::ELECTRIC => "!attacker.isAirborne?" },
		:FIELDCHANGE => {},
		:CHANGEMESSAGE => {},
		:STATUSMOVEBOOST => [PBMoves::CALMMIND, PBMoves::COSMICPOWER, PBMoves::KINESIS, PBMoves::MEDITATE,
			PBMoves::NASTYPLOT, PBMoves::HYPNOSIS, PBMoves::TELEKINESIS, PBMoves::GRAVITY, PBMoves::MAGICROOM,
			PBMoves::TRICKROOM, PBMoves::WONDERROOM],
		:CHANGEEFFECTS => {},
		:SEED => PBItems::MAGICALSEED,
		:SEEDEFFECT => 0,
		:SEEDEFFECTVAL => 0,
		:SEEDEFFECTSTR => "{1} became confused!",
		:SEEDANIM => 0,
		:SEEDSTATS => {PBStats::SPATK => 2}
		},
	PBFields::INDOORA => {
		:FIELDGRAPHICS =>  "IndoorA",
		:SECRETPOWERANIM => PBMoves::TRIATTACK,
		:NATUREMOVES => PBMoves::TRIATTACK,
		:MIMICRY => PBTypes::NORMAL,
		:CHANGEMESSAGE => {},
		:CHANGEEFFECTS => {},
		:SEED => {}
		},
	PBFields::INDOORB => {
		:FIELDGRAPHICS =>  "IndoorB",
		:SECRETPOWERANIM => PBMoves::TRIATTACK,
		:NATUREMOVES => PBMoves::TRIATTACK,
		:MIMICRY => PBTypes::NORMAL,
		:CHANGEMESSAGE => {},
		:CHANGEEFFECTS => {},
		:SEED => {}
		},
	PBFields::INDOORC => {
		:FIELDGRAPHICS =>  "IndoorC",
		:SECRETPOWERANIM => PBMoves::TRIATTACK,
		:NATUREMOVES => PBMoves::TRIATTACK,
		:MIMICRY => PBTypes::NORMAL,
		:CHANGEMESSAGE => {},
		:CHANGEEFFECTS => {},
		:SEED => {}
		},
	PBFields::CITY => {
		:FIELDGRAPHICS =>  "City",
		:SECRETPOWERANIM => PBMoves::TRIATTACK,
		:NATUREMOVES => PBMoves::TRIATTACK,
		:MIMICRY => PBTypes::NORMAL,
		:CHANGEMESSAGE => {},
		:CHANGEEFFECTS => {},
		:SEED => {}
		},
	PBFields::CITYNEW => {
		:FIELDGRAPHICS =>  "CityNew",
		:SECRETPOWERANIM => PBMoves::TRIATTACK,
		:NATUREMOVES => PBMoves::TRIATTACK,
		:MIMICRY => PBTypes::NORMAL,
		:CHANGEEFFECTS => {},
		:SEED => {}
		} 
}

